// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Quickcode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.IdentityModule.Domain.Entities;
using QuickCode.Quickcode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Features.ApiMethodDefinition
{
    public class GetApiMethodDefinitionsByUrlQuery : IRequest<Response<List<GetApiMethodDefinitionsByUrlResponseDto>>>
    {
        public string ApiMethodDefinitionUrlPath { get; set; }

        public GetApiMethodDefinitionsByUrlQuery(string apiMethodDefinitionUrlPath)
        {
            this.ApiMethodDefinitionUrlPath = apiMethodDefinitionUrlPath;
        }

        public class GetApiMethodDefinitionsByUrlHandler : IRequestHandler<GetApiMethodDefinitionsByUrlQuery, Response<List<GetApiMethodDefinitionsByUrlResponseDto>>>
        {
            private readonly ILogger<GetApiMethodDefinitionsByUrlHandler> _logger;
            private readonly IApiMethodDefinitionRepository _repository;
            public GetApiMethodDefinitionsByUrlHandler(ILogger<GetApiMethodDefinitionsByUrlHandler> logger, IApiMethodDefinitionRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetApiMethodDefinitionsByUrlResponseDto>>> Handle(GetApiMethodDefinitionsByUrlQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetApiMethodDefinitionsByUrlAsync(request.ApiMethodDefinitionUrlPath);
                return returnValue.ToResponse();
            }
        }
    }
}