// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Quickcode.Portal.Models;
using QuickCode.Quickcode.Portal.Models.QuickcodeModule;
using QuickCode.Quickcode.Portal.Helpers;
using QuickCode.Quickcode.Infrastructure.Integration.Models;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.Quickcode.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using QuickcodeModuleContracts = QuickCode.Quickcode.Infrastructure.Integration.Nswag.Clients.QuickcodeModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Quickcode.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Quickcode.Portal.Controllers.QuickcodeModule
{
    [Permission("QuickcodeModuleGenerationLogs")]
    [Area("QuickcodeModule")]
    [Route("QuickcodeModuleGenerationLogs")]
    public partial class GenerationLogsController : BaseController
    {
        private readonly QuickcodeModuleContracts.IGenerationLogsClient pageClient;
        private readonly QuickcodeModuleContracts.IProjectsClient pageProjectClient;
        private readonly QuickcodeModuleContracts.IGenerationStatusesClient pageGenerationStatusClient;
        public GenerationLogsController(QuickcodeModuleContracts.IGenerationLogsClient pageClient, QuickcodeModuleContracts.IProjectsClient pageProjectClient, QuickcodeModuleContracts.IGenerationStatusesClient pageGenerationStatusClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageProjectClient = pageProjectClient;
            this.pageGenerationStatusClient = pageGenerationStatusClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(GenerationLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("ListPartial")]
        [HttpPost]
        public async Task<IActionResult> ListPartial(GenerationLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return PartialView("_ListTable", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(GenerationLogData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.GenerationLogsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(GenerationLogData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.GenerationLogsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(GenerationLogData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.GenerationLogsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(GenerationLogData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(GenerationLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(GenerationLogData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(GenerationLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<GenerationLogData> PrepareModel()
        {
            var model = GetModel<GenerationLogData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<GenerationLogData> PrepareModel(GenerationLogData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            var result = await pageClient.GenerationLogsListAsync(model.CurrentPage, model.PageSize, includeCount: true);
            model.NumberOfRecord = result?.TotalCount ?? 0;
            model.TotalPage = model.PageSize <= 0 ? 0 : (model.NumberOfRecord + model.PageSize - 1) / model.PageSize;
            if (model.TotalPage > 0 && model.CurrentPage > model.TotalPage)
            {
                model.CurrentPage = model.TotalPage;
                result = await pageClient.GenerationLogsListAsync(model.CurrentPage, model.PageSize, includeCount: false);
            }

            model.List = result?.Items?.ToList() ?? new();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("Projects", async () => ToComboItems((await pageProjectClient.ProjectsListAsync())?.Items)));
            comboBoxList.AddRange(await FillComboBoxAsync("GenerationStatuses", async () => ToComboItems((await pageGenerationStatusClient.GenerationStatusesListAsync())?.Items)));
            return comboBoxList;
        }

        [Route("Queries/GetLogsByProject")]
        public async Task<IActionResult> QueryGetLogsByProject()
        {
            var model = GetModel<GenerationLogGetLogsByProjectData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetLogsByProject", model);
        }

        [Route("Queries/GetLogsByProject")]
        [HttpPost]
        public async Task<IActionResult> QueryGetLogsByProject(GenerationLogGetLogsByProjectData model)
        {
            model = await PrepareQueryGetLogsByProjectModel(model);
            return View("GetLogsByProject", model);
        }

        [Route("Queries/GetLogsByProjectPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetLogsByProjectPartial(GenerationLogGetLogsByProjectData model)
        {
            model = await PrepareQueryGetLogsByProjectModel(model);
            return PartialView("_GetLogsByProjectTable", model);
        }

        private async Task<GenerationLogGetLogsByProjectData> PrepareQueryGetLogsByProjectModel(GenerationLogGetLogsByProjectData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.GenerationLogsGetLogsByProjectAsync(model.GenerationLogProjectId);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetLogsByProjectAndStatus")]
        public async Task<IActionResult> QueryGetLogsByProjectAndStatus()
        {
            var model = GetModel<GenerationLogGetLogsByProjectAndStatusData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetLogsByProjectAndStatus", model);
        }

        [Route("Queries/GetLogsByProjectAndStatus")]
        [HttpPost]
        public async Task<IActionResult> QueryGetLogsByProjectAndStatus(GenerationLogGetLogsByProjectAndStatusData model)
        {
            model = await PrepareQueryGetLogsByProjectAndStatusModel(model);
            return View("GetLogsByProjectAndStatus", model);
        }

        [Route("Queries/GetLogsByProjectAndStatusPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetLogsByProjectAndStatusPartial(GenerationLogGetLogsByProjectAndStatusData model)
        {
            model = await PrepareQueryGetLogsByProjectAndStatusModel(model);
            return PartialView("_GetLogsByProjectAndStatusTable", model);
        }

        private async Task<GenerationLogGetLogsByProjectAndStatusData> PrepareQueryGetLogsByProjectAndStatusModel(GenerationLogGetLogsByProjectAndStatusData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.GenerationLogsGetLogsByProjectAndStatusAsync(model.GenerationLogProjectId, model.GenerationLogGenerationStatusId);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetRecentLogsByProject")]
        public async Task<IActionResult> QueryGetRecentLogsByProject()
        {
            var model = GetModel<GenerationLogGetRecentLogsByProjectData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetRecentLogsByProject", model);
        }

        [Route("Queries/GetRecentLogsByProject")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentLogsByProject(GenerationLogGetRecentLogsByProjectData model)
        {
            model = await PrepareQueryGetRecentLogsByProjectModel(model);
            return View("GetRecentLogsByProject", model);
        }

        [Route("Queries/GetRecentLogsByProjectPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentLogsByProjectPartial(GenerationLogGetRecentLogsByProjectData model)
        {
            model = await PrepareQueryGetRecentLogsByProjectModel(model);
            return PartialView("_GetRecentLogsByProjectTable", model);
        }

        private async Task<GenerationLogGetRecentLogsByProjectData> PrepareQueryGetRecentLogsByProjectModel(GenerationLogGetRecentLogsByProjectData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.GenerationLogsGetRecentLogsByProjectAsync(model.GenerationLogProjectId);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }
    }
}