// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.QuickCode.Portal.Models;
using QuickCode.QuickCode.Portal.Models.QuickCodeModule;
using QuickCode.QuickCode.Portal.Helpers;
using QuickCode.QuickCode.Infrastructure.Integration.Models;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.QuickCode.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using QuickCodeModuleContracts = QuickCode.QuickCode.Infrastructure.Integration.Nswag.Clients.QuickCodeModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.QuickCode.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.QuickCode.Portal.Controllers.QuickCodeModule
{
    [Permission("QuickCodeModuleProjectSchemaSnapshots")]
    [Area("QuickCodeModule")]
    [Route("QuickCodeModuleProjectSchemaSnapshots")]
    public partial class ProjectSchemaSnapshotsController : BaseController
    {
        private readonly QuickCodeModuleContracts.IProjectSchemaSnapshotsClient pageClient;
        private readonly QuickCodeModuleContracts.IProjectsClient pageProjectClient;
        public ProjectSchemaSnapshotsController(QuickCodeModuleContracts.IProjectSchemaSnapshotsClient pageClient, QuickCodeModuleContracts.IProjectsClient pageProjectClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageProjectClient = pageProjectClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(ProjectSchemaSnapshotData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("ListPartial")]
        [HttpPost]
        public async Task<IActionResult> ListPartial(ProjectSchemaSnapshotData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return PartialView("_ListTable", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(ProjectSchemaSnapshotData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.ProjectSchemaSnapshotsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(ProjectSchemaSnapshotData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.ProjectSchemaSnapshotsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(ProjectSchemaSnapshotData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.ProjectSchemaSnapshotsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(ProjectSchemaSnapshotData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(ProjectSchemaSnapshotData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(ProjectSchemaSnapshotData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(ProjectSchemaSnapshotData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<ProjectSchemaSnapshotData> PrepareModel()
        {
            var model = GetModel<ProjectSchemaSnapshotData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<ProjectSchemaSnapshotData> PrepareModel(ProjectSchemaSnapshotData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            var result = await pageClient.ProjectSchemaSnapshotsListAsync(model.CurrentPage, model.PageSize, includeCount: true);
            model.NumberOfRecord = result?.TotalCount ?? 0;
            model.TotalPage = model.PageSize <= 0 ? 0 : (model.NumberOfRecord + model.PageSize - 1) / model.PageSize;
            if (model.TotalPage > 0 && model.CurrentPage > model.TotalPage)
            {
                model.CurrentPage = model.TotalPage;
                result = await pageClient.ProjectSchemaSnapshotsListAsync(model.CurrentPage, model.PageSize, includeCount: false);
            }

            model.List = result?.Items?.ToList() ?? new();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("Projects", async () => ToComboItems((await pageProjectClient.ProjectsListAsync())?.Items)));
            return comboBoxList;
        }

        [Route("Queries/GetByProject")]
        public async Task<IActionResult> QueryGetByProject()
        {
            var model = GetModel<ProjectSchemaSnapshotGetByProjectData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetByProject", model);
        }

        [Route("Queries/GetByProject")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByProject(ProjectSchemaSnapshotGetByProjectData model)
        {
            model = await PrepareQueryGetByProjectModel(model);
            return View("GetByProject", model);
        }

        [Route("Queries/GetByProjectPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByProjectPartial(ProjectSchemaSnapshotGetByProjectData model)
        {
            model = await PrepareQueryGetByProjectModel(model);
            return PartialView("_GetByProjectTable", model);
        }

        private async Task<ProjectSchemaSnapshotGetByProjectData> PrepareQueryGetByProjectModel(ProjectSchemaSnapshotGetByProjectData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.ProjectSchemaSnapshotsGetByProjectAsync(model.ProjectsKey);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetByTrigger")]
        public async Task<IActionResult> QueryGetByTrigger()
        {
            var model = GetModel<ProjectSchemaSnapshotGetByTriggerData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetByTrigger", model);
        }

        [Route("Queries/GetByTrigger")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByTrigger(ProjectSchemaSnapshotGetByTriggerData model)
        {
            model = await PrepareQueryGetByTriggerModel(model);
            return View("GetByTrigger", model);
        }

        [Route("Queries/GetByTriggerPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByTriggerPartial(ProjectSchemaSnapshotGetByTriggerData model)
        {
            model = await PrepareQueryGetByTriggerModel(model);
            return PartialView("_GetByTriggerTable", model);
        }

        private async Task<ProjectSchemaSnapshotGetByTriggerData> PrepareQueryGetByTriggerModel(ProjectSchemaSnapshotGetByTriggerData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.ProjectSchemaSnapshotsGetByTriggerAsync(model.ProjectsKey, model.ProjectSchemaSnapshotsTrigger);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetSnapshot")]
        public async Task<IActionResult> QueryGetSnapshot()
        {
            var model = GetModel<ProjectSchemaSnapshotGetSnapshotData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetSnapshot", model);
        }

        [Route("Queries/GetSnapshot")]
        [HttpPost]
        public async Task<IActionResult> QueryGetSnapshot(ProjectSchemaSnapshotGetSnapshotData model)
        {
            model = await PrepareQueryGetSnapshotModel(model);
            return View("GetSnapshot", model);
        }

        [Route("Queries/GetSnapshotPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetSnapshotPartial(ProjectSchemaSnapshotGetSnapshotData model)
        {
            model = await PrepareQueryGetSnapshotModel(model);
            return PartialView("_GetSnapshotTable", model);
        }

        private async Task<ProjectSchemaSnapshotGetSnapshotData> PrepareQueryGetSnapshotModel(ProjectSchemaSnapshotGetSnapshotData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.ProjectSchemaSnapshotsGetSnapshotAsync(model.ProjectSchemaSnapshotId);
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetSnapshotModules")]
        public async Task<IActionResult> QueryGetSnapshotModules()
        {
            var model = GetModel<ProjectSchemaSnapshotGetSnapshotModulesData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetSnapshotModules", model);
        }

        [Route("Queries/GetSnapshotModules")]
        [HttpPost]
        public async Task<IActionResult> QueryGetSnapshotModules(ProjectSchemaSnapshotGetSnapshotModulesData model)
        {
            model = await PrepareQueryGetSnapshotModulesModel(model);
            return View("GetSnapshotModules", model);
        }

        [Route("Queries/GetSnapshotModulesPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetSnapshotModulesPartial(ProjectSchemaSnapshotGetSnapshotModulesData model)
        {
            model = await PrepareQueryGetSnapshotModulesModel(model);
            return PartialView("_GetSnapshotModulesTable", model);
        }

        private async Task<ProjectSchemaSnapshotGetSnapshotModulesData> PrepareQueryGetSnapshotModulesModel(ProjectSchemaSnapshotGetSnapshotModulesData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.ProjectSchemaSnapshotsGetSnapshotModulesAsync(model.ProjectSchemaSnapshotId);
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }
    }
}