<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <NoWarn>CS8669;AD0001</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
    <Compile Remove="Properties\AssemblyInfo.qc.cs" />
  </ItemGroup>
   <ItemGroup>
    <ProjectReference Include="..\QuickCode.QuickCode.IdentityModule.Domain\QuickCode.QuickCode.IdentityModule.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\QuickCode.QuickCode.Application.Contracts\QuickCode.QuickCode.Application.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
