// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.QuickCode.IdentityModule.Application.Dtos.ApiKey;

namespace QuickCode.QuickCode.IdentityModule.Persistence.Repositories;
internal static class ApiKeyCrudSqlBindings
{
    public const string StoreTableName = "ApiKeys";
    public const string ParameterNamePrefix = "ApiKey";
    public const string IdParameterName = "PRM_API_KEY_ID";
    public static class OperationNames
    {
        public const string ApiKeyNameIsExists = "ApiKeyNameIsExists";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetApiKeyByPrefix = "GetApiKeyByPrefix";
        public const string GetByName = "GetByName";
        public const string GetByPermissionGroup = "GetByPermissionGroup";
        public const string GetByPk = "GetByPk";
        public const string GetByPrefix = "GetByPrefix";
        public const string GetByStatus = "GetByStatus";
        public const string Insert = "Insert";
        public const string RevokeApiKey = "RevokeApiKey";
        public const string Select = "Select";
        public const string TouchApiKeyLastUsed = "TouchApiKeyLastUsed";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("Id", nameof(ApiKeyDto.Id)),
        ("Name", nameof(ApiKeyDto.Name)),
        ("Description", nameof(ApiKeyDto.Description)),
        ("KeyPrefix", nameof(ApiKeyDto.KeyPrefix)),
        ("KeyHash", nameof(ApiKeyDto.KeyHash)),
        ("PermissionGroupName", nameof(ApiKeyDto.PermissionGroupName)),
        ("CreatedByUserId", nameof(ApiKeyDto.CreatedByUserId)),
        ("Status", nameof(ApiKeyDto.Status)),
        ("IsActive", nameof(ApiKeyDto.IsActive)),
        ("ExpiresAt", nameof(ApiKeyDto.ExpiresAt)),
        ("LastUsedAt", nameof(ApiKeyDto.LastUsedAt)),
        ("CreatedDate", nameof(ApiKeyDto.CreatedDate)),
        ("RevokedDate", nameof(ApiKeyDto.RevokedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("Name", nameof(ApiKeyDto.Name)),
        ("Description", nameof(ApiKeyDto.Description)),
        ("KeyPrefix", nameof(ApiKeyDto.KeyPrefix)),
        ("KeyHash", nameof(ApiKeyDto.KeyHash)),
        ("PermissionGroupName", nameof(ApiKeyDto.PermissionGroupName)),
        ("CreatedByUserId", nameof(ApiKeyDto.CreatedByUserId)),
        ("Status", nameof(ApiKeyDto.Status)),
        ("IsActive", nameof(ApiKeyDto.IsActive)),
        ("ExpiresAt", nameof(ApiKeyDto.ExpiresAt)),
        ("LastUsedAt", nameof(ApiKeyDto.LastUsedAt)),
        ("CreatedDate", nameof(ApiKeyDto.CreatedDate)),
        ("RevokedDate", nameof(ApiKeyDto.RevokedDate)),
        ("Id", nameof(ApiKeyDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("Id", nameof(ApiKeyDto.Id))
    };
}