// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.IdentityModule.Application.Features.AspNetUserToken;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.AspNetUserToken;
using QuickCode.QuickCode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.QuickCode.Infrastructure.Web.Helpers;
using QuickCode.QuickCode.Application.Contracts;

namespace QuickCode.QuickCode.IdentityModule.Application.Tests.Features.AspNetUserToken
{
    public class InsertAspNetUserTokenCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IAspNetUserTokenRepository> _repositoryMock;
        private readonly Mock<ILogger<InsertAspNetUserTokenCommand.InsertAspNetUserTokenHandler>> _loggerMock;
        public InsertAspNetUserTokenCommandTests()
        {
            _repositoryMock = new Mock<IAspNetUserTokenRepository>();
            _loggerMock = new Mock<ILogger<InsertAspNetUserTokenCommand.InsertAspNetUserTokenHandler>>();
        }

        [Fact]
        public async Task Handle_Should_Return_Success_When_Valid_Command()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<AspNetUserTokenDto>("tr");
            var fakeResponse = new RepoResponse<AspNetUserTokenDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<AspNetUserTokenDto>())).ReturnsAsync(fakeResponse);
            var handler = new InsertAspNetUserTokenCommand.InsertAspNetUserTokenHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new InsertAspNetUserTokenCommand(fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<AspNetUserTokenDto>()), Times.Once);
        }

        [Fact]
        public async Task Handle_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<AspNetUserTokenDto>("tr");
            var fakeResponse = new RepoResponse<AspNetUserTokenDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<AspNetUserTokenDto>())).ReturnsAsync(fakeResponse);
            var handler = new InsertAspNetUserTokenCommand.InsertAspNetUserTokenHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new InsertAspNetUserTokenCommand(fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}