// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Quickcode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.IdentityModule.Domain.Entities;
using QuickCode.Quickcode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.ApiKey;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Features.ApiKey
{
    public class InsertApiKeyCommand : IRequest<Response<ApiKeyDto>>
    {
        public ApiKeyDto request { get; set; }

        public InsertApiKeyCommand(ApiKeyDto request)
        {
            this.request = request;
        }

        public class InsertApiKeyHandler : IRequestHandler<InsertApiKeyCommand, Response<ApiKeyDto>>
        {
            private readonly ILogger<InsertApiKeyHandler> _logger;
            private readonly IApiKeyRepository _repository;
            public InsertApiKeyHandler(ILogger<InsertApiKeyHandler> logger, IApiKeyRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<ApiKeyDto>> Handle(InsertApiKeyCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}