// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Quickcode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.IdentityModule.Domain.Entities;
using QuickCode.Quickcode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.ApiKey;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Features.ApiKey
{
    public class TouchApiKeyLastUsedCommand : IRequest<Response<int>>
    {
        public Guid ApiKeyId { get; set; }
        public TouchApiKeyLastUsedRequestDto UpdateRequest { get; set; }

        public TouchApiKeyLastUsedCommand(Guid apiKeyId, TouchApiKeyLastUsedRequestDto updateRequest)
        {
            this.ApiKeyId = apiKeyId;
            this.UpdateRequest = updateRequest;
        }

        public class TouchApiKeyLastUsedHandler : IRequestHandler<TouchApiKeyLastUsedCommand, Response<int>>
        {
            private readonly ILogger<TouchApiKeyLastUsedHandler> _logger;
            private readonly IApiKeyRepository _repository;
            public TouchApiKeyLastUsedHandler(ILogger<TouchApiKeyLastUsedHandler> logger, IApiKeyRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(TouchApiKeyLastUsedCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.TouchApiKeyLastUsedAsync(request.ApiKeyId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}