-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [Id],
    [TypeName],
    [IosComponentName],
    [IosType],
    [IconCode]
FROM [dbo].[ColumnTypes]
WHERE
    [Id] = @PRM_COLUMN_TYPE_ID
    AND [IsDeleted] = 0;