// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.QuickCodeModule.Domain.Entities;
using QuickCode.QuickCode.QuickCodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.Infrastructure.Data;
using QuickCode.QuickCode.Infrastructure.Data.Extensions;
using QuickCode.QuickCode.Infrastructure.Data.Helpers;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.ProjectRequest;
using QuickCode.QuickCode.QuickCodeModule.Application.Mappings;
using QuickCode.QuickCode.QuickCodeModule.Persistence.Sql;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Persistence.Repositories
{
    public partial class ProjectRequestRepository : BaseRepository, IProjectRequestRepository
    {
        public async Task<RepoResponse<int>> ConfirmAsync(Guid projectRequestId, ProjectRequestStatus projectRequestStatus, ConfirmRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProjectRequestCrudSqlBindings.OperationNames.Confirm, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectRequest.Command.Confirm);
                var parameters = new
                {
                    PROJECT_REQUEST_PROJECT_ID = updateRequest.ProjectRequestProjectId,
                    PRM_PROJECT_REQUEST_ID = projectRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> ResendAsync(Guid projectRequestId, ProjectRequestStatus projectRequestStatus, ResendRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProjectRequestCrudSqlBindings.OperationNames.Resend, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectRequest.Command.Resend);
                var parameters = new
                {
                    PROJECT_REQUEST_TOKEN_HASH = updateRequest.ProjectRequestTokenHash,
                    PROJECT_REQUEST_EXPIRES_AT = updateRequest.ProjectRequestExpiresAt,
                    PRM_PROJECT_REQUEST_ID = projectRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateEmailAsync(Guid projectRequestId, ProjectRequestStatus projectRequestStatus, UpdateEmailRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProjectRequestCrudSqlBindings.OperationNames.UpdateEmail, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectRequest.Command.UpdateEmail);
                var parameters = new
                {
                    PROJECT_REQUEST_EMAIL = updateRequest.ProjectRequestEmail,
                    PROJECT_REQUEST_TOKEN_HASH = updateRequest.ProjectRequestTokenHash,
                    PROJECT_REQUEST_EXPIRES_AT = updateRequest.ProjectRequestExpiresAt,
                    PRM_PROJECT_REQUEST_ID = projectRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateDocumentAsync(Guid projectRequestId, ProjectRequestStatus projectRequestStatus, UpdateDocumentRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProjectRequestCrudSqlBindings.OperationNames.UpdateDocument, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectRequest.Command.UpdateDocument);
                var parameters = new
                {
                    PROJECT_REQUEST_DOCUMENT_STORAGE_KEY = updateRequest.ProjectRequestDocumentStorageKey,
                    PROJECT_REQUEST_DOCUMENT_FILE_NAME = updateRequest.ProjectRequestDocumentFileName,
                    PRM_PROJECT_REQUEST_ID = projectRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> CancelAsync(Guid projectRequestId, ProjectRequestStatus projectRequestStatus, CancelRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProjectRequestCrudSqlBindings.OperationNames.Cancel, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectRequest.Command.Cancel);
                var parameters = new
                {
                    PRM_PROJECT_REQUEST_ID = projectRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> ExpireStaleAsync(ProjectRequestStatus projectRequestStatus, ExpireStaleRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProjectRequestCrudSqlBindings.OperationNames.ExpireStale, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectRequest.Command.ExpireStale);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}