// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.Infrastructure.Web.Controllers;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.GenerationRun;
using QuickCode.QuickCode.QuickCodeModule.Application.Services.GenerationRun;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Api.Controllers
{
    public partial class GenerationRunsController : QuickCodeBaseApiController
    {
        private readonly IGenerationRunService service;
        private readonly ILogger<GenerationRunsController> logger;
        private readonly IServiceProvider serviceProvider;
        public GenerationRunsController(IGenerationRunService service, IServiceProvider serviceProvider, ILogger<GenerationRunsController> logger)
        {
            this.service = service;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ListResult<GenerationRunDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size, [FromQuery] bool includeCount = false)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await service.ListAsync(page, size, includeCount);
            if (HandleResponseError(response, logger, "GenerationRun", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await service.TotalItemCountAsync();
            if (HandleResponseError(response, logger, "GenerationRun") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GenerationRunDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await service.GetItemAsync(id);
            if (HandleResponseError(response, logger, "GenerationRun", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(GenerationRunDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(GenerationRunDto model)
        {
            var response = await service.InsertAsync(model);
            if (HandleResponseError(response, logger, "GenerationRun") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, GenerationRunDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await service.UpdateAsync(id, model);
            if (HandleResponseError(response, logger, "GenerationRun", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await service.DeleteItemAsync(id);
            if (HandleResponseError(response, logger, "GenerationRun", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-generation-runs-first/{generationRunProjectId:guid}/{generationRunIsFinished:bool}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetGenerationRunsFirstResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetGenerationRunsFirstAsync(Guid generationRunProjectId, bool generationRunIsFinished)
        {
            var response = await service.GetGenerationRunsFirstAsync(generationRunProjectId, generationRunIsFinished);
            if (HandleResponseError(response, logger, "GenerationRun", $"GenerationRunProjectId: '{generationRunProjectId}', GenerationRunIsFinished: '{generationRunIsFinished}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-generation-runs-by-project-id/{generationRunsProjectId:guid}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetGenerationRunsByProjectIdResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetGenerationRunsByProjectIdAsync(Guid generationRunsProjectId)
        {
            var response = await service.GetGenerationRunsByProjectIdAsync(generationRunsProjectId);
            if (HandleResponseError(response, logger, "GenerationRun", $"GenerationRunsProjectId: '{generationRunsProjectId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-generation-runs-with-project-name/{projectsName}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetGenerationRunsWithProjectNameResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetGenerationRunsWithProjectNameAsync(string projectsName)
        {
            var response = await service.GetGenerationRunsWithProjectNameAsync(projectsName);
            if (HandleResponseError(response, logger, "GenerationRun", $"ProjectsName: '{projectsName}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-generation-runs-with-session-id/{generationRunsSessionId}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetGenerationRunsWithSessionIdResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetGenerationRunsWithSessionIdAsync(string generationRunsSessionId)
        {
            var response = await service.GetGenerationRunsWithSessionIdAsync(generationRunsSessionId);
            if (HandleResponseError(response, logger, "GenerationRun", $"GenerationRunsSessionId: '{generationRunsSessionId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("finish-all-unfinished-runs")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> FinishAllUnfinishedRunsAsync([FromBody] FinishAllUnfinishedRunsRequestDto updateRequest)
        {
            var response = await service.FinishAllUnfinishedRunsAsync(updateRequest);
            if (HandleResponseError(response, logger, "GenerationRun", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}