// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.Infrastructure.Web.Controllers;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.ProjectModule;
using QuickCode.Quickcode.QuickcodeModule.Application.Services.ProjectModule;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Api.Controllers
{
    public partial class ProjectModulesController : QuickCodeBaseApiController
    {
        private readonly IProjectModuleService service;
        private readonly ILogger<ProjectModulesController> logger;
        private readonly IServiceProvider serviceProvider;
        public ProjectModulesController(IProjectModuleService service, IServiceProvider serviceProvider, ILogger<ProjectModulesController> logger)
        {
            this.service = service;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ListResult<ProjectModuleDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size, [FromQuery] bool includeCount = false)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await service.ListAsync(page, size, includeCount);
            if (HandleResponseError(response, logger, "ProjectModule", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await service.TotalItemCountAsync();
            if (HandleResponseError(response, logger, "ProjectModule") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{projectId:guid}/{moduleName}/{moduleTemplateKey}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ProjectModuleDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(Guid projectId, string moduleName, string moduleTemplateKey)
        {
            var response = await service.GetItemAsync(projectId, moduleName, moduleTemplateKey);
            if (HandleResponseError(response, logger, "ProjectModule", $"ProjectId: '{projectId}', ModuleName: '{moduleName}', ModuleTemplateKey: '{moduleTemplateKey}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(ProjectModuleDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(ProjectModuleDto model)
        {
            var response = await service.InsertAsync(model);
            if (HandleResponseError(response, logger, "ProjectModule") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { projectId = response.Value.ProjectId, moduleName = response.Value.ModuleName, moduleTemplateKey = response.Value.ModuleTemplateKey }, response.Value);
        }

        [HttpPut("{projectId:guid}/{moduleName}/{moduleTemplateKey}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(Guid projectId, string moduleName, string moduleTemplateKey, ProjectModuleDto model)
        {
            if (!(model.ProjectId == projectId && model.ModuleName == moduleName && model.ModuleTemplateKey == moduleTemplateKey))
            {
                return BadRequest($"ProjectId: '{projectId}', ModuleName: '{moduleName}', ModuleTemplateKey: '{moduleTemplateKey}' must be equal to model.ProjectId: '{model.ProjectId}', model.ModuleName: '{model.ModuleName}', model.ModuleTemplateKey: '{model.ModuleTemplateKey}'");
            }

            var response = await service.UpdateAsync(projectId, moduleName, moduleTemplateKey, model);
            if (HandleResponseError(response, logger, "ProjectModule", $"ProjectId: '{projectId}', ModuleName: '{moduleName}', ModuleTemplateKey: '{moduleTemplateKey}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{projectId:guid}/{moduleName}/{moduleTemplateKey}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(Guid projectId, string moduleName, string moduleTemplateKey)
        {
            var response = await service.DeleteItemAsync(projectId, moduleName, moduleTemplateKey);
            if (HandleResponseError(response, logger, "ProjectModule", $"ProjectId: '{projectId}', ModuleName: '{moduleName}', ModuleTemplateKey: '{moduleTemplateKey}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-project-modules/{projectsKey}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetProjectModulesResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetProjectModulesAsync(string projectsKey)
        {
            var response = await service.GetProjectModulesAsync(projectsKey);
            if (HandleResponseError(response, logger, "ProjectModule", $"ProjectsKey: '{projectsKey}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-project-module-with-keys/{projectsKey}/{projectModulesModuleName}/{projectModulesModuleTemplateKey}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetProjectModuleWithKeysResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetProjectModuleWithKeysAsync(string projectsKey, string projectModulesModuleName, string projectModulesModuleTemplateKey)
        {
            var response = await service.GetProjectModuleWithKeysAsync(projectsKey, projectModulesModuleName, projectModulesModuleTemplateKey);
            if (HandleResponseError(response, logger, "ProjectModule", $"ProjectsKey: '{projectsKey}', ProjectModulesModuleName: '{projectModulesModuleName}', ProjectModulesModuleTemplateKey: '{projectModulesModuleTemplateKey}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-project-module-emails/{projectsKey}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetProjectModuleEmailsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetProjectModuleEmailsAsync(string projectsKey)
        {
            var response = await service.GetProjectModuleEmailsAsync(projectsKey);
            if (HandleResponseError(response, logger, "ProjectModule", $"ProjectsKey: '{projectsKey}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-project-module/{projectsKey}/{projectModulesModuleName}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetProjectModuleResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetProjectModuleAsync(string projectsKey, string projectModulesModuleName)
        {
            var response = await service.GetProjectModuleAsync(projectsKey, projectModulesModuleName);
            if (HandleResponseError(response, logger, "ProjectModule", $"ProjectsKey: '{projectsKey}', ProjectModulesModuleName: '{projectModulesModuleName}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}