// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Quickcode.Application.Contracts;
using QcEntity = global::QuickCode.Quickcode.QuickcodeModule.Domain.Entities;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.Infrastructure.Data;
using QuickCode.Quickcode.Infrastructure.Data.Extensions;
using QuickCode.Quickcode.Infrastructure.Data.Helpers;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.ProjectModule;
using QuickCode.Quickcode.QuickcodeModule.Application.Mappings;
using QuickCode.Quickcode.QuickcodeModule.Persistence.Sql;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Repositories
{
    public partial class ProjectModuleRepository : BaseRepository, IProjectModuleRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public ProjectModuleRepository(ILogger<ProjectModuleRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "ProjectModule")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<ProjectModuleDto>> InsertAsync(ProjectModuleDto value)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(ProjectModuleCrudSqlBindings.ParameterNamePrefix, value, ProjectModuleCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.ProjectModule>(sql, p);
                return new RepoResponse<ProjectModuleDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ProjectModuleDto value)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(ProjectModuleCrudSqlBindings.ParameterNamePrefix, value, ProjectModuleCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ProjectModuleDto value)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(ProjectModuleCrudSqlBindings.ParameterNamePrefix, value, ProjectModuleCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<ProjectModuleDto>> GetByPkAsync(Guid projectId, string moduleName, string moduleTemplateKey)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(ProjectModuleCrudSqlBindings.ProjectIdParameterName, projectId);
                p.Add(ProjectModuleCrudSqlBindings.ModuleNameParameterName, moduleName);
                p.Add(ProjectModuleCrudSqlBindings.ModuleTemplateKeyParameterName, moduleTemplateKey);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.ProjectModule>(sql, p);
                return row == null ? CreateNotFoundResponse<ProjectModuleDto>("Not found in ProjectModule") : new RepoResponse<ProjectModuleDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<ProjectModuleDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ProjectModuleDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.ProjectModule>(sql, p);
                return new RepoResponse<List<ProjectModuleDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}