// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.QuickCodeModule.Domain.Entities;
using QuickCode.QuickCode.QuickCodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.Infrastructure.Data;
using QuickCode.QuickCode.Infrastructure.Data.Extensions;
using QuickCode.QuickCode.Infrastructure.Data.Helpers;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.ProjectModule;
using QuickCode.QuickCode.QuickCodeModule.Application.Mappings;
using QuickCode.QuickCode.QuickCodeModule.Persistence.Sql;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Persistence.Repositories
{
    public partial class ProjectModuleRepository : BaseRepository, IProjectModuleRepository
    {
        public async Task<RepoResponse<List<GetProjectModulesResponseDto>>> GetProjectModulesAsync(string projectsKey)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.GetProjectModules, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Query.GetProjectModules);
                var parameters = new
                {
                    PRM_PROJECTS_KEY = projectsKey
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetProjectModulesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ProjectModule");
            });
        }

        public async Task<RepoResponse<GetProjectModuleWithKeysResponseDto>> GetProjectModuleWithKeysAsync(string projectsKey, string projectModulesModuleName, string projectModulesModuleTemplateKey)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.GetProjectModuleWithKeys, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Query.GetProjectModuleWithKeys);
                var parameters = new
                {
                    PRM_PROJECTS_KEY = projectsKey,
                    PRM_PROJECT_MODULES_MODULE_NAME = projectModulesModuleName,
                    PRM_PROJECT_MODULES_MODULE_TEMPLATE_KEY = projectModulesModuleTemplateKey
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetProjectModuleWithKeysResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ProjectModule");
            });
        }

        public async Task<RepoResponse<List<GetProjectModuleEmailsResponseDto>>> GetProjectModuleEmailsAsync(string projectsKey)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.GetProjectModuleEmails, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Query.GetProjectModuleEmails);
                var parameters = new
                {
                    PRM_PROJECTS_KEY = projectsKey
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetProjectModuleEmailsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ProjectModule");
            });
        }

        public async Task<RepoResponse<GetProjectModuleResponseDto>> GetProjectModuleAsync(string projectsKey, string projectModulesModuleName)
        {
            return await ExecuteWithExceptionHandling(ProjectModuleCrudSqlBindings.OperationNames.GetProjectModule, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectModule.Query.GetProjectModule);
                var parameters = new
                {
                    PRM_PROJECTS_KEY = projectsKey,
                    PRM_PROJECT_MODULES_MODULE_NAME = projectModulesModuleName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetProjectModuleResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ProjectModule");
            });
        }
    }
}