// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.QuickCode.Application.Contracts;

public interface IBaseRepository<T> where T : class
{
    Task<RepoResponse<T>> InsertAsync(T value);
    Task<RepoResponse<bool>> UpdateAsync(T value);
    Task<RepoResponse<bool>> DeleteAsync(T value);
    Task<RepoResponse<List<T>>> ListAsync(int? pageNumber = null, int? pageSize = null);
    Task<RepoResponse<int>> CountAsync();
}
