-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CASE WHEN EXISTS (
SELECT 1 
FROM [ApiMethodDefinitions] AMD 
WHERE AMD.[ModelName] = @PRM_ApiMethodDefinition_ModelName ) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END