// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.GenerationRun;
using GenerationRunEntity = QuickCode.Quickcode.QuickcodeModule.Domain.Entities.GenerationRun;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Application.Mappings
{
    public static class GenerationRunMappings
    {
        public static List<GenerationRunDto> ToDto(this IEnumerable<GenerationRunEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static GenerationRunDto ToDto(this GenerationRunEntity model)
        {
            return new GenerationRunDto
            {
                Id = model.Id,
                ProjectId = model.ProjectId,
                GenerationRunTypeId = model.GenerationRunTypeId,
                SessionId = model.SessionId,
                StartDate = model.StartDate,
                FinishDate = model.FinishDate,
                IsFinished = model.IsFinished
            };
        }

        public static GenerationRunEntity ToEntity(this GenerationRunDto model)
        {
            return new GenerationRunEntity
            {
                Id = model.Id,
                ProjectId = model.ProjectId,
                GenerationRunTypeId = model.GenerationRunTypeId,
                SessionId = model.SessionId,
                StartDate = model.StartDate,
                FinishDate = model.FinishDate,
                IsFinished = model.IsFinished
            };
        }
    }
}