// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Quickcode.IdentityModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Model
    {
        public static class Command
        {
            private const string _prefix = "IdentityModule.Model.Command";
            private const string _sqlScriptStem = "Model";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string DeleteModelsWithModuleName => ResourceKey($"{_sqlScriptStem}.DeleteModelsWithModuleName.g.sql");
        }
    }
}