IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.AUDIT_LOGS', N'U') AND name = N'IX_AUDIT_LOGS_ENTITY_NAME_REQUEST_MODULE')
BEGIN
    CREATE INDEX [IX_AUDIT_LOGS_ENTITY_NAME_REQUEST_MODULE] ON [dbo].[AUDIT_LOGS] ([ENTITY_NAME], [REQUEST_MODULE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.AUDIT_LOGS', N'U') AND name = N'IX_AUDIT_LOGS_ENTITY_NAME_TIMESTAMP')
BEGIN
    CREATE INDEX [IX_AUDIT_LOGS_ENTITY_NAME_TIMESTAMP] ON [dbo].[AUDIT_LOGS] ([ENTITY_NAME], [TIMESTAMP]);
END