-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[PAGE_CONFIGS]
SET
    [IS_ACTIVE] = @PRM_PAGE_CONFIG_IS_ACTIVE,
    [PAGE_CONFIG_DATA] = @PRM_PAGE_CONFIG_PAGE_CONFIG_DATA,
    [PAGE_TITLE] = @PRM_PAGE_CONFIG_PAGE_TITLE,
    [PAGE_TYPE] = @PRM_PAGE_CONFIG_PAGE_TYPE
WHERE
    [PAGE_KEY] = @PRM_PAGE_CONFIG_PAGE_KEY;