// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.QuickcodeModule.Domain.Entities;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.Infrastructure.Data;
using QuickCode.Quickcode.Infrastructure.Data.Extensions;
using QuickCode.Quickcode.Infrastructure.Data.Helpers;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.GenerationAction;
using QuickCode.Quickcode.QuickcodeModule.Application.Mappings;
using QuickCode.Quickcode.QuickcodeModule.Persistence.Sql;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Repositories
{
    public partial class GenerationActionRepository : BaseRepository, IGenerationActionRepository
    {
        public async Task<RepoResponse<List<GetIdBetweenResponseDto>>> GetIdBetweenAsync(int generationActionIdFrom, int generationActionIdTo)
        {
            return await ExecuteWithExceptionHandling(GenerationActionCrudSqlBindings.OperationNames.GetIdBetween, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationAction.Query.GetIdBetween);
                var parameters = new
                {
                    PRM_GENERATION_ACTION_ID_From = generationActionIdFrom,
                    PRM_GENERATION_ACTION_ID_To = generationActionIdTo
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetIdBetweenResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in GenerationAction");
            });
        }

        public async Task<RepoResponse<GetByActionIdResponseDto>> GetByActionIdAsync(int generationActionsId)
        {
            return await ExecuteWithExceptionHandling(GenerationActionCrudSqlBindings.OperationNames.GetByActionId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationAction.Query.GetByActionId);
                var parameters = new
                {
                    PRM_GENERATION_ACTIONS_ID = generationActionsId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByActionIdResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in GenerationAction");
            });
        }

        public async Task<RepoResponse<List<GetByRunIdResponseDto>>> GetByRunIdAsync(int generationActionsGenerationRunId)
        {
            return await ExecuteWithExceptionHandling(GenerationActionCrudSqlBindings.OperationNames.GetByRunId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationAction.Query.GetByRunId);
                var parameters = new
                {
                    PRM_GENERATION_ACTIONS_GENERATION_RUN_ID = generationActionsGenerationRunId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetByRunIdResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in GenerationAction");
            });
        }

        public async Task<RepoResponse<List<GetByProjectKeyResponseDto>>> GetByProjectKeyAsync(string projectsKey)
        {
            return await ExecuteWithExceptionHandling(GenerationActionCrudSqlBindings.OperationNames.GetByProjectKey, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationAction.Query.GetByProjectKey);
                var parameters = new
                {
                    PRM_PROJECTS_KEY = projectsKey
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetByProjectKeyResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in GenerationAction");
            });
        }
    }
}