// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Quickcode.Application.Contracts;
using QcEntity = global::QuickCode.Quickcode.IdentityModule.Domain.Entities;
using QuickCode.Quickcode.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.Infrastructure.Data;
using QuickCode.Quickcode.Infrastructure.Data.Extensions;
using QuickCode.Quickcode.Infrastructure.Data.Helpers;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.Module;
using QuickCode.Quickcode.IdentityModule.Application.Mappings;
using QuickCode.Quickcode.IdentityModule.Persistence.Sql;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Persistence.Repositories
{
    public partial class ModuleRepository : BaseRepository, IModuleRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public ModuleRepository(ILogger<ModuleRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "Module")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<ModuleDto>> InsertAsync(ModuleDto value)
        {
            return await ExecuteWithExceptionHandling(ModuleCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(ModuleCrudSqlBindings.ParameterNamePrefix, value, ModuleCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.Module>(sql, p);
                return new RepoResponse<ModuleDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ModuleDto value)
        {
            return await ExecuteWithExceptionHandling(ModuleCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(ModuleCrudSqlBindings.ParameterNamePrefix, value, ModuleCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ModuleDto value)
        {
            return await ExecuteWithExceptionHandling(ModuleCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(ModuleCrudSqlBindings.ParameterNamePrefix, value, ModuleCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<ModuleDto>> GetByPkAsync(string name)
        {
            return await ExecuteWithExceptionHandling(ModuleCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(ModuleCrudSqlBindings.NameParameterName, name);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.Module>(sql, p);
                return row == null ? CreateNotFoundResponse<ModuleDto>("Not found in Module") : new RepoResponse<ModuleDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<ModuleDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(ModuleCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ModuleDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.Module.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.Module>(sql, p);
                return new RepoResponse<List<ModuleDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(ModuleCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}