// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.IdentityModule.Domain.Entities;
using QuickCode.QuickCode.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.Infrastructure.Data;
using QuickCode.QuickCode.Infrastructure.Data.Extensions;
using QuickCode.QuickCode.Infrastructure.Data.Helpers;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.Module;
using QuickCode.QuickCode.IdentityModule.Application.Mappings;
using QuickCode.QuickCode.IdentityModule.Persistence.Sql;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Persistence.Repositories
{
    public partial class ModuleRepository : BaseRepository, IModuleRepository
    {
        public async Task<RepoResponse<bool>> ModuleNameIsExistsAsync(string moduleName)
        {
            return await ExecuteWithExceptionHandling(ModuleCrudSqlBindings.OperationNames.ModuleNameIsExists, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.ModuleNameIsExists);
                var parameters = new
                {
                    PRM_Module_Name = moduleName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in Module");
            });
        }
    }
}