// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.QuickCodeModule.Domain.Entities;
using QuickCode.QuickCode.QuickCodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.Infrastructure.Data;
using QuickCode.QuickCode.Infrastructure.Data.Extensions;
using QuickCode.QuickCode.Infrastructure.Data.Helpers;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.GenerationRun;
using QuickCode.QuickCode.QuickCodeModule.Application.Mappings;
using QuickCode.QuickCode.QuickCodeModule.Persistence.Sql;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Persistence.Repositories
{
    public partial class GenerationRunRepository : BaseRepository, IGenerationRunRepository
    {
        public async Task<RepoResponse<int>> FinishAllUnfinishedRunsAsync(FinishAllUnfinishedRunsRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(GenerationRunCrudSqlBindings.OperationNames.FinishAllUnfinishedRuns, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationRun.Command.FinishAllUnfinishedRuns);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}