// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.QuickcodeModule.Domain.Entities;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.Infrastructure.Data;
using QuickCode.Quickcode.Infrastructure.Data.Extensions;
using QuickCode.Quickcode.Infrastructure.Data.Helpers;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.GenerationRun;
using QuickCode.Quickcode.QuickcodeModule.Application.Mappings;
using QuickCode.Quickcode.QuickcodeModule.Persistence.Sql;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Repositories
{
    public partial class GenerationRunRepository : BaseRepository, IGenerationRunRepository
    {
        public async Task<RepoResponse<GetGenerationRunsFirstResponseDto>> GetGenerationRunsFirstAsync(Guid generationRunProjectId, bool? generationRunIsFinished)
        {
            return await ExecuteWithExceptionHandling(GenerationRunCrudSqlBindings.OperationNames.GetGenerationRunsFirst, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationRun.Query.GetGenerationRunsFirst);
                var parameters = new
                {
                    PRM_GENERATION_RUN_PROJECT_ID = generationRunProjectId,
                    PRM_GENERATION_RUN_IS_FINISHED = generationRunIsFinished
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetGenerationRunsFirstResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in GenerationRun");
            });
        }

        public async Task<RepoResponse<List<GetGenerationRunsByProjectIdResponseDto>>> GetGenerationRunsByProjectIdAsync(Guid generationRunsProjectId)
        {
            return await ExecuteWithExceptionHandling(GenerationRunCrudSqlBindings.OperationNames.GetGenerationRunsByProjectId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationRun.Query.GetGenerationRunsByProjectId);
                var parameters = new
                {
                    PRM_GENERATION_RUNS_PROJECT_ID = generationRunsProjectId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetGenerationRunsByProjectIdResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in GenerationRun");
            });
        }

        public async Task<RepoResponse<List<GetGenerationRunsWithProjectNameResponseDto>>> GetGenerationRunsWithProjectNameAsync(string projectsName)
        {
            return await ExecuteWithExceptionHandling(GenerationRunCrudSqlBindings.OperationNames.GetGenerationRunsWithProjectName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationRun.Query.GetGenerationRunsWithProjectName);
                var parameters = new
                {
                    PRM_PROJECTS_NAME = projectsName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetGenerationRunsWithProjectNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in GenerationRun");
            });
        }

        public async Task<RepoResponse<List<GetGenerationRunsWithSessionIdResponseDto>>> GetGenerationRunsWithSessionIdAsync(string generationRunsSessionId)
        {
            return await ExecuteWithExceptionHandling(GenerationRunCrudSqlBindings.OperationNames.GetGenerationRunsWithSessionId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GenerationRun.Query.GetGenerationRunsWithSessionId);
                var parameters = new
                {
                    PRM_GENERATION_RUNS_SESSION_ID = generationRunsSessionId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetGenerationRunsWithSessionIdResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in GenerationRun");
            });
        }
    }
}