-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [PROJECT_ID],
    [MODULE_NAME],
    [MODULE_TEMPLATE_KEY],
    [DBML],
    [DB_TYPE_KEY],
    [ARCHITECTURAL_PATTERN_KEY],
    [DESCRIPTION],
    [INITIAL_DATA],
    [CREATED_DATE],
    [UPDATED_DATE]
FROM [dbo].[PROJECT_MODULES]
ORDER BY
    [PROJECT_ID],
    [MODULE_NAME],
    [MODULE_TEMPLATE_KEY]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;