<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <NoWarn>CS8669;AD0001</NoWarn>
    <GenerateCode>True</GenerateCode>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f18176a5-a2ce-4478-beb2-55c957b39513</UserSecretsId>
    
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Yarp.ReverseProxy" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi.Readers" />
    <PackageReference Include="CloudFlare.Client" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AspNetCore.HealthChecks.UI" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" />
    <PackageReference Include="IdentityModel" />
  </ItemGroup>
  <ItemGroup>
    <None Condition="'$(ExcludeConfigFilesFromBuildOutput)'!='true'" Update="Dashboard\Dashboard.html">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\QuickCode.QuickCode.Infrastructure.Web\QuickCode.QuickCode.Infrastructure.Web.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\..\Shared\QuickCode.QuickCode.Application.Contracts\QuickCode.QuickCode.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
