// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.QuickCode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.IdentityModule.Domain.Entities;
using QuickCode.QuickCode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.AuditLog;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Features.AuditLog
{
    public class ListAuditLogQuery : IRequest<Response<ListResult<AuditLogDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }
        public bool IncludeCount { get; set; }

        public ListAuditLogQuery(int? pageNumber, int? pageSize, bool includeCount = false)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
            this.IncludeCount = includeCount;
        }

        public class ListAuditLogHandler : IRequestHandler<ListAuditLogQuery, Response<ListResult<AuditLogDto>>>
        {
            private readonly ILogger<ListAuditLogHandler> _logger;
            private readonly IAuditLogRepository _repository;
            public ListAuditLogHandler(ILogger<ListAuditLogHandler> logger, IAuditLogRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<ListResult<AuditLogDto>>> Handle(ListAuditLogQuery request, CancellationToken cancellationToken)
            {
                var listTask = _repository.ListAsync(request.PageNumber, request.PageSize);
                if (!request.IncludeCount)
                    return (await listTask).ToListResultResponse();
                var countTask = _repository.CountAsync();
                await Task.WhenAll(listTask, countTask);
                return (await listTask).ToListResultResponse(await countTask);
            }
        }
    }
}