// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.QuickCode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.IdentityModule.Domain.Entities;
using QuickCode.QuickCode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.AuditLog;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Features.AuditLog
{
    public class StatsYesterdayHttpRequestsQuery : IRequest<Response<StatsYesterdayHttpRequestsResponseDto>>
    {
        public StatsYesterdayHttpRequestsQuery()
        {
        }

        public class StatsYesterdayHttpRequestsHandler : IRequestHandler<StatsYesterdayHttpRequestsQuery, Response<StatsYesterdayHttpRequestsResponseDto>>
        {
            private readonly ILogger<StatsYesterdayHttpRequestsHandler> _logger;
            private readonly IAuditLogRepository _repository;
            public StatsYesterdayHttpRequestsHandler(ILogger<StatsYesterdayHttpRequestsHandler> logger, IAuditLogRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<StatsYesterdayHttpRequestsResponseDto>> Handle(StatsYesterdayHttpRequestsQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.StatsYesterdayHttpRequestsAsync();
                return returnValue.ToResponse();
            }
        }
    }
}