// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.QuickCode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.IdentityModule.Domain.Entities;
using QuickCode.QuickCode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.AuditLog;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Features.AuditLog
{
    public class StatsHttpStatusCodesQuery : IRequest<Response<List<StatsHttpStatusCodesResponseDto>>>
    {
        public StatsHttpStatusCodesQuery()
        {
        }

        public class StatsHttpStatusCodesHandler : IRequestHandler<StatsHttpStatusCodesQuery, Response<List<StatsHttpStatusCodesResponseDto>>>
        {
            private readonly ILogger<StatsHttpStatusCodesHandler> _logger;
            private readonly IAuditLogRepository _repository;
            public StatsHttpStatusCodesHandler(ILogger<StatsHttpStatusCodesHandler> logger, IAuditLogRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<StatsHttpStatusCodesResponseDto>>> Handle(StatsHttpStatusCodesQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.StatsHttpStatusCodesAsync();
                return returnValue.ToResponse();
            }
        }
    }
}