// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.QuickCode.Infrastructure.Integration.Models;
using Serilog;

namespace QuickCode.QuickCode.Gateway.Extensions;

public static class GatewayLoggingHelper
{
    private const int MaxResponseLogLength = 512;

    public static void LogDependencyError(string operation, Exception ex, string? path = null, string? method = null)
    {
        if (ex is QuickCodeSwaggerException swaggerEx)
        {
            Log.Error(ex,
                "Gateway {Operation} failed. Method={Method} Path={Path} HttpStatus={HttpStatus} Response={Response}",
                operation,
                method ?? "(unknown)",
                path ?? "(unknown)",
                swaggerEx.StatusCode,
                Truncate(swaggerEx.Response));
            return;
        }

        Log.Error(ex,
            "Gateway {Operation} failed. Method={Method} Path={Path}",
            operation,
            method ?? "(unknown)",
            path ?? "(unknown)");
    }

    public static void LogKafkaFailure(string operation, Exception ex, string? topic = null, string? key = null)
    {
        Log.Error(ex,
            "Gateway Kafka {Operation} failed. Topic={Topic} Key={Key}",
            operation,
            topic ?? "(unknown)",
            key ?? "(unknown)");
    }

    private static string Truncate(string? value)
    {
        if (string.IsNullOrEmpty(value))
            return "(empty)";

        return value.Length <= MaxResponseLogLength
            ? value
            : value[..MaxResponseLogLength] + "...";
    }
}
