// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.QuickcodeModule.Application.Services.ModuleTemplate;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.ModuleTemplate;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.Infrastructure.Web.Helpers;
using QuickCode.Quickcode.Application.Contracts;

namespace QuickCode.Quickcode.QuickcodeModule.Application.Tests.Services.ModuleTemplate
{
    public class InsertModuleTemplateCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IModuleTemplateRepository> _repositoryMock;
        private readonly Mock<ILogger<ModuleTemplateService>> _loggerMock;
        private readonly ModuleTemplateService _service;
        public InsertModuleTemplateCommandTests()
        {
            _repositoryMock = new Mock<IModuleTemplateRepository>();
            _loggerMock = new Mock<ILogger<ModuleTemplateService>>();
            _service = new ModuleTemplateService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ModuleTemplateDto>("tr");
            var fakeResponse = new RepoResponse<ModuleTemplateDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<ModuleTemplateDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<ModuleTemplateDto>()), Times.Once);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ModuleTemplateDto>("tr");
            var fakeResponse = new RepoResponse<ModuleTemplateDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<ModuleTemplateDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}