// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Application.Dtos.AuditLog
{
    public record StatsTopHttpServicesByModuleResponseDto
    {
        public string? RequestModule { get; init; }
        public string Action { get; init; }
        public string? RequestPath { get; init; }
        public int TotalRequests { get; init; }
    }
}