// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.QuickCodeModule.Application.Services.ProjectAnalysisDocument;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.ProjectAnalysisDocument;
using QuickCode.QuickCode.QuickCodeModule.Application.Interfaces.Repositories;
using QuickCode.QuickCode.Infrastructure.Web.Helpers;
using QuickCode.QuickCode.Application.Contracts;

namespace QuickCode.QuickCode.QuickCodeModule.Application.Tests.Services.ProjectAnalysisDocument
{
    public class ProjectAnalysisDocumentServiceDeleteTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IProjectAnalysisDocumentRepository> _repositoryMock;
        private readonly Mock<ILogger<ProjectAnalysisDocumentService>> _loggerMock;
        private readonly ProjectAnalysisDocumentService _service;
        public ProjectAnalysisDocumentServiceDeleteTests()
        {
            _repositoryMock = new Mock<IProjectAnalysisDocumentRepository>();
            _loggerMock = new Mock<ILogger<ProjectAnalysisDocumentService>>();
            _service = new ProjectAnalysisDocumentService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task DeleteItemAsync_Should_Return_Success_When_Item_Exists()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ProjectAnalysisDocumentDto>("tr");
            var fakeGetResponse = new RepoResponse<ProjectAnalysisDocumentDto>(fakeDto, "Success");
            var fakeDeleteResponse = new RepoResponse<bool>(true, "Success");
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            _repositoryMock.Setup(r => r.DeleteAsync(It.IsAny<ProjectAnalysisDocumentDto>())).ReturnsAsync(fakeDeleteResponse);
            // Act
            var result = await _service.DeleteItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.True(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.DeleteAsync(It.IsAny<ProjectAnalysisDocumentDto>()), Times.Once);
        }

        [Fact]
        public async Task DeleteItemAsync_Should_Return_NotFound_When_Item_Does_Not_Exist()
        {
            var fakeDto = TestDataGenerator.CreateFake<ProjectAnalysisDocumentDto>("tr");
            // Arrange
            var fakeGetResponse = new RepoResponse<ProjectAnalysisDocumentDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            // Act
            var result = await _service.DeleteItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.False(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.DeleteAsync(It.IsAny<ProjectAnalysisDocumentDto>()), Times.Never);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}