-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [PROJECT_REQUESTS] 
	SET [DOCUMENT_STORAGE_KEY] = @PROJECT_REQUEST_DOCUMENT_STORAGE_KEY, [DOCUMENT_FILE_NAME] = @PROJECT_REQUEST_DOCUMENT_FILE_NAME, [UPDATED_DATE] = GETDATE() 
WHERE [ID] = @PRM_PROJECT_REQUEST_ID 
	AND [STATUS] = 'Pending'