-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [PROJECT_REQUESTS] 
	SET [STATUS] = 'Expired', [UPDATED_DATE] = GETDATE() 
WHERE [STATUS] = 'Pending' 
	AND [EXPIRES_AT] < GETDATE()