// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Dtos.Model
{
    public record ModuleNameIsExistsResponseDto
    {
        public string Name { get; init; }
        public string ModuleName { get; init; }
        public string Description { get; init; }
    }
}