-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 RT.[Id], RT.[UserId], RT.[Token], RT.[ExpiryDate], RT.[CreatedDate], RT.[IsRevoked] 
FROM [RefreshTokens] RT 
WHERE RT.[IsDeleted] = 0 
	AND RT.[Token] = @PRM_RefreshToken_Token 
	AND RT.[IsRevoked] = 0 
	AND RT.[ExpiryDate] > GETDATE() 
ORDER BY RT.[Id] 