-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[GENERATION_STEPS]
SET
    [NAME] = @PRM_GENERATION_STEP_NAME,
    [WAITING_MESSAGE] = @PRM_GENERATION_STEP_WAITING_MESSAGE,
    [IN_PROGRESS_MESSAGE] = @PRM_GENERATION_STEP_IN_PROGRESS_MESSAGE,
    [COMPLETED_MESSAGE] = @PRM_GENERATION_STEP_COMPLETED_MESSAGE,
    [DESCRIPTION] = @PRM_GENERATION_STEP_DESCRIPTION,
    [ICON] = @PRM_GENERATION_STEP_ICON,
    [NEEDS] = @PRM_GENERATION_STEP_NEEDS
WHERE
    [ID] = @PRM_GENERATION_STEP_ID
    AND [IsDeleted] = 0;