// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using QuickCode.Quickcode.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using QuickCode.Quickcode.Portal.Models;

namespace QuickCode.Quickcode.Portal.Helpers;

public static class PortalNavigationHelper
{
    public static bool IsActivePath(string? requestPath, string? actionName)
    {
        if (string.IsNullOrWhiteSpace(actionName))
            return false;

        var path = NormalizePath(requestPath);
        var action = NormalizePath(actionName);

        return path.Equals(action, StringComparison.OrdinalIgnoreCase);
    }

    public static bool IsDashboard(string? requestPath)
    {
        var path = NormalizePath(requestPath);
        return path == "/"
               || path.Equals("/Home", StringComparison.OrdinalIgnoreCase)
               || path.Equals("/Home/Index", StringComparison.OrdinalIgnoreCase);
    }

    public static bool IsDashboardPage(HttpContext? httpContext)
    {
        if (httpContext == null)
            return false;

        var controller = httpContext.GetRouteValue("controller")?.ToString();
        var action = httpContext.GetRouteValue("action")?.ToString();
        if (IsHomeIndexRoute(controller, action))
            return true;

        return IsDashboard(httpContext.Request.Path.Value);
    }

    public static IReadOnlyList<PortalBreadcrumbItem> BuildBreadcrumb(
        string? requestPath,
        IReadOnlyList<PortalMenuDto> menuItems,
        string? pageTitleOverride = null)
    {
        if (IsDashboard(requestPath))
            return Array.Empty<PortalBreadcrumbItem>();

        var allMenus = menuItems as List<PortalMenuDto> ?? new List<PortalMenuDto>(menuItems);
        var normalizedPath = NormalizePath(requestPath);
        var items = new List<PortalBreadcrumbItem>
        {
            CreateLinkCrumb("Dashboard", "/", normalizedPath)
        };

        PortalMenuDto? match = null;
        foreach (var menu in allMenus)
        {
            if (IsActivePath(normalizedPath, menu.ActionName))
            {
                match = menu;
                break;
            }
        }

        if (match != null)
        {
            items.AddRange(GetSectionItems(match, allMenus, normalizedPath));
            items.Add(CreateMenuCrumb(match, normalizedPath, isActive: true));
            return items;
        }

        if (!string.IsNullOrWhiteSpace(pageTitleOverride))
        {
            items.Add(new PortalBreadcrumbItem
            {
                Text = pageTitleOverride.Trim(),
                IsActive = true
            });
            return items;
        }

        var fallbackTitle = GetFallbackTitle(normalizedPath);
        if (!string.IsNullOrWhiteSpace(fallbackTitle))
        {
            items.Add(new PortalBreadcrumbItem
            {
                Text = fallbackTitle,
                IsActive = true
            });
        }

        return items;
    }

    public static string FormatMenuItemTitle(PortalMenuDto item)
    {
        if (string.Equals(item.Name, "AuditLogs", StringComparison.OrdinalIgnoreCase))
        {
            return $"{item.ParentName.Replace("Module", "", StringComparison.OrdinalIgnoreCase)} {item.Text}"
                .AsSplitCapitalWithUnderline();
        }

        if (TryGetQueryMenuParts(item, out _, out var filterName) && !string.IsNullOrWhiteSpace(filterName))
            return filterName.SplitCamelCaseToString();

        return item.Text.SplitCamelCaseToString();
    }

    public static string FormatSectionTitle(string parentName)
    {
        if (string.IsNullOrWhiteSpace(parentName))
            return string.Empty;

        if (parentName.EndsWith("Queries", StringComparison.OrdinalIgnoreCase))
        {
            var withoutQueries = parentName[..^7];
            if (withoutQueries.EndsWith("Module", StringComparison.OrdinalIgnoreCase))
                return withoutQueries[..^6].SplitCamelCaseToString();
            return withoutQueries.SplitCamelCaseToString();
        }

        if (parentName.EndsWith("Module", StringComparison.OrdinalIgnoreCase))
            return parentName[..^6].SplitCamelCaseToString();

        return parentName.SplitCamelCaseToString();
    }

    /// <summary>
    /// Resolves table + filter from a Queries menu row (Key or ActionName).
    /// Key format: Queries_{Module}_{Table}_{Filter}; Action: /{Module}{Table}/Queries/{Filter}
    /// </summary>
    public static bool TryGetQueryMenuParts(
        PortalMenuDto item,
        out string tableName,
        out string filterName)
    {
        tableName = string.Empty;
        filterName = string.Empty;

        var parentName = item.ParentName.AsString().Trim();
        if (!parentName.EndsWith("Queries", StringComparison.OrdinalIgnoreCase) || parentName.Length <= 7)
            return false;

        var modulePrefix = parentName[..^7];
        var key = item.Key.AsString().Trim();
        if (key.StartsWith("Queries_", StringComparison.OrdinalIgnoreCase))
        {
            var rest = key["Queries_".Length..];
            var moduleWithSep = modulePrefix + "_";
            if (rest.StartsWith(moduleWithSep, StringComparison.OrdinalIgnoreCase)
                && rest.Length > moduleWithSep.Length)
            {
                var afterModule = rest[moduleWithSep.Length..];
                var separator = afterModule.IndexOf('_');
                if (separator > 0 && separator < afterModule.Length - 1)
                {
                    tableName = afterModule[..separator];
                    filterName = afterModule[(separator + 1)..];
                    return true;
                }
            }
        }

        var action = NormalizePath(item.ActionName);
        var segments = action.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length >= 3
            && segments[1].Equals("Queries", StringComparison.OrdinalIgnoreCase)
            && segments[0].StartsWith(modulePrefix, StringComparison.OrdinalIgnoreCase)
            && segments[0].Length > modulePrefix.Length)
        {
            tableName = segments[0][modulePrefix.Length..];
            filterName = segments[^1];
            return !string.IsNullOrWhiteSpace(tableName) && !string.IsNullOrWhiteSpace(filterName);
        }

        return false;
    }

    public static bool IsAuditLogsTable(string tableName) =>
        string.Equals(tableName, "AuditLogs", StringComparison.OrdinalIgnoreCase)
        || string.Equals(tableName, "AuditLog", StringComparison.OrdinalIgnoreCase);

    public static bool IsAuditLogsQuery(PortalMenuDto item) =>
        TryGetQueryMenuParts(item, out var tableName, out _) && IsAuditLogsTable(tableName);

    private static IEnumerable<PortalBreadcrumbItem> GetSectionItems(
        PortalMenuDto match,
        IReadOnlyList<PortalMenuDto> menuItems,
        string currentPath)
    {
        var parentName = match.ParentName.AsString().Trim();

        if (string.Equals(match.Name, "AuditLogs", StringComparison.OrdinalIgnoreCase))
        {
            var auditMenus = new List<PortalMenuDto>();
            foreach (var menu in menuItems)
            {
                if (string.Equals(menu.Name, "AuditLogs", StringComparison.OrdinalIgnoreCase))
                    auditMenus.Add(menu);
            }

            yield return CreateMenuGroupCrumb(
                "Audit Logs",
                auditMenus,
                currentPath);
            yield break;
        }

        if (parentName.EndsWith("Queries", StringComparison.OrdinalIgnoreCase))
        {
            var queryMenus = new List<PortalMenuDto>();
            foreach (var menu in menuItems)
            {
                if (menu.ParentName.AsString().Trim().EndsWith("Queries", StringComparison.OrdinalIgnoreCase)
                    && !IsAuditLogsQuery(menu))
                    queryMenus.Add(menu);
            }

            yield return CreateQueriesOverviewCrumb(queryMenus, currentPath);

            var queryPages = new List<PortalMenuDto>();
            foreach (var menu in menuItems)
            {
                if (menu.ParentName.AsString().Trim().Equals(parentName, StringComparison.OrdinalIgnoreCase)
                    && !IsAuditLogsQuery(menu))
                    queryPages.Add(menu);
            }

            yield return CreateQueryModuleCrumb(
                FormatSectionTitle(parentName),
                queryPages,
                currentPath);

            if (TryGetQueryMenuParts(match, out var tableName, out _)
                && !string.IsNullOrWhiteSpace(tableName))
            {
                var tablePages = new List<PortalMenuDto>();
                foreach (var menu in queryPages)
                {
                    if (TryGetQueryMenuParts(menu, out var menuTable, out _)
                        && menuTable.Equals(tableName, StringComparison.OrdinalIgnoreCase))
                    {
                        tablePages.Add(menu);
                    }
                }

                yield return CreateMenuGroupCrumb(
                    tableName.SplitCamelCaseToString(),
                    tablePages,
                    currentPath);
            }

            yield break;
        }

        if (parentName.EndsWith("Module", StringComparison.OrdinalIgnoreCase))
        {
            var moduleMenus = new List<PortalMenuDto>();
            foreach (var menu in menuItems)
            {
                if (menu.ParentName.AsString().Trim().EndsWith("Module")
                    && !menu.ParentName.AsString().Trim().EndsWith("Queries"))
                    moduleMenus.Add(menu);
            }

            yield return CreateModuleOverviewCrumb(moduleMenus, currentPath);

            var modulePages = new List<PortalMenuDto>();
            foreach (var menu in menuItems)
            {
                if (menu.ParentName.AsString().Trim().Equals(parentName, StringComparison.OrdinalIgnoreCase)
                    && !string.Equals(menu.Name, "AuditLogs", StringComparison.OrdinalIgnoreCase))
                {
                    modulePages.Add(menu);
                }
            }

            yield return CreateMenuGroupCrumb(
                FormatSectionTitle(parentName),
                modulePages,
                currentPath);
            yield break;
        }

        var managementMenus = new List<PortalMenuDto>();
        foreach (var menu in menuItems)
        {
            var menuParent = menu.ParentName.AsString().Trim();
            if (!menuParent.EndsWith("Module", StringComparison.OrdinalIgnoreCase)
                && !menuParent.EndsWith("Queries", StringComparison.OrdinalIgnoreCase))
            {
                managementMenus.Add(menu);
            }
        }

        yield return CreateManagementOverviewCrumb(managementMenus, currentPath);

        var groupPages = new List<PortalMenuDto>();
        foreach (var menu in menuItems)
        {
            if (menu.ParentName.AsString().Trim().Equals(parentName, StringComparison.OrdinalIgnoreCase))
                groupPages.Add(menu);
        }

        yield return CreateMenuGroupCrumb(
            FormatSectionTitle(parentName),
            groupPages,
            currentPath);
    }

    private static PortalBreadcrumbItem CreateLinkCrumb(
        string text,
        string url,
        string currentPath,
        bool isActive = false)
    {
        return new PortalBreadcrumbItem
        {
            Text = text,
            Url = url,
            IsActive = isActive || IsActivePath(currentPath, url)
        };
    }

    private static PortalBreadcrumbItem CreateMenuCrumb(
        PortalMenuDto menu,
        string currentPath,
        bool isActive = false)
    {
        return new PortalBreadcrumbItem
        {
            Text = FormatMenuItemTitle(menu),
            Url = menu.ActionName,
            IsActive = isActive,
            RelatedLinks = BuildMenuLinks(new[] { menu }, currentPath)
        };
    }

    private static PortalBreadcrumbItem CreateMenuGroupCrumb(
        string text,
        IReadOnlyList<PortalMenuDto> groupMenus,
        string currentPath)
    {
        var links = BuildMenuLinks(groupMenus, currentPath);
        return new PortalBreadcrumbItem
        {
            Text = text,
            Url = links.FirstOrDefault(i => !i.IsActive)?.Url ?? links.FirstOrDefault()?.Url,
            RelatedLinks = links
        };
    }

    private static PortalBreadcrumbItem CreateQueriesOverviewCrumb(
        IReadOnlyList<PortalMenuDto> queryMenus,
        string currentPath)
    {
        var moduleLinks = new List<PortalBreadcrumbLink>();
        foreach (var group in queryMenus.GroupBy(i => i.ParentName.AsString().Trim()))
        {
            PortalMenuDto? firstPage = null;
            foreach (var menu in group.OrderBy(i => FormatMenuItemTitle(i)))
            {
                if (string.IsNullOrWhiteSpace(menu.ActionName))
                    continue;

                firstPage = menu;
                break;
            }

            if (firstPage == null)
                continue;

            moduleLinks.Add(new PortalBreadcrumbLink(
                FormatSectionTitle(group.Key),
                firstPage.ActionName,
                group.Any(i => IsActivePath(currentPath, i.ActionName))));
        }

        moduleLinks.Sort((left, right) => string.Compare(left.Text, right.Text, StringComparison.OrdinalIgnoreCase));

        return new PortalBreadcrumbItem
        {
            Text = "Live Reports",
            Url = moduleLinks.FirstOrDefault()?.Url,
            RelatedLinks = moduleLinks
        };
    }

    private static PortalBreadcrumbItem CreateQueryModuleCrumb(
        string moduleLabel,
        IReadOnlyList<PortalMenuDto> moduleQueryPages,
        string currentPath)
    {
        var tableLinks = new List<PortalBreadcrumbLink>();
        foreach (var group in moduleQueryPages
                     .Select(menu =>
                     {
                         TryGetQueryMenuParts(menu, out var table, out _);
                         return (Menu: menu, Table: table);
                     })
                     .Where(x => !string.IsNullOrWhiteSpace(x.Table))
                     .GroupBy(x => x.Table, StringComparer.OrdinalIgnoreCase))
        {
            PortalMenuDto? firstPage = null;
            foreach (var entry in group.OrderBy(x => FormatMenuItemTitle(x.Menu)))
            {
                if (string.IsNullOrWhiteSpace(entry.Menu.ActionName))
                    continue;

                firstPage = entry.Menu;
                break;
            }

            if (firstPage == null)
                continue;

            tableLinks.Add(new PortalBreadcrumbLink(
                group.Key.SplitCamelCaseToString(),
                firstPage.ActionName,
                group.Any(x => IsActivePath(currentPath, x.Menu.ActionName))));
        }

        tableLinks.Sort((left, right) => string.Compare(left.Text, right.Text, StringComparison.OrdinalIgnoreCase));

        return new PortalBreadcrumbItem
        {
            Text = moduleLabel,
            Url = tableLinks.FirstOrDefault()?.Url
                  ?? moduleQueryPages.FirstOrDefault(i => !string.IsNullOrWhiteSpace(i.ActionName))?.ActionName,
            RelatedLinks = tableLinks
        };
    }

    private static PortalBreadcrumbItem CreateModuleOverviewCrumb(
        IReadOnlyList<PortalMenuDto> moduleMenus,
        string currentPath)
    {
        var moduleLinks = new List<PortalBreadcrumbLink>();
        foreach (var group in moduleMenus
                     .Where(i => !string.Equals(i.Name, "AuditLogs", StringComparison.OrdinalIgnoreCase))
                     .GroupBy(i => i.ParentName.AsString().Trim()))
        {
            PortalMenuDto? firstPage = null;
            foreach (var menu in group.OrderBy(i => FormatMenuItemTitle(i)))
            {
                if (string.IsNullOrWhiteSpace(menu.ActionName))
                    continue;

                firstPage = menu;
                break;
            }

            if (firstPage == null)
                continue;

            moduleLinks.Add(new PortalBreadcrumbLink(
                FormatSectionTitle(group.Key),
                firstPage.ActionName,
                group.Any(i => IsActivePath(currentPath, i.ActionName))));
        }

        moduleLinks.Sort((left, right) => string.Compare(left.Text, right.Text, StringComparison.OrdinalIgnoreCase));

        return new PortalBreadcrumbItem
        {
            Text = "Modules",
            Url = moduleLinks.FirstOrDefault()?.Url,
            RelatedLinks = moduleLinks
        };
    }

    private static PortalBreadcrumbItem CreateManagementOverviewCrumb(
        IReadOnlyList<PortalMenuDto> managementMenus,
        string currentPath)
    {
        var groupLinks = new List<PortalBreadcrumbLink>();
        foreach (var group in managementMenus.GroupBy(i => i.ParentName.AsString().Trim()))
        {
            PortalMenuDto? firstPage = null;
            foreach (var menu in group.OrderBy(i => FormatMenuItemTitle(i)))
            {
                if (string.IsNullOrWhiteSpace(menu.ActionName))
                    continue;

                firstPage = menu;
                break;
            }

            if (firstPage == null)
                continue;

            groupLinks.Add(new PortalBreadcrumbLink(
                FormatSectionTitle(group.Key),
                firstPage.ActionName,
                group.Any(i => IsActivePath(currentPath, i.ActionName))));
        }

        groupLinks.Sort((left, right) => string.Compare(left.Text, right.Text, StringComparison.OrdinalIgnoreCase));

        return new PortalBreadcrumbItem
        {
            Text = "Management",
            Url = groupLinks.FirstOrDefault()?.Url,
            RelatedLinks = groupLinks
        };
    }

    private static IReadOnlyList<PortalBreadcrumbLink> BuildMenuLinks(
        IEnumerable<PortalMenuDto> menus,
        string currentPath)
    {
        var links = new List<PortalBreadcrumbLink>();
        foreach (var menu in menus)
        {
            if (string.IsNullOrWhiteSpace(menu.ActionName))
                continue;

            links.Add(new PortalBreadcrumbLink(
                FormatMenuItemTitle(menu),
                menu.ActionName,
                IsActivePath(currentPath, menu.ActionName)));
        }

        links.Sort((left, right) => string.Compare(left.Text, right.Text, StringComparison.OrdinalIgnoreCase));
        return links;
    }

    private static string? GetFallbackTitle(string normalizedPath)
    {
        if (string.IsNullOrWhiteSpace(normalizedPath) || normalizedPath == "/")
            return null;

        var segments = normalizedPath.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length == 0)
            return null;

        var lastSegment = segments[^1];
        if (lastSegment.Equals("List", StringComparison.OrdinalIgnoreCase) && segments.Length > 1)
            lastSegment = segments[^2];

        return lastSegment.SplitCamelCaseToString();
    }

    private static bool IsHomeIndexRoute(string? controller, string? action)
    {
        if (!string.Equals(controller, "Home", StringComparison.OrdinalIgnoreCase))
            return false;

        return string.IsNullOrWhiteSpace(action)
               || string.Equals(action, "Index", StringComparison.OrdinalIgnoreCase);
    }

    private static string NormalizePath(string? path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return "/";

        var normalized = path.Split('?', '#')[0].Trim();
        if (!normalized.StartsWith('/'))
            normalized = "/" + normalized;

        return normalized.TrimEnd('/');
    }
}
