// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Quickcode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.IdentityModule.Domain.Entities;
using QuickCode.Quickcode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.PortalPageDefinition;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Features.PortalPageDefinition
{
    public class ListPortalPageDefinitionQuery : IRequest<Response<ListResult<PortalPageDefinitionDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }
        public bool IncludeCount { get; set; }

        public ListPortalPageDefinitionQuery(int? pageNumber, int? pageSize, bool includeCount = false)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
            this.IncludeCount = includeCount;
        }

        public class ListPortalPageDefinitionHandler : IRequestHandler<ListPortalPageDefinitionQuery, Response<ListResult<PortalPageDefinitionDto>>>
        {
            private readonly ILogger<ListPortalPageDefinitionHandler> _logger;
            private readonly IPortalPageDefinitionRepository _repository;
            public ListPortalPageDefinitionHandler(ILogger<ListPortalPageDefinitionHandler> logger, IPortalPageDefinitionRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<ListResult<PortalPageDefinitionDto>>> Handle(ListPortalPageDefinitionQuery request, CancellationToken cancellationToken)
            {
                var listTask = _repository.ListAsync(request.PageNumber, request.PageSize);
                if (!request.IncludeCount)
                    return (await listTask).ToListResultResponse();
                var countTask = _repository.CountAsync();
                await Task.WhenAll(listTask, countTask);
                return (await listTask).ToListResultResponse(await countTask);
            }
        }
    }
}