-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
DELETE FROM [dbo].[Models]
WHERE
    [Name] = @PRM_MODEL_NAME AND
    [ModuleName] = @PRM_MODEL_MODULE_NAME;