// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.QuickCodeModule.Domain.Entities;
using QuickCode.QuickCode.QuickCodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.Infrastructure.Data;
using QuickCode.QuickCode.Infrastructure.Data.Extensions;
using QuickCode.QuickCode.Infrastructure.Data.Helpers;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.ModuleTemplate;
using QuickCode.QuickCode.QuickCodeModule.Application.Mappings;
using QuickCode.QuickCode.QuickCodeModule.Persistence.Sql;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Persistence.Repositories
{
    public partial class ModuleTemplateRepository : BaseRepository, IModuleTemplateRepository
    {
        public async Task<RepoResponse<GetByNameResponseDto>> GetByNameAsync(string moduleTemplateName)
        {
            return await ExecuteWithExceptionHandling(ModuleTemplateCrudSqlBindings.OperationNames.GetByName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ModuleTemplate.Query.GetByName);
                var parameters = new
                {
                    PRM_MODULE_TEMPLATE_NAME = moduleTemplateName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByNameResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ModuleTemplate");
            });
        }

        public async Task<RepoResponse<List<GetByIsWebProjectResponseDto>>> GetByIsWebProjectAsync(bool moduleTemplateIsWebProject)
        {
            return await ExecuteWithExceptionHandling(ModuleTemplateCrudSqlBindings.OperationNames.GetByIsWebProject, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ModuleTemplate.Query.GetByIsWebProject);
                var parameters = new
                {
                    PRM_MODULE_TEMPLATE_IS_WEB_PROJECT = moduleTemplateIsWebProject
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetByIsWebProjectResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ModuleTemplate");
            });
        }
    }
}