// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.QuickcodeModule.Domain.Entities;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.GenerationAction;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Application.Services.GenerationAction
{
    public partial class GenerationActionService : IGenerationActionService
    {
        private readonly ILogger<GenerationActionService> _logger;
        private readonly IGenerationActionRepository _repository;
        public GenerationActionService(ILogger<GenerationActionService> logger, IGenerationActionRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<GenerationActionDto>> InsertAsync(GenerationActionDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(GenerationActionDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, GenerationActionDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<ListResult<GenerationActionDto>>> ListAsync(int? pageNumber, int? pageSize, bool includeCount = false)
        {
            var listTask = _repository.ListAsync(pageNumber, pageSize);
            if (!includeCount)
                return (await listTask).ToListResultResponse();
            var countTask = _repository.CountAsync();
            await Task.WhenAll(listTask, countTask);
            return (await listTask).ToListResultResponse(await countTask);
        }

        public async Task<Response<GenerationActionDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetIdBetweenResponseDto>>> GetIdBetweenAsync(int generationActionIdFrom, int generationActionIdTo)
        {
            var returnValue = await _repository.GetIdBetweenAsync(generationActionIdFrom, generationActionIdTo);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetByActionIdResponseDto>> GetByActionIdAsync(int generationActionsId)
        {
            var returnValue = await _repository.GetByActionIdAsync(generationActionsId);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByRunIdResponseDto>>> GetByRunIdAsync(int generationActionsGenerationRunId)
        {
            var returnValue = await _repository.GetByRunIdAsync(generationActionsGenerationRunId);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByProjectKeyResponseDto>>> GetByProjectKeyAsync(string projectsKey)
        {
            var returnValue = await _repository.GetByProjectKeyAsync(projectsKey);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UpdateActionStartedAsync(string projectsKey, string generationStepsName, int generationActionsGenerationStepId, string generationActionsStepParameters, int generationActionsGenerationRunId, UpdateActionStartedRequestDto updateRequest)
        {
            var returnValue = await _repository.UpdateActionStartedAsync(projectsKey, generationStepsName, generationActionsGenerationStepId, generationActionsStepParameters, generationActionsGenerationRunId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UpdateActionCompletedAsync(string projectsKey, string generationStepsName, int generationActionsGenerationStepId, string generationActionsStepParameters, int generationActionsGenerationRunId, UpdateActionCompletedRequestDto updateRequest)
        {
            var returnValue = await _repository.UpdateActionCompletedAsync(projectsKey, generationStepsName, generationActionsGenerationStepId, generationActionsStepParameters, generationActionsGenerationRunId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> CompleteAllIncompleteActionsAsync(CompleteAllIncompleteActionsRequestDto updateRequest)
        {
            var returnValue = await _repository.CompleteAllIncompleteActionsAsync(updateRequest);
            return returnValue.ToResponse();
        }
    }
}