-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 P.[ID], P.[KEY], P.[NAME], P.[EMAIL], P.[GENERATION_STATUS_ID], P.[SECRET_CODE], P.[DESCRIPTION], P.[IS_ACTIVE], P.[CREATED_DATE], P.[UPDATED_DATE], PR.[ID] AS REQUEST_ID,
	PR.[STATUS] AS REQUEST_STATUS,
	PR.[EMAIL] AS REQUEST_EMAIL 
FROM [PROJECTS] P 
	INNER JOIN [PROJECT_REQUESTS] PR 
			ON PR.[PROJECT_ID] = P.[ID] 
WHERE PR.[ID] = @PRM_PROJECT_REQUESTS_ID 
ORDER BY P.[ID], PR.[ID] 