// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Project
    {
        public static class Query
        {
            private const string _prefix = "QuickcodeModule.Project.Query";
            private const string _sqlScriptStem = "Project";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetProject => ResourceKey($"{_sqlScriptStem}.GetProject.g.sql");
            public static string GetProjectByKey => ResourceKey($"{_sqlScriptStem}.GetProjectByKey.g.sql");
            public static string GetProjectIncludeInactive => ResourceKey($"{_sqlScriptStem}.GetProjectIncludeInactive.g.sql");
            public static string CheckProjectName => ResourceKey($"{_sqlScriptStem}.CheckProjectName.g.sql");
            public static string CheckSecretCode => ResourceKey($"{_sqlScriptStem}.CheckSecretCode.g.sql");
            public static string CountSecretCode => ResourceKey($"{_sqlScriptStem}.CountSecretCode.g.sql");
            public static string GetProjectByRequest => ResourceKey($"{_sqlScriptStem}.GetProjectByRequest.g.sql");
        }
    }
}