// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.GenerationStatus;

namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Repositories;
internal static class GenerationStatusCrudSqlBindings
{
    public const string StoreTableName = "GENERATION_STATUSES";
    public const string ParameterNamePrefix = "GENERATION_STATUS";
    public const string IdParameterName = "PRM_GENERATION_STATUS_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByName = "GetByName";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("ID", nameof(GenerationStatusDto.Id)),
        ("DESCRIPTION", nameof(GenerationStatusDto.Description)),
        ("EXECUTION_DESCRIPTION", nameof(GenerationStatusDto.ExecutionDescription)),
        ("ICON", nameof(GenerationStatusDto.Icon)),
        ("NAME", nameof(GenerationStatusDto.Name))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("DESCRIPTION", nameof(GenerationStatusDto.Description)),
        ("EXECUTION_DESCRIPTION", nameof(GenerationStatusDto.ExecutionDescription)),
        ("ICON", nameof(GenerationStatusDto.Icon)),
        ("NAME", nameof(GenerationStatusDto.Name)),
        ("ID", nameof(GenerationStatusDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(GenerationStatusDto.Id))
    };
}