// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Razor.TagHelpers;
using QuickCode.QuickCode.Portal.Controllers;
using QuickCode.QuickCode.Portal.Helpers;

namespace QuickCode.QuickCode.Portal.TagHelpers
{
    [HtmlTargetElement(Attributes = nameof(IsPageAvailable))]
    public class IsPageAvailableTagHelper : TagHelper
    {

        public bool IsPageAvailable { get; set; } = false;
        private List<PropertyInfo> viewAuthorizationProperties { get; set; }
        public IPortalPagePermissionManager portalPagePermissionManager { get; set; }

        [ViewContext]
        [HtmlAttributeNotBound]
        public ViewContext ViewContext { get; set; } = default!;

        public IsPageAvailableTagHelper(IPortalPagePermissionManager portalPagePermissionManager)
        {
            this.portalPagePermissionManager = portalPagePermissionManager;
            this.viewAuthorizationProperties = typeof(ViewPermission).GetProperties().ToList<PropertyInfo>();
        }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            var operationKeyRemove = "Item";
            var isPermissionManagerPage = false;
            var areaName = ViewContext.RouteData.Values["Area"].AsString();
            var controllerName = ViewContext.RouteData.Values["Controller"].AsString();
            var actionName = ViewContext.RouteData.Values["Action"].AsString();
            if (controllerName.Equals("ApiKeyGrands", StringComparison.OrdinalIgnoreCase))
                controllerName = "ApiKeys";
            var operationName = actionName.EndsWith(operationKeyRemove)
                ? actionName.Substring(0, actionName.IndexOf(operationKeyRemove, StringComparison.Ordinal))
                : actionName;
            if (operationName.IsIn("GetModulePermissions", "GetGroupPermissions", "GetKafkaEvents"))
            {
                operationName = "List";
                isPermissionManagerPage = true;
            }
            else if (!viewAuthorizationProperties.Any(i => i.Name == operationName))
            {
                // Live Report Query* actions (and other custom actions) use the List grant.
                // GetPagePermission resolves Query* to Module+Table+FilterName definition key.
                operationName = "List";
            }

            if (viewAuthorizationProperties.Any(i => i.Name == operationName))
            {
                var result = await portalPagePermissionManager.GetPagePermission($"{areaName}{controllerName}", actionName);

                var actionIsAvailable = result.GetType().GetProperty(operationName)!.GetValue(result).AsBoolean();
                IsPageAvailable = context.AllAttributes[nameof(IsPageAvailable)].Value.AsString().AsBoolean();
                bool isAuthorized;

                if (IsPageAvailable)
                {
                    isAuthorized = actionIsAvailable;
                }
                else
                {
                    isAuthorized = actionIsAvailable == IsPageAvailable;
                }

                if (isPermissionManagerPage
                    && !(result.Insert && result.Delete && result.Update))
                {
                    isAuthorized = false;
                }

                if (!isAuthorized)
                {
                    output.SuppressOutput();
                }

            }

        }

    }
}