// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.QuickCode.IdentityModule.Application.Dtos.AspNetUserClaim;

namespace QuickCode.QuickCode.IdentityModule.Persistence.Repositories;
internal static class AspNetUserClaimCrudSqlBindings
{
    public const string StoreTableName = "AspNetUserClaims";
    public const string ParameterNamePrefix = "AspNetUserClaim";
    public const string IdParameterName = "PRM_ASP_NET_USER_CLAIM_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("UserId", nameof(AspNetUserClaimDto.UserId)),
        ("ClaimType", nameof(AspNetUserClaimDto.ClaimType)),
        ("ClaimValue", nameof(AspNetUserClaimDto.ClaimValue))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("UserId", nameof(AspNetUserClaimDto.UserId)),
        ("ClaimType", nameof(AspNetUserClaimDto.ClaimType)),
        ("ClaimValue", nameof(AspNetUserClaimDto.ClaimValue)),
        ("Id", nameof(AspNetUserClaimDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("Id", nameof(AspNetUserClaimDto.Id))
    };
}