-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[PROJECT_PROMPTS]
SET [IsDeleted] = 1, [DeletedOnUtc] = SYSUTCDATETIME()
WHERE
    [ID] = @PRM_PROJECT_PROMPT_ID AND
    [AI_TYPE] = @PRM_PROJECT_PROMPT_AI_TYPE
    AND [IsDeleted] = 0;