// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class ProjectModuleRevision
    {
        public static class Query
        {
            private const string _prefix = "QuickcodeModule.ProjectModuleRevision.Query";
            private const string _sqlScriptStem = "ProjectModuleRevision";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetRevision => ResourceKey($"{_sqlScriptStem}.GetRevision.g.sql");
            public static string GetByModule => ResourceKey($"{_sqlScriptStem}.GetByModule.g.sql");
            public static string GetRevisionDbml => ResourceKey($"{_sqlScriptStem}.GetRevisionDbml.g.sql");
            public static string GetByProject => ResourceKey($"{_sqlScriptStem}.GetByProject.g.sql");
            public static string GetByAnalysis => ResourceKey($"{_sqlScriptStem}.GetByAnalysis.g.sql");
        }
    }
}