-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT R.[ID], R.[MODULE_NAME], R.[MODULE_TEMPLATE_KEY], R.[REVISION], R.[SOURCE], R.[ANALYSIS_ID], R.[CREATED_DATE], P.[KEY] AS PROJECT_KEY 
FROM [PROJECT_MODULE_REVISIONS] R 
	INNER JOIN [PROJECTS] P 
			ON R.[PROJECT_ID] = P.[ID] 
WHERE R.[IsDeleted] = 0 
	AND P.[KEY] = @PRM_PROJECTS_KEY 
	AND R.[MODULE_NAME] = @PRM_PROJECT_MODULE_REVISIONS_MODULE_NAME 
	AND P.[IS_ACTIVE] = 1 
ORDER BY R.[REVISION] DESC 