IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_MODULE_REVISIONS', N'U') AND name = N'IX_PROJECT_MODULE_REVISIONS_ANALYSIS_ID')
BEGIN
    CREATE INDEX [IX_PROJECT_MODULE_REVISIONS_ANALYSIS_ID] ON [dbo].[PROJECT_MODULE_REVISIONS] ([ANALYSIS_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_MODULE_REVISIONS', N'U') AND name = N'IX_PROJECT_MODULE_REVISIONS_MODULE_NAME')
BEGIN
    CREATE INDEX [IX_PROJECT_MODULE_REVISIONS_MODULE_NAME] ON [dbo].[PROJECT_MODULE_REVISIONS] ([MODULE_NAME]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_MODULE_REVISIONS', N'U') AND name = N'IX_PROJECT_MODULE_REVISIONS_PROJECT_ID')
BEGIN
    CREATE INDEX [IX_PROJECT_MODULE_REVISIONS_PROJECT_ID] ON [dbo].[PROJECT_MODULE_REVISIONS] ([PROJECT_ID]);
END