IF OBJECT_ID(N'dbo.ARCHITECTURAL_PATTERNS', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ARCHITECTURAL_PATTERNS] (
        [KEY] nvarchar(250) NOT NULL,
        [NAME] nvarchar(250) NOT NULL,
        [DESCRIPTION] nvarchar(max) NOT NULL,
        [ICON_URL] nvarchar(500) NOT NULL,
        CONSTRAINT [PK_ARCHITECTURAL_PATTERNS] PRIMARY KEY ([KEY])
    );
END;