IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_SCHEMA_SNAPSHOTS', N'U') AND name = N'IX_PROJECT_SCHEMA_SNAPSHOTS_PROJECT_ID')
BEGIN
    CREATE INDEX [IX_PROJECT_SCHEMA_SNAPSHOTS_PROJECT_ID] ON [dbo].[PROJECT_SCHEMA_SNAPSHOTS] ([PROJECT_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_SCHEMA_SNAPSHOTS', N'U') AND name = N'IX_PROJECT_SCHEMA_SNAPSHOTS_TRIGGER')
BEGIN
    CREATE INDEX [IX_PROJECT_SCHEMA_SNAPSHOTS_TRIGGER] ON [dbo].[PROJECT_SCHEMA_SNAPSHOTS] ([TRIGGER]);
END