IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_GENERATION_RUNS_PROJECTS_PROJECT_ID' AND parent_object_id = OBJECT_ID(N'dbo.GENERATION_RUNS'))
BEGIN
    ALTER TABLE [dbo].[GENERATION_RUNS] ADD CONSTRAINT [FK_GENERATION_RUNS_PROJECTS_PROJECT_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_GENERATION_RUNS_GENERATION_RUN_TYPES_GENERATION_RUN_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.GENERATION_RUNS'))
BEGIN
    ALTER TABLE [dbo].[GENERATION_RUNS] ADD CONSTRAINT [FK_GENERATION_RUNS_GENERATION_RUN_TYPES_GENERATION_RUN_TYPE_ID] FOREIGN KEY ([GENERATION_RUN_TYPE_ID]) REFERENCES [dbo].[GENERATION_RUN_TYPES] ([ID]);
END