IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECTS', N'U') AND name = N'IX_PROJECTS_GENERATION_STATUS_ID')
BEGIN
    CREATE INDEX [IX_PROJECTS_GENERATION_STATUS_ID] ON [dbo].[PROJECTS] ([GENERATION_STATUS_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECTS', N'U') AND name = N'IX_PROJECTS_KEY_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_PROJECTS_KEY_IS_ACTIVE] ON [dbo].[PROJECTS] ([KEY], [IS_ACTIVE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECTS', N'U') AND name = N'IX_PROJECTS_KEY_SECRET_CODE')
BEGIN
    CREATE INDEX [IX_PROJECTS_KEY_SECRET_CODE] ON [dbo].[PROJECTS] ([KEY], [SECRET_CODE]);
END