IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_LOGS', N'U') AND name = N'IX_GENERATION_LOGS_GENERATION_STATUS_ID')
BEGIN
    CREATE INDEX [IX_GENERATION_LOGS_GENERATION_STATUS_ID] ON [dbo].[GENERATION_LOGS] ([GENERATION_STATUS_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_LOGS', N'U') AND name = N'IX_GENERATION_LOGS_PROJECT_ID_GENERATION_STATUS_ID')
BEGIN
    CREATE INDEX [IX_GENERATION_LOGS_PROJECT_ID_GENERATION_STATUS_ID] ON [dbo].[GENERATION_LOGS] ([PROJECT_ID], [GENERATION_STATUS_ID]);
END