IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARCHITECTURAL_PATTERNS', N'U') AND name = N'IX_ARCHITECTURAL_PATTERNS_NAME')
BEGIN
    CREATE INDEX [IX_ARCHITECTURAL_PATTERNS_NAME] ON [dbo].[ARCHITECTURAL_PATTERNS] ([NAME]);
END