IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_MODULE_PROMPTS', N'U') AND name = N'IX_PROJECT_MODULE_PROMPTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_PROJECT_MODULE_PROMPTS_IsDeleted] ON [dbo].[PROJECT_MODULE_PROMPTS] ([IsDeleted]);
END