IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_MODULE_REVISIONS', N'U') AND name = N'IX_PROJECT_MODULE_REVISIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_PROJECT_MODULE_REVISIONS_IsDeleted] ON [dbo].[PROJECT_MODULE_REVISIONS] ([IsDeleted]);
END