IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_REQUESTS', N'U') AND name = N'IX_PROJECT_REQUESTS_PROJECT_ID')
BEGIN
    CREATE INDEX [IX_PROJECT_REQUESTS_PROJECT_ID] ON [dbo].[PROJECT_REQUESTS] ([PROJECT_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_REQUESTS', N'U') AND name = N'IX_PROJECT_REQUESTS_PROJECT_NAME_STATUS_EXPIRES_AT')
BEGIN
    CREATE INDEX [IX_PROJECT_REQUESTS_PROJECT_NAME_STATUS_EXPIRES_AT] ON [dbo].[PROJECT_REQUESTS] ([PROJECT_NAME], [STATUS], [EXPIRES_AT]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_REQUESTS', N'U') AND name = N'IX_PROJECT_REQUESTS_STATUS_EXPIRES_AT')
BEGIN
    CREATE INDEX [IX_PROJECT_REQUESTS_STATUS_EXPIRES_AT] ON [dbo].[PROJECT_REQUESTS] ([STATUS], [EXPIRES_AT]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_REQUESTS', N'U') AND name = N'IX_PROJECT_REQUESTS_TOKEN_HASH_STATUS_EXPIRES_AT')
BEGIN
    CREATE INDEX [IX_PROJECT_REQUESTS_TOKEN_HASH_STATUS_EXPIRES_AT] ON [dbo].[PROJECT_REQUESTS] ([TOKEN_HASH], [STATUS], [EXPIRES_AT]);
END