IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_ACTIONS', N'U') AND name = N'IX_GENERATION_ACTIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_GENERATION_ACTIONS_IsDeleted] ON [dbo].[GENERATION_ACTIONS] ([IsDeleted]);
END