IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_RUNS', N'U') AND name = N'IX_GENERATION_RUNS_IsDeleted')
BEGIN
    CREATE INDEX [IX_GENERATION_RUNS_IsDeleted] ON [dbo].[GENERATION_RUNS] ([IsDeleted]);
END