IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_ANALYSES_PROJECTS_PROJECT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_ANALYSES'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_ANALYSES] ADD CONSTRAINT [FK_PROJECT_ANALYSES_PROJECTS_PROJECT_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECTS] ([ID]);
END