IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_MODULES', N'U') AND name = N'IX_PROJECT_MODULES_ARCHITECTURAL_PATTERN_KEY')
BEGIN
    CREATE INDEX [IX_PROJECT_MODULES_ARCHITECTURAL_PATTERN_KEY] ON [dbo].[PROJECT_MODULES] ([ARCHITECTURAL_PATTERN_KEY]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_MODULES', N'U') AND name = N'IX_PROJECT_MODULES_DB_TYPE_KEY')
BEGIN
    CREATE INDEX [IX_PROJECT_MODULES_DB_TYPE_KEY] ON [dbo].[PROJECT_MODULES] ([DB_TYPE_KEY]);
END