IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_MODULES_PROJECTS_PROJECT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_MODULES'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_MODULES] ADD CONSTRAINT [FK_PROJECT_MODULES_PROJECTS_PROJECT_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_MODULES_MODULE_TEMPLATES_MODULE_TEMPLATE_KEY' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_MODULES'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_MODULES] ADD CONSTRAINT [FK_PROJECT_MODULES_MODULE_TEMPLATES_MODULE_TEMPLATE_KEY] FOREIGN KEY ([MODULE_TEMPLATE_KEY]) REFERENCES [dbo].[MODULE_TEMPLATES] ([KEY]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_MODULES_DB_TYPES_DB_TYPE_KEY' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_MODULES'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_MODULES] ADD CONSTRAINT [FK_PROJECT_MODULES_DB_TYPES_DB_TYPE_KEY] FOREIGN KEY ([DB_TYPE_KEY]) REFERENCES [dbo].[DB_TYPES] ([KEY]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_MODULES_ARCHITECTURAL_PATTERNS_ARCHITECTURAL_PATTERN_KEY' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_MODULES'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_MODULES] ADD CONSTRAINT [FK_PROJECT_MODULES_ARCHITECTURAL_PATTERNS_ARCHITECTURAL_PATTERN_KEY] FOREIGN KEY ([ARCHITECTURAL_PATTERN_KEY]) REFERENCES [dbo].[ARCHITECTURAL_PATTERNS] ([KEY]);
END