IF OBJECT_ID(N'dbo.GENERATION_STATUSES', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[GENERATION_STATUSES] (
        [ID] int NOT NULL,
        [DESCRIPTION] nvarchar(250) NOT NULL,
        [EXECUTION_DESCRIPTION] nvarchar(250) NOT NULL,
        [ICON] nvarchar(250) NULL,
        [NAME] nvarchar(250) NOT NULL,
        CONSTRAINT [PK_GENERATION_STATUSES] PRIMARY KEY ([ID])
    );
END;