IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_LOGS', N'U') AND name = N'IX_GENERATION_LOGS_IsDeleted')
BEGIN
    CREATE INDEX [IX_GENERATION_LOGS_IsDeleted] ON [dbo].[GENERATION_LOGS] ([IsDeleted]);
END