IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_RUN_TYPES', N'U') AND name = N'IX_GENERATION_RUN_TYPES_IsDeleted')
BEGIN
    CREATE INDEX [IX_GENERATION_RUN_TYPES_IsDeleted] ON [dbo].[GENERATION_RUN_TYPES] ([IsDeleted]);
END