IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_MODULE_REVISIONS_PROJECTS_PROJECT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_MODULE_REVISIONS'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_MODULE_REVISIONS] ADD CONSTRAINT [FK_PROJECT_MODULE_REVISIONS_PROJECTS_PROJECT_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECTS] ([ID]);
END