IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_STATUSES', N'U') AND name = N'IX_GENERATION_STATUSES_NAME')
BEGIN
    CREATE INDEX [IX_GENERATION_STATUSES_NAME] ON [dbo].[GENERATION_STATUSES] ([NAME]);
END