IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_GENERATION_LOGS_PROJECTS_PROJECT_ID' AND parent_object_id = OBJECT_ID(N'dbo.GENERATION_LOGS'))
BEGIN
    ALTER TABLE [dbo].[GENERATION_LOGS] ADD CONSTRAINT [FK_GENERATION_LOGS_PROJECTS_PROJECT_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_GENERATION_LOGS_GENERATION_STATUSES_GENERATION_STATUS_ID' AND parent_object_id = OBJECT_ID(N'dbo.GENERATION_LOGS'))
BEGIN
    ALTER TABLE [dbo].[GENERATION_LOGS] ADD CONSTRAINT [FK_GENERATION_LOGS_GENERATION_STATUSES_GENERATION_STATUS_ID] FOREIGN KEY ([GENERATION_STATUS_ID]) REFERENCES [dbo].[GENERATION_STATUSES] ([ID]);
END