IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_ANALYSES', N'U') AND name = N'IX_PROJECT_ANALYSES_ANALYSIS_ID')
BEGIN
    CREATE INDEX [IX_PROJECT_ANALYSES_ANALYSIS_ID] ON [dbo].[PROJECT_ANALYSES] ([ANALYSIS_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_ANALYSES', N'U') AND name = N'IX_PROJECT_ANALYSES_PROJECT_ID_IS_CURRENT')
BEGIN
    CREATE INDEX [IX_PROJECT_ANALYSES_PROJECT_ID_IS_CURRENT] ON [dbo].[PROJECT_ANALYSES] ([PROJECT_ID], [IS_CURRENT]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_ANALYSES', N'U') AND name = N'IX_PROJECT_ANALYSES_STATUS')
BEGIN
    CREATE INDEX [IX_PROJECT_ANALYSES_STATUS] ON [dbo].[PROJECT_ANALYSES] ([STATUS]);
END