IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_RUNS', N'U') AND name = N'IX_GENERATION_RUNS_GENERATION_RUN_TYPE_ID')
BEGIN
    CREATE INDEX [IX_GENERATION_RUNS_GENERATION_RUN_TYPE_ID] ON [dbo].[GENERATION_RUNS] ([GENERATION_RUN_TYPE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_RUNS', N'U') AND name = N'IX_GENERATION_RUNS_PROJECT_ID_IS_FINISHED')
BEGIN
    CREATE INDEX [IX_GENERATION_RUNS_PROJECT_ID_IS_FINISHED] ON [dbo].[GENERATION_RUNS] ([PROJECT_ID], [IS_FINISHED]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_RUNS', N'U') AND name = N'IX_GENERATION_RUNS_SESSION_ID')
BEGIN
    CREATE INDEX [IX_GENERATION_RUNS_SESSION_ID] ON [dbo].[GENERATION_RUNS] ([SESSION_ID]);
END