IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_ANALYSIS_DOCUMENTS', N'U') AND name = N'IX_PROJECT_ANALYSIS_DOCUMENTS_PROJECT_ANALYSIS_ID')
BEGIN
    CREATE INDEX [IX_PROJECT_ANALYSIS_DOCUMENTS_PROJECT_ANALYSIS_ID] ON [dbo].[PROJECT_ANALYSIS_DOCUMENTS] ([PROJECT_ANALYSIS_ID]);
END