IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECTS_GENERATION_STATUSES_GENERATION_STATUS_ID' AND parent_object_id = OBJECT_ID(N'dbo.PROJECTS'))
BEGIN
    ALTER TABLE [dbo].[PROJECTS] ADD CONSTRAINT [FK_PROJECTS_GENERATION_STATUSES_GENERATION_STATUS_ID] FOREIGN KEY ([GENERATION_STATUS_ID]) REFERENCES [dbo].[GENERATION_STATUSES] ([ID]);
END