IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.MODULE_TEMPLATES', N'U') AND name = N'IX_MODULE_TEMPLATES_IS_WEB_PROJECT')
BEGIN
    CREATE INDEX [IX_MODULE_TEMPLATES_IS_WEB_PROJECT] ON [dbo].[MODULE_TEMPLATES] ([IS_WEB_PROJECT]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.MODULE_TEMPLATES', N'U') AND name = N'IX_MODULE_TEMPLATES_NAME')
BEGIN
    CREATE INDEX [IX_MODULE_TEMPLATES_NAME] ON [dbo].[MODULE_TEMPLATES] ([NAME]);
END