IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_GENERATION_ACTIONS_PROJECTS_PROJECT_ID' AND parent_object_id = OBJECT_ID(N'dbo.GENERATION_ACTIONS'))
BEGIN
    ALTER TABLE [dbo].[GENERATION_ACTIONS] ADD CONSTRAINT [FK_GENERATION_ACTIONS_PROJECTS_PROJECT_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_GENERATION_ACTIONS_GENERATION_RUNS_GENERATION_RUN_ID' AND parent_object_id = OBJECT_ID(N'dbo.GENERATION_ACTIONS'))
BEGIN
    ALTER TABLE [dbo].[GENERATION_ACTIONS] ADD CONSTRAINT [FK_GENERATION_ACTIONS_GENERATION_RUNS_GENERATION_RUN_ID] FOREIGN KEY ([GENERATION_RUN_ID]) REFERENCES [dbo].[GENERATION_RUNS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_GENERATION_ACTIONS_GENERATION_STEPS_GENERATION_STEP_ID' AND parent_object_id = OBJECT_ID(N'dbo.GENERATION_ACTIONS'))
BEGIN
    ALTER TABLE [dbo].[GENERATION_ACTIONS] ADD CONSTRAINT [FK_GENERATION_ACTIONS_GENERATION_STEPS_GENERATION_STEP_ID] FOREIGN KEY ([GENERATION_STEP_ID]) REFERENCES [dbo].[GENERATION_STEPS] ([ID]);
END