IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_ACTIONS', N'U') AND name = N'IX_GENERATION_ACTIONS_GENERATION_RUN_ID')
BEGIN
    CREATE INDEX [IX_GENERATION_ACTIONS_GENERATION_RUN_ID] ON [dbo].[GENERATION_ACTIONS] ([GENERATION_RUN_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_ACTIONS', N'U') AND name = N'IX_GENERATION_ACTIONS_GENERATION_STEP_ID_GENERATION_RUN_ID')
BEGIN
    CREATE INDEX [IX_GENERATION_ACTIONS_GENERATION_STEP_ID_GENERATION_RUN_ID] ON [dbo].[GENERATION_ACTIONS] ([GENERATION_STEP_ID], [GENERATION_RUN_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_ACTIONS', N'U') AND name = N'IX_GENERATION_ACTIONS_PROJECT_ID')
BEGIN
    CREATE INDEX [IX_GENERATION_ACTIONS_PROJECT_ID] ON [dbo].[GENERATION_ACTIONS] ([PROJECT_ID]);
END