IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_SCHEMA_SNAPSHOTS_PROJECTS_PROJECT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_SCHEMA_SNAPSHOTS'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_SCHEMA_SNAPSHOTS] ADD CONSTRAINT [FK_PROJECT_SCHEMA_SNAPSHOTS_PROJECTS_PROJECT_ID] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECTS] ([ID]);
END