IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_STEPS', N'U') AND name = N'IX_GENERATION_STEPS_NAME')
BEGIN
    CREATE INDEX [IX_GENERATION_STEPS_NAME] ON [dbo].[GENERATION_STEPS] ([NAME]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_STEPS', N'U') AND name = N'IX_GENERATION_STEPS_NEEDS')
BEGIN
    CREATE INDEX [IX_GENERATION_STEPS_NEEDS] ON [dbo].[GENERATION_STEPS] ([NEEDS]);
END