IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROJECT_PROMPTS', N'U') AND name = N'IX_PROJECT_PROMPTS_PROJECT_ID')
BEGIN
    CREATE INDEX [IX_PROJECT_PROMPTS_PROJECT_ID] ON [dbo].[PROJECT_PROMPTS] ([PROJECT_ID]);
END