IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.GENERATION_STEPS', N'U') AND name = N'IX_GENERATION_STEPS_IsDeleted')
BEGIN
    CREATE INDEX [IX_GENERATION_STEPS_IsDeleted] ON [dbo].[GENERATION_STEPS] ([IsDeleted]);
END