IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PROJECT_ANALYSIS_DOCUMENTS_PROJECT_ANALYSES_PROJECT_ANALYSIS_ID' AND parent_object_id = OBJECT_ID(N'dbo.PROJECT_ANALYSIS_DOCUMENTS'))
BEGIN
    ALTER TABLE [dbo].[PROJECT_ANALYSIS_DOCUMENTS] ADD CONSTRAINT [FK_PROJECT_ANALYSIS_DOCUMENTS_PROJECT_ANALYSES_PROJECT_ANALYSIS_ID] FOREIGN KEY ([PROJECT_ANALYSIS_ID]) REFERENCES [dbo].[PROJECT_ANALYSES] ([ID]);
END