-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS TOTAL 
FROM [PROJECT_PROMPTS] PP 
WHERE PP.[IsDeleted] = 0 
	AND PP.[CREATED_DATE] > DATEADD(DAY, -365,
	GETDATE()) 