-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT PP.[ID], PP.[PROJECT_ID], PP.[AI_TYPE], PP.[USER_PROMPT], PP.[SYSTEM_PROMPT], PP.[AI_RESPONSE], PP.[CREATED_DATE], PP.[UPDATED_DATE] 
FROM [PROJECT_PROMPTS] PP 
WHERE PP.[IsDeleted] = 0 
	AND PP.[PROJECT_ID] = @PRM_PROJECT_PROMPT_PROJECT_ID 
ORDER BY PP.[ID], PP.[AI_TYPE] 