// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Dtos.AuditLog
{
    public record StatsDailyHttpRequestsByDayResponseDto
    {
        public string RequestDay { get; init; }
        public int TotalRequests { get; init; }
        public decimal AvgDurationMs { get; init; }
        public decimal MaxDurationMs { get; init; }
        public decimal MinDurationMs { get; init; }
    }
}