// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Quickcode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.IdentityModule.Domain.Entities;
using QuickCode.Quickcode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.AspNetUser;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Features.AspNetUser
{
    public class UpdatePhotoCommand : IRequest<Response<int>>
    {
        public string AspNetUserId { get; set; }
        public UpdatePhotoRequestDto UpdateRequest { get; set; }

        public UpdatePhotoCommand(string aspNetUserId, UpdatePhotoRequestDto updateRequest)
        {
            this.AspNetUserId = aspNetUserId;
            this.UpdateRequest = updateRequest;
        }

        public class UpdatePhotoHandler : IRequestHandler<UpdatePhotoCommand, Response<int>>
        {
            private readonly ILogger<UpdatePhotoHandler> _logger;
            private readonly IAspNetUserRepository _repository;
            public UpdatePhotoHandler(ILogger<UpdatePhotoHandler> logger, IAspNetUserRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(UpdatePhotoCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.UpdatePhotoAsync(request.AspNetUserId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}