// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.QuickcodeModule.Domain.Entities;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.Infrastructure.Data;
using QuickCode.Quickcode.Infrastructure.Data.Extensions;
using QuickCode.Quickcode.Infrastructure.Data.Helpers;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.ProjectAnalysisDocument;
using QuickCode.Quickcode.QuickcodeModule.Application.Mappings;
using QuickCode.Quickcode.QuickcodeModule.Persistence.Sql;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Repositories
{
    public partial class ProjectAnalysisDocumentRepository : BaseRepository, IProjectAnalysisDocumentRepository
    {
        public async Task<RepoResponse<GetDocumentResponseDto>> GetDocumentAsync(Guid projectAnalysisDocumentId)
        {
            return await ExecuteWithExceptionHandling(ProjectAnalysisDocumentCrudSqlBindings.OperationNames.GetDocument, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectAnalysisDocument.Query.GetDocument);
                var parameters = new
                {
                    PRM_PROJECT_ANALYSIS_DOCUMENT_ID = projectAnalysisDocumentId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetDocumentResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ProjectAnalysisDocument");
            });
        }

        public async Task<RepoResponse<List<GetByAnalysisResponseDto>>> GetByAnalysisAsync(Guid projectAnalysisDocumentProjectAnalysisId)
        {
            return await ExecuteWithExceptionHandling(ProjectAnalysisDocumentCrudSqlBindings.OperationNames.GetByAnalysis, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectAnalysisDocument.Query.GetByAnalysis);
                var parameters = new
                {
                    PRM_PROJECT_ANALYSIS_DOCUMENT_PROJECT_ANALYSIS_ID = projectAnalysisDocumentProjectAnalysisId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetByAnalysisResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ProjectAnalysisDocument");
            });
        }

        public async Task<RepoResponse<List<GetByProjectResponseDto>>> GetByProjectAsync(string projectsKey)
        {
            return await ExecuteWithExceptionHandling(ProjectAnalysisDocumentCrudSqlBindings.OperationNames.GetByProject, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProjectAnalysisDocument.Query.GetByProject);
                var parameters = new
                {
                    PRM_PROJECTS_KEY = projectsKey
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetByProjectResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ProjectAnalysisDocument");
            });
        }
    }
}