// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.ApiMethodAccessGrant;
using ApiMethodAccessGrantEntity = QuickCode.QuickCode.IdentityModule.Domain.Entities.ApiMethodAccessGrant;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Mappings
{
    public static class ApiMethodAccessGrantMappings
    {
        public static List<ApiMethodAccessGrantDto> ToDto(this IEnumerable<ApiMethodAccessGrantEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ApiMethodAccessGrantDto ToDto(this ApiMethodAccessGrantEntity model)
        {
            return new ApiMethodAccessGrantDto
            {
                PermissionGroupName = model.PermissionGroupName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                ModifiedBy = model.ModifiedBy,
                IsActive = model.IsActive
            };
        }

        public static ApiMethodAccessGrantEntity ToEntity(this ApiMethodAccessGrantDto model)
        {
            return new ApiMethodAccessGrantEntity
            {
                PermissionGroupName = model.PermissionGroupName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                ModifiedBy = model.ModifiedBy,
                IsActive = model.IsActive
            };
        }
    }
}