// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.KafkaEvent;
using KafkaEventEntity = QuickCode.Quickcode.IdentityModule.Domain.Entities.KafkaEvent;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Mappings
{
    public static class KafkaEventMappings
    {
        public static List<KafkaEventDto> ToDto(this IEnumerable<KafkaEventEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static KafkaEventDto ToDto(this KafkaEventEntity model)
        {
            return new KafkaEventDto
            {
                TopicName = model.TopicName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                IsActive = model.IsActive
            };
        }

        public static KafkaEventEntity ToEntity(this KafkaEventDto model)
        {
            return new KafkaEventEntity
            {
                TopicName = model.TopicName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                IsActive = model.IsActive
            };
        }
    }
}