// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.PortalMenu;
using PortalMenuEntity = QuickCode.Quickcode.IdentityModule.Domain.Entities.PortalMenu;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Mappings
{
    public static class PortalMenuMappings
    {
        public static List<PortalMenuDto> ToDto(this IEnumerable<PortalMenuEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PortalMenuDto ToDto(this PortalMenuEntity model)
        {
            return new PortalMenuDto
            {
                Key = model.Key,
                Name = model.Name,
                Text = model.Text,
                Tooltip = model.Tooltip,
                ActionName = model.ActionName,
                OrderNo = model.OrderNo,
                ParentName = model.ParentName
            };
        }

        public static PortalMenuEntity ToEntity(this PortalMenuDto model)
        {
            return new PortalMenuEntity
            {
                Key = model.Key,
                Name = model.Name,
                Text = model.Text,
                Tooltip = model.Tooltip,
                ActionName = model.ActionName,
                OrderNo = model.OrderNo,
                ParentName = model.ParentName
            };
        }
    }
}