// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.RefreshToken;
using RefreshTokenEntity = QuickCode.Quickcode.IdentityModule.Domain.Entities.RefreshToken;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Mappings
{
    public static class RefreshTokenMappings
    {
        public static List<RefreshTokenDto> ToDto(this IEnumerable<RefreshTokenEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RefreshTokenDto ToDto(this RefreshTokenEntity model)
        {
            return new RefreshTokenDto
            {
                Id = model.Id,
                UserId = model.UserId,
                Token = model.Token,
                ExpiryDate = model.ExpiryDate,
                CreatedDate = model.CreatedDate,
                IsRevoked = model.IsRevoked
            };
        }

        public static RefreshTokenEntity ToEntity(this RefreshTokenDto model)
        {
            return new RefreshTokenEntity
            {
                Id = model.Id,
                UserId = model.UserId,
                Token = model.Token,
                ExpiryDate = model.ExpiryDate,
                CreatedDate = model.CreatedDate,
                IsRevoked = model.IsRevoked
            };
        }
    }
}