// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.TopicWorkflow;
using TopicWorkflowEntity = QuickCode.QuickCode.IdentityModule.Domain.Entities.TopicWorkflow;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Mappings
{
    public static class TopicWorkflowMappings
    {
        public static List<TopicWorkflowDto> ToDto(this IEnumerable<TopicWorkflowEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TopicWorkflowDto ToDto(this TopicWorkflowEntity model)
        {
            return new TopicWorkflowDto
            {
                Id = model.Id,
                KafkaEventsTopicName = model.KafkaEventsTopicName,
                WorkflowContent = model.WorkflowContent
            };
        }

        public static TopicWorkflowEntity ToEntity(this TopicWorkflowDto model)
        {
            return new TopicWorkflowEntity
            {
                Id = model.Id,
                KafkaEventsTopicName = model.KafkaEventsTopicName,
                WorkflowContent = model.WorkflowContent
            };
        }
    }
}