// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Application.Dtos.ProjectSchemaSnapshot
{
    public record GetByTriggerResponseDto
    {
        public Guid Id { get; init; }
        public string Label { get; init; }
        public SnapshotTrigger Trigger { get; init; }
        public DateTime CreatedDate { get; init; }
        public string ProjectKey { get; init; }
    }
}