// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.QuickCode.IdentityModule.Domain;
using QuickCode.QuickCode.Domain.Shared.Abstractions;
using QuickCode.QuickCode.Domain.Shared.Entities;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Domain.Entities;

[Table("ApiKeyUsageLogs")]
public partial class ApiKeyUsageLog : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("Id")]
	public int Id { get; set; }
	
	[Column("ApiKeyId")]
	public Guid ApiKeyId { get; set; }
	
	[Column("HttpMethod", TypeName = "nvarchar(50)")]
	public HttpMethodType HttpMethod { get; set; }
	
	[Column("UrlPath")]
	[StringLength(1000)]
	public string UrlPath { get; set; }
	
	[Column("StatusCode")]
	public int StatusCode { get; set; }
	
	[Column("IpAddress")]
	[StringLength(64)]
	public string? IpAddress { get; set; }
	
	[Column("CreatedDate")]
	public DateTime CreatedDate { get; set; }
	
	[ForeignKey("ApiKeyId")]
	[InverseProperty(nameof(ApiKey.ApiKeyUsageLogs))]
	public virtual ApiKey ApiKey { get; set; } = null!;
}

