// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.QuickCode.IdentityModule.Domain;
using QuickCode.QuickCode.Domain.Shared.Abstractions;
using QuickCode.QuickCode.Domain.Shared.Entities;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Domain.Entities;

[Table("PortalPageAccessGrants")]
public partial class PortalPageAccessGrant : IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.None)]
	[Column("PermissionGroupName")]
	[StringLength(1000)]
	public string PermissionGroupName { get; set; }
	
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.None)]
	[Column("PortalPageDefinitionKey")]
	[StringLength(1000)]
	public string PortalPageDefinitionKey { get; set; }
	
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.None)]
	[Column("PageAction", TypeName = "nvarchar(50)")]
	public PageActionType PageAction { get; set; }
	
	[Column("ModifiedBy", TypeName = "nvarchar(50)")]
	public ModificationType ModifiedBy { get; set; }
	
	[Column("IsActive")]
	public bool IsActive { get; set; }
	
	[ForeignKey("PortalPageDefinitionKey")]
	[InverseProperty(nameof(PortalPageDefinition.PortalPageAccessGrants))]
	public virtual PortalPageDefinition PortalPageDefinition { get; set; } = null!;

	[ForeignKey("PermissionGroupName")]
	[InverseProperty(nameof(PermissionGroup.PortalPageAccessGrants))]
	public virtual PermissionGroup PermissionGroup { get; set; } = null!;
}

