-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [KEY],
    [NAME],
    [TEMPLATE_IMAGE],
    [DESCRIPTION],
    [IS_WEB_PROJECT],
    [DBML],
    [INITIAL_DATA],
    [ORDER]
FROM [dbo].[MODULE_TEMPLATES]
WHERE
    [KEY] = @PRM_MODULE_TEMPLATE_KEY;