-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[PortalPageDefinitions] (
    [Key],
    [ModuleName],
    [ModelName],
    [PageAction],
    [PagePath]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PORTAL_PAGE_DEFINITION_KEY,
    @PRM_PORTAL_PAGE_DEFINITION_MODULE_NAME,
    @PRM_PORTAL_PAGE_DEFINITION_MODEL_NAME,
    @PRM_PORTAL_PAGE_DEFINITION_PAGE_ACTION,
    @PRM_PORTAL_PAGE_DEFINITION_PAGE_PATH
    );