// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.QuickcodeModule.Domain.Entities;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.ProjectModule;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Application.Services.ProjectModule
{
    public partial class ProjectModuleService : IProjectModuleService
    {
        private readonly ILogger<ProjectModuleService> _logger;
        private readonly IProjectModuleRepository _repository;
        public ProjectModuleService(ILogger<ProjectModuleService> logger, IProjectModuleRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<ProjectModuleDto>> InsertAsync(ProjectModuleDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(ProjectModuleDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(Guid projectId, string moduleName, string moduleTemplateKey, ProjectModuleDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.ProjectId, request.ModuleName, request.ModuleTemplateKey);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<ListResult<ProjectModuleDto>>> ListAsync(int? pageNumber, int? pageSize, bool includeCount = false)
        {
            var listTask = _repository.ListAsync(pageNumber, pageSize);
            if (!includeCount)
                return (await listTask).ToListResultResponse();
            var countTask = _repository.CountAsync();
            await Task.WhenAll(listTask, countTask);
            return (await listTask).ToListResultResponse(await countTask);
        }

        public async Task<Response<ProjectModuleDto>> GetItemAsync(Guid projectId, string moduleName, string moduleTemplateKey)
        {
            var returnValue = await _repository.GetByPkAsync(projectId, moduleName, moduleTemplateKey);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(Guid projectId, string moduleName, string moduleTemplateKey)
        {
            var deleteItem = await _repository.GetByPkAsync(projectId, moduleName, moduleTemplateKey);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetProjectModulesResponseDto>>> GetProjectModulesAsync(string projectsKey)
        {
            var returnValue = await _repository.GetProjectModulesAsync(projectsKey);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetProjectModuleWithKeysResponseDto>> GetProjectModuleWithKeysAsync(string projectsKey, string projectModulesModuleName, string projectModulesModuleTemplateKey)
        {
            var returnValue = await _repository.GetProjectModuleWithKeysAsync(projectsKey, projectModulesModuleName, projectModulesModuleTemplateKey);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetProjectModuleEmailsResponseDto>>> GetProjectModuleEmailsAsync(string projectsKey)
        {
            var returnValue = await _repository.GetProjectModuleEmailsAsync(projectsKey);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetProjectModuleResponseDto>> GetProjectModuleAsync(string projectsKey, string projectModulesModuleName)
        {
            var returnValue = await _repository.GetProjectModuleAsync(projectsKey, projectModulesModuleName);
            return returnValue.ToResponse();
        }
    }
}