// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.QuickCodeModule.Domain.Entities;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.GenerationRun;
using System.Threading.Tasks;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Application.Interfaces.Repositories
{
    public partial interface IGenerationRunRepository : IBaseRepository<GenerationRunDto>
    {
        Task<RepoResponse<GenerationRunDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetGenerationRunsFirstResponseDto>> GetGenerationRunsFirstAsync(Guid generationRunProjectId, bool? generationRunIsFinished);
        Task<RepoResponse<List<GetGenerationRunsByProjectIdResponseDto>>> GetGenerationRunsByProjectIdAsync(Guid generationRunsProjectId);
        Task<RepoResponse<List<GetGenerationRunsWithProjectNameResponseDto>>> GetGenerationRunsWithProjectNameAsync(string projectsName);
        Task<RepoResponse<List<GetGenerationRunsWithSessionIdResponseDto>>> GetGenerationRunsWithSessionIdAsync(string generationRunsSessionId);
        Task<RepoResponse<int>> FinishAllUnfinishedRunsAsync(FinishAllUnfinishedRunsRequestDto updateRequest);
    }
}