// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using Dapper;
using System.Collections.Generic;
using System.IO.Compression;
using System.Reflection;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using HealthChecks.UI.Client;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using QuickCode.QuickCode.Infrastructure.Web;
using QuickCode.QuickCode.Infrastructure.Data;
using QuickCode.QuickCode.Infrastructure.Web.Extensions;
using QuickCode.QuickCode.Infrastructure.Web.Filters;
using QuickCode.QuickCode.Infrastructure.Web.Helpers;
using QuickCode.QuickCode.Infrastructure.Web.Models;
using QuickCode.QuickCode.IdentityModule.Api.Models;
using QuickCode.QuickCode.Infrastructure.Integration.Models;
using QuickCode.QuickCode.Infrastructure.Integration.Nswag.Extensions;
using QuickCode.QuickCode.IdentityModule.Api.Extension;
using QuickCode.QuickCode.IdentityModule.Persistence;
using QuickCode.QuickCode.IdentityModule.Persistence.Stores;
using QuickCode.QuickCode.Infrastructure.Data.Mappers;
using Serilog;
using QuickCode.QuickCode.Infrastructure.Web.Auditing;
using QuickCode.QuickCode.Infrastructure.Web.Middleware;
using QuickCode.QuickCode.Infrastructure.Web.ExceptionHandling;
using QuickCode.QuickCode.IdentityModule.Api;

DefaultTypeMap.MatchNamesWithUnderscores = true;
var builder = WebApplication.CreateBuilder(args);

builder.Configuration.UpdateConfigurationFromEnv();

var runMigration = Environment.GetEnvironmentVariable("RUN_MIGRATION");
var useHealthCheck = builder.Configuration.GetSection("AppSettings:UseHealthCheck").Get<bool>();
var databaseType = builder.Configuration.GetSection("AppSettings:DatabaseType").Get<string>();
var environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production";

builder.Services.AddLogger(builder.Configuration);
Log.Information($"Started({environmentName}) {builder.Configuration["Logging:ApiName"]} Started.");

builder.Services.AddQuickCodeMediator<Program>();
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();
builder.Services.AddProblemDetails();
builder.Services.AddHttpClient();
builder.Services.AddGatewayServiceTokenGenerator();

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = GatewayServiceTokenSettings.AuthenticationScheme;
    options.DefaultChallengeScheme = GatewayServiceTokenSettings.AuthenticationScheme;
})
.AddCookie(IdentityConstants.ApplicationScheme, options =>
{
    options.Cookie.Name = "QuickCodeCookieName";
    options.LoginPath = "/api/auth/login";
    options.LogoutPath = "/api/auth/logout";
    options.AccessDeniedPath = "/api/auth/access-denied";
})
.AddJwtBearer(GatewayServiceTokenSettings.AuthenticationScheme, options =>
    GatewayServiceTokenExtensions.ConfigureGatewayServiceTokenValidation(options, builder.Configuration));

builder.Services.AddAuthorization();
builder.Services.AddControllers(options =>
{
    options.Conventions.Add(new RouteTokenTransformerConvention(new ToKebabParameterTransformer(typeof(Program))));
    options.Filters.Add(typeof(ApiLogFilterAttribute));
    options.Filters.Add(new ProducesAttribute("application/json"));
}).AddJsonOptions(jsonOptions => { jsonOptions.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()); });

builder.Services.AddSingleton<IMemoryCache, MemoryCache>();
builder.Services.AddIdentityCore<ApiUser>()
    .AddUserStore<ApiUserDapperStore>()
    .AddDefaultTokenProviders()
    .AddClaimsPrincipalFactory<CustomClaimsPrincipalFactory>()
    .AddSignInManager()
    .AddApiEndpoints();

builder.Services.AddTransient<IEmailSender<ApiUser>, IdentityEmailServiceClient>();
builder.Services.AddTransient<IIdentityAccountEmailSender, IdentityEmailServiceClient>();

builder.Services.Configure<IdentityOptions>(options =>
{
    options.SignIn.RequireConfirmedEmail = true;
    options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
    options.Lockout.MaxFailedAccessAttempts = 5;
    options.Lockout.AllowedForNewUsers = true;
    options.Password.RequiredLength = PasswordPolicy.MinLength;
    options.Password.RequiredUniqueChars = 1;
    options.Password.RequireDigit = true;
    options.Password.RequireLowercase = true;
    options.Password.RequireUppercase = true;
    options.Password.RequireNonAlphanumeric = true;
});

builder.Services.AddResponseCompression();
builder.Services.Configure<GzipCompressionProviderOptions>(options => { options.Level = CompressionLevel.Fastest; });

builder.Services.AddHttpContextAccessor();
builder.Services.AddBankingGradeAuditing(builder.Configuration);
builder.Services.AddQuickCodeForwardedHeaders();
builder.Services.AddRateLimiting(builder.Configuration);

builder.Services.AddQuickCodeDbConnectionFactory();
builder.Services.AddHealthChecks();
builder.Services.AddRouting(options => options.LowercaseUrls = true);
builder.Services.AddQuickCodeRepositories("QuickCode.QuickCode.IdentityModule.Persistence", "QuickCode.QuickCode.IdentityModule.Application");
builder.Services.AddQuickCodeSwaggerGen(builder.Configuration, tokenType: "Bearer");
builder.Services.AddNswagServiceClient(builder.Configuration, typeof(Program));
builder.Services.AddServiceClient(builder.Configuration, typeof(Program));
builder.Services.AddKafkaEventPublishing();
builder.Services.AddEndpointsApiExplorer();

DapperTypeMapper.ConfigureTypeMappings();

builder.Services.AddScoped<IApiKeyStore, ApiKeyStore>();
builder.Services.AddSiteCustomizations();

var app = builder.Build();
app.UseSerilogRequestLogging();
app.UseResponseCompression();
app.UseDefaultFiles();
app.UseStaticFiles();

if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
}

app.UseExceptionHandler();
app.UseQuickCodeForwardedHeaders();

app.ConfigureSitePipelineEarly(app.Environment);

app.UseSecurityHeaders();
app.UseRateLimiting();
app.UseInputValidation();
app.UseSecurityLogging();
app.UseSecurityAudit();
app.UsePasswordPolicy();

app.UseSwagger();
app.UseSwaggerUI();

if (useHealthCheck && databaseType != "inMemory")
{
    app.UseHealthChecks("/hc", new HealthCheckOptions
    {
        Predicate = _ => true,
        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
    });
}

app.UseHttpsRedirection();

app.UseQuickCodeCors(app.Configuration);

app.UseAuthentication();
app.UseRouting();
app.UseAuthorization();

app.ConfigureSitePipeline(app.Environment);

app.MapGroup("/api/auth").WithTags("Authentications").MapQuickCodeIdentityApi<ApiUser>();

app.MapControllers();

app.ConfigureSitePipelineLate(app.Environment);

using (var scope = app.Services.CreateScope())
{
    if ((runMigration == null || runMigration!.Equals("yes", StringComparison.CurrentCultureIgnoreCase)) &&
        databaseType != "inMemory")
    {
        var migrationRunner = scope.ServiceProvider.GetRequiredService<QuickCodeSqlMigrationRunner>();
        await migrationRunner.MigrateAsync();
        
        var seedRunner = scope.ServiceProvider.GetRequiredService<QuickCodeSeedDataRunner>();
        await seedRunner.SeedAsync();
    }
}

await app.RunAsync();