-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[KafkaEvents]
SET
    [ApiMethodDefinitionKey] = @PRM_KAFKA_EVENT_API_METHOD_DEFINITION_KEY,
    [IsActive] = @PRM_KAFKA_EVENT_IS_ACTIVE
WHERE
    [TopicName] = @PRM_KAFKA_EVENT_TOPIC_NAME;