-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
DELETE FROM [dbo].[AspNetRoleClaims]
WHERE
    [Id] = @PRM_ASP_NET_ROLE_CLAIM_ID;