// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Quickcode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.IdentityModule.Domain.Entities;
using QuickCode.Quickcode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.IdentityModule.Application.Dtos.ApiKey;
using QuickCode.Quickcode.IdentityModule.Domain.Enums;

namespace QuickCode.Quickcode.IdentityModule.Application.Features.ApiKey
{
    public class GetActiveQuery : IRequest<Response<List<GetActiveResponseDto>>>
    {
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetActiveQuery(int? pageNumber, int? pageSize)
        {
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetActiveHandler : IRequestHandler<GetActiveQuery, Response<List<GetActiveResponseDto>>>
        {
            private readonly ILogger<GetActiveHandler> _logger;
            private readonly IApiKeyRepository _repository;
            public GetActiveHandler(ILogger<GetActiveHandler> logger, IApiKeyRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetActiveResponseDto>>> Handle(GetActiveQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetActiveAsync(request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}