// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.QuickCodeModule.Domain.Entities;
using QuickCode.QuickCode.QuickCodeModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.QuickCode.Infrastructure.Data;
using QuickCode.QuickCode.Infrastructure.Data.Extensions;
using QuickCode.QuickCode.Infrastructure.Data.Helpers;
using QuickCode.QuickCode.QuickCodeModule.Application.Dtos.DbType;
using QuickCode.QuickCode.QuickCodeModule.Application.Mappings;
using QuickCode.QuickCode.QuickCodeModule.Persistence.Sql;
using QuickCode.QuickCode.QuickCodeModule.Domain.Enums;

namespace QuickCode.QuickCode.QuickCodeModule.Persistence.Repositories
{
    public partial class DbTypeRepository : BaseRepository, IDbTypeRepository
    {
        public async Task<RepoResponse<GetByKeyResponseDto>> GetByKeyAsync(string dbTypeKey)
        {
            return await ExecuteWithExceptionHandling(DbTypeCrudSqlBindings.OperationNames.GetByKey, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.DbType.Query.GetByKey);
                var parameters = new
                {
                    PRM_DB_TYPE_KEY = dbTypeKey
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByKeyResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in DbType");
            });
        }

        public async Task<RepoResponse<GetByNameResponseDto>> GetByNameAsync(string dbTypeName)
        {
            return await ExecuteWithExceptionHandling(DbTypeCrudSqlBindings.OperationNames.GetByName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.DbType.Query.GetByName);
                var parameters = new
                {
                    PRM_DB_TYPE_NAME = dbTypeName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByNameResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in DbType");
            });
        }
    }
}