// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.QuickCode.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.QuickCode.Application.Contracts;
using QuickCode.QuickCode.IdentityModule.Domain.Entities;
using QuickCode.QuickCode.IdentityModule.Application.Interfaces.Repositories;
using QuickCode.QuickCode.IdentityModule.Application.Dtos.PermissionGroup;
using QuickCode.QuickCode.IdentityModule.Domain.Enums;

namespace QuickCode.QuickCode.IdentityModule.Application.Features.PermissionGroup
{
    public class UpdatePermissionGroupCommand : IRequest<Response<bool>>
    {
        public string Name { get; set; }
        public PermissionGroupDto request { get; set; }

        public UpdatePermissionGroupCommand(string name, PermissionGroupDto request)
        {
            this.request = request;
            this.Name = name;
        }

        public class UpdatePermissionGroupHandler : IRequestHandler<UpdatePermissionGroupCommand, Response<bool>>
        {
            private readonly ILogger<UpdatePermissionGroupHandler> _logger;
            private readonly IPermissionGroupRepository _repository;
            public UpdatePermissionGroupHandler(ILogger<UpdatePermissionGroupHandler> logger, IPermissionGroupRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdatePermissionGroupCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.Name);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}