// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using Microsoft.AspNetCore.Mvc;
using QuickCode.QuickCode.Infrastructure.Integration.Kafka;
using QuickCode.QuickCode.Infrastructure.Web.Filters;

namespace QuickCode.QuickCode.Infrastructure.Web.Extensions;

public static class KafkaEventPublishingExtensions
{
    /// <summary>
    /// Registers the shared Kafka producer and HTTP-event filter used by all generated APIs.
    /// Do not add this on Portal or Gateway.
    /// </summary>
    public static IServiceCollection AddKafkaEventPublishing(this IServiceCollection services)
    {
        services.AddMemoryCache();
        services.AddHttpClient();
        services.AddSingleton<IKafkaProducerWrapper, KafkaProducerWrapper>();
        services.AddSingleton<IKafkaEventCatalog, KafkaEventCatalog>();
        services.AddScoped<KafkaPublishFilter>();
        services.Configure<MvcOptions>(options => options.Filters.AddService<KafkaPublishFilter>());
        return services;
    }
}
