// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Reflection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using QuickCode.Quickcode.Portal.Helpers;
using QuickCode.Quickcode.Portal.Helpers.Authorization;
using QuickCode.Quickcode.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using QuickCode.Quickcode.Portal.Models;

namespace QuickCode.Quickcode.Portal.Controllers
{
    [Permission("Dashboard")]
    public class HomeController : BaseController
    {
        private readonly IPermissionGroupsClient _permissionGroupsClient;
        private readonly IApiMethodDefinitionsClient _apiMethodDefinitionsClient;
        private readonly IAspNetUsersClient _aspNetUsersClient;
        private readonly IAuditLogsClient _auditLogsClient;
        private readonly IPortalMenusClient _portalMenusClient;
        private readonly IServiceProvider _serviceProvider;

        public HomeController(
            ITableComboboxSettingsClient tableComboboxSettingsClient,
            IHttpContextAccessor httpContextAccessor,
            IMemoryCache cache,
            IPermissionGroupsClient permissionGroupsClient,
            IApiMethodDefinitionsClient apiMethodDefinitionsClient,
            IAspNetUsersClient aspNetUsersClient,
            IAuditLogsClient auditLogsClient,
            IPortalMenusClient portalMenusClient,
            IServiceProvider serviceProvider) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            _permissionGroupsClient = permissionGroupsClient;
            _apiMethodDefinitionsClient = apiMethodDefinitionsClient;
            _aspNetUsersClient = aspNetUsersClient;
            _auditLogsClient = auditLogsClient;
            _portalMenusClient = portalMenusClient;
            _serviceProvider = serviceProvider;
        }

        public async Task<IActionResult> Index(string selectedModule = null, string module = null)
        {
            var model = new DashboardStatsViewModel();
            var requestedModule = Request?.Query["selectedModule"].FirstOrDefault();
            if (string.IsNullOrWhiteSpace(requestedModule))
                requestedModule = Request?.Query["module"].FirstOrDefault();
            if (string.IsNullOrWhiteSpace(requestedModule))
                requestedModule = selectedModule ?? module;

            model.SelectedModule = string.IsNullOrWhiteSpace(requestedModule) ||
                                   IsAllModules(requestedModule)
                ? "All Modules"
                : ToSidebarModuleLabel(requestedModule);

            model.ModuleOptions = await GetCachedSidebarModuleOptionsAsync();
            model.ManagementQuickLinks = await GetCachedDashboardManagementQuickLinksAsync();
            if (!model.ModuleOptions.Any(i => IsSameModule(i, model.SelectedModule)))
                model.SelectedModule = "All Modules";

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DashboardSummary(string selectedModule = "All Modules")
        {
            var normalizedModule = IsAllModules(selectedModule) ? "All Modules" : ToSidebarModuleLabel(selectedModule);
            var cacheKey = $"dashboard-summary:{NormalizePropertyKey(normalizedModule)}";
            var summary = await GetOrCreateDashboardCacheAsync(cacheKey, TimeSpan.FromMinutes(1), async () =>
            {
                var model = new DashboardStatsViewModel { SelectedModule = normalizedModule };

                // Permission groups (3rd card)
                var groups = (await _permissionGroupsClient.PermissionGroupsListAsync())?.Items;
                model.TotalPermissionGroups = groups?.Count ?? 0;

                // Aggregate module + endpoint counts for current permission group,
                // matching the "Api Method Access Grant Manager" group selector behavior.
                var currentPermissionGroupName =
                    HttpContextAccessor.HttpContext?.User?.Claims?
                        .FirstOrDefault(c => c.Type == ClaimTypes.GroupSid)?.Value
                    ?? groups?.FirstOrDefault()?.Name;

                if (!string.IsNullOrWhiteSpace(currentPermissionGroupName))
                {
                    dynamic apiPermissions = await _apiMethodDefinitionsClient
                        .ApiMethodDefinitionsGetApiPermissionsAsync(currentPermissionGroupName);

                    if (apiPermissions?.ApiModulePermissionList != null)
                    {
                        model.TotalModules = (int)apiPermissions.ApiModulePermissionList.Count;

                        int endpoints = 0;
                        foreach (var moduleEntry in apiPermissions.ApiModulePermissionList)
                        {
                            foreach (var controllerEntry in moduleEntry.Value)
                            {
                                endpoints += (int)controllerEntry.Value.Count;
                            }
                        }

                        model.TotalEndpoints = endpoints;
                    }
                }

                // Users count (4th card). If NSwag doesn't expose a list method,
                // this will gracefully fall back to 0.
                model.TotalUsers = await TryGetUsersCountAsync(_aspNetUsersClient);

                return new
                {
                    model.TotalModules,
                    model.TotalEndpoints,
                    model.TotalPermissionGroups,
                    model.TotalUsers
                };
            });

            return Json(summary);
        }

        [HttpGet]
        public async Task<IActionResult> DashboardRequestMetrics(string selectedModule = "All Modules")
        {
            var moduleOptions = await GetCachedSidebarModuleOptionsAsync();
            var normalizedModule = IsAllModules(selectedModule) ? "All Modules" : ToSidebarModuleLabel(selectedModule);
            if (!moduleOptions.Any(i => IsSameModule(i, normalizedModule)))
                normalizedModule = "All Modules";

            var cacheKey = $"dashboard-request-metrics:{NormalizePropertyKey(normalizedModule)}";
            var metrics = await GetOrCreateDashboardCacheAsync(cacheKey, TimeSpan.FromMinutes(1), async () =>
            {
                var model = new DashboardStatsViewModel
                {
                    SelectedModule = normalizedModule,
                    ModuleOptions = moduleOptions
                };

                await FillRequestMetricsAsync(model);

                return new
                {
                    model.SelectedModule,
                    model.DailyRequestStats,
                    model.Last24HourLabels,
                    model.Last24HourKeys,
                    model.ModuleHourlySeries,
                    model.ModuleDailySeries,
                    model.ModuleTotalRequests,
                    model.StatusCodeStats,
                    model.ModuleTopServices
                };
            });

            return Json(metrics);
        }

        [HttpGet]
        public async Task<IActionResult> DashboardHourlyMetrics(string selectedModule = "All Modules")
        {
            var moduleOptions = await GetCachedSidebarModuleOptionsAsync();
            var normalizedModule = NormalizeDashboardSelectedModule(selectedModule, moduleOptions);
            var cacheKey = $"dashboard-hourly-metrics:{NormalizePropertyKey(normalizedModule)}";
            var metrics = await GetOrCreateDashboardCacheAsync(cacheKey, TimeSpan.FromMinutes(1), async () =>
            {
                var hourlyTask = TryGetHourlyStatsByModuleFromQueryAsync(moduleOptions, "All Modules");
                var statusTask = TryGetStatusCodeStatsLast24HoursByModuleFromQueryAsync(moduleOptions, normalizedModule);
                await Task.WhenAll(hourlyTask, statusTask).ConfigureAwait(false);

                var allRows = await hourlyTask.ConfigureAwait(false);
                var rows = allRows;
                var statusRows = await statusTask.ConfigureAwait(false);
                if (!IsAllModules(normalizedModule))
                {
                    rows = rows.Where(i => IsSameModule(i.Module, normalizedModule)).ToList();
                    statusRows = statusRows.Where(i => IsSameModule(i.Module, normalizedModule)).ToList();
                }

                var hourKeys = BuildLast24HourKeys(allRows);
                return new
                {
                    SelectedModule = normalizedModule,
                    Last24HourKeys = hourKeys,
                    Last24HourLabels = BuildHourLabels(hourKeys),
                    TotalHourlyTotals = BuildHourlyTotals(allRows, hourKeys),
                    ModuleHourlySeries = BuildModuleHourlySeries(rows, hourKeys, normalizedModule, moduleOptions),
                    StatusCodeStats = BuildStatusCodeStats(statusRows)
                };
            });

            return Json(metrics);
        }

        [HttpGet]
        public async Task<IActionResult> DashboardSevenDayMetrics(string selectedModule = "All Modules")
        {
            var moduleOptions = await GetCachedSidebarModuleOptionsAsync();
            var normalizedModule = NormalizeDashboardSelectedModule(selectedModule, moduleOptions);
            var cacheKey = $"dashboard-seven-day-metrics:{NormalizePropertyKey(normalizedModule)}";
            var metrics = await GetOrCreateDashboardCacheAsync(cacheKey, TimeSpan.FromMinutes(1), async () =>
            {
                var last7DayKeys = BuildLast7DayKeys();
                // One stats query type is enough: derive totals + duration client-side to cut HTTP fan-out.
                var statusTask = TryGetStatusCodeStatsByModuleFromQueryAsync(moduleOptions, normalizedModule);
                var topTask = TryGetTopServicesByModuleFromQueryAsync(moduleOptions, normalizedModule);
                var allDailyTask = TryGetDailyStatsByModuleFromQueryAsync(moduleOptions, "All Modules");
                await Task.WhenAll(allDailyTask, statusTask, topTask).ConfigureAwait(false);

                var allDailyByModuleRows = await allDailyTask.ConfigureAwait(false);
                var dailyByModuleRows = allDailyByModuleRows;
                var statusRows = await statusTask.ConfigureAwait(false);
                var topServiceRows = await topTask.ConfigureAwait(false);

                if (!IsAllModules(normalizedModule))
                {
                    dailyByModuleRows = dailyByModuleRows.Where(i => IsSameModule(i.Module, normalizedModule)).ToList();
                    statusRows = statusRows.Where(i => IsSameModule(i.Module, normalizedModule)).ToList();
                    topServiceRows = topServiceRows.Where(i => IsSameModule(i.Module, normalizedModule)).ToList();
                }

                var moduleTotalsRows = dailyByModuleRows
                    .GroupBy(i => i.Module, StringComparer.OrdinalIgnoreCase)
                    .Select(g => new ModuleTotalRequestViewModel { Module = g.Key, TotalRequests = g.Sum(x => x.TotalRequests) })
                    .ToList();

                var totalDailyRequestStats = BuildDailyRequestStatsFromModuleRows(allDailyByModuleRows);
                var dailyRequestStats = BuildDailyRequestStatsFromModuleRows(dailyByModuleRows);

                return new
                {
                    SelectedModule = normalizedModule,
                    DailyRequestStats = dailyRequestStats,
                    TotalDailyRequestStats = totalDailyRequestStats,
                    ModuleDailySeries = BuildModuleDailySeries(dailyByModuleRows, last7DayKeys, normalizedModule, moduleOptions),
                    ModuleTotalRequests = BuildModuleTotals(moduleTotalsRows, moduleOptions, normalizedModule),
                    StatusCodeStats = BuildStatusCodeStats(statusRows),
                    ModuleTopServices = topServiceRows
                        .GroupBy(i => i.Module, StringComparer.OrdinalIgnoreCase)
                        .Select(g => g.OrderByDescending(x => x.TotalRequests).First())
                        .OrderByDescending(i => i.TotalRequests)
                        .ThenBy(i => i.Module)
                        .Select(i => new ModuleTopServiceViewModel
                        {
                            Module = i.Module,
                            Method = i.Method,
                            Path = i.Path,
                            TotalRequests = i.TotalRequests
                        })
                        .ToList()
                };
            });

            return Json(metrics);
        }

        [HttpGet]
        public async Task<IActionResult> DashboardStatusMetrics(string selectedModule = "All Modules")
        {
            var moduleOptions = await GetCachedSidebarModuleOptionsAsync();
            var normalizedModule = NormalizeDashboardSelectedModule(selectedModule, moduleOptions);
            var cacheKey = $"dashboard-status-metrics:{NormalizePropertyKey(normalizedModule)}";
            var metrics = await GetOrCreateDashboardCacheAsync(cacheKey, TimeSpan.FromMinutes(1), async () =>
            {
                var rows = await TryGetStatusCodeStatsByModuleFromQueryAsync(moduleOptions, normalizedModule);
                if (!IsAllModules(normalizedModule))
                    rows = rows.Where(i => IsSameModule(i.Module, normalizedModule)).ToList();

                return new
                {
                    SelectedModule = normalizedModule,
                    StatusCodeStats = BuildStatusCodeStats(rows)
                };
            });

            return Json(metrics);
        }

        [HttpGet]
        public async Task<IActionResult> DashboardTopServices(string selectedModule = "All Modules")
        {
            var moduleOptions = await GetCachedSidebarModuleOptionsAsync();
            var normalizedModule = NormalizeDashboardSelectedModule(selectedModule, moduleOptions);
            var cacheKey = $"dashboard-top-services:{NormalizePropertyKey(normalizedModule)}";
            var metrics = await GetOrCreateDashboardCacheAsync(cacheKey, TimeSpan.FromMinutes(1), async () =>
            {
                var rows = await TryGetTopServicesByModuleFromQueryAsync(moduleOptions, normalizedModule);
                if (!IsAllModules(normalizedModule))
                    rows = rows.Where(i => IsSameModule(i.Module, normalizedModule)).ToList();

                return new
                {
                    SelectedModule = normalizedModule,
                    ModuleTopServices = rows
                        .GroupBy(i => i.Module, StringComparer.OrdinalIgnoreCase)
                        .Select(g => g.OrderByDescending(x => x.TotalRequests).First())
                        .OrderByDescending(i => i.TotalRequests)
                        .ThenBy(i => i.Module)
                        .Select(i => new ModuleTopServiceViewModel
                        {
                            Module = i.Module,
                            Method = i.Method,
                            Path = i.Path,
                            TotalRequests = i.TotalRequests
                        })
                        .ToList()
                };
            });

            return Json(metrics);
        }

        private async Task<T> GetOrCreateDashboardCacheAsync<T>(string key, TimeSpan ttl, Func<Task<T>> factory)
        {
            if (Cache.TryGetValue(key, out T cachedValue))
                return cachedValue;

            var value = await factory();
            Cache.Set(key, value, new MemoryCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = ttl
            });
            return value;
        }

        private static List<string> BuildLast7DayKeys()
            => Enumerable.Range(0, 7)
                .Select(dayOffset => DateTime.UtcNow.Date.AddDays(-6 + dayOffset).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture))
                .ToList();

        private static List<string> BuildLast24HourKeys(List<AggregatedHourlyStatRow> hourlyRows = null)
        {
            var endHour = DateTime.UtcNow;
            if (hourlyRows != null && hourlyRows.Count > 0)
            {
                var maxDataHour = hourlyRows
                    .Select(i => TryParseUtcHourKey(i.RequestHour, out var parsed) ? parsed : DateTime.MinValue)
                    .Where(i => i != DateTime.MinValue)
                    .DefaultIfEmpty(DateTime.UtcNow)
                    .Max();
                endHour = maxDataHour > DateTime.MinValue ? maxDataHour : DateTime.UtcNow;
            }

            endHour = new DateTime(endHour.Year, endHour.Month, endHour.Day, endHour.Hour, 0, 0, DateTimeKind.Utc);
            return Enumerable.Range(0, 24)
                .Select(hourOffset => endHour.AddHours(-23 + hourOffset).ToString("yyyy-MM-dd HH:00:00", CultureInfo.InvariantCulture))
                .ToList();
        }

        private static List<string> BuildHourLabels(List<string> hourKeys)
            => hourKeys
                .Select(i => TryParseUtcHourKey(i, out var parsed)
                    ? parsed.ToString("HH:00", CultureInfo.InvariantCulture)
                    : i)
                .ToList();

        private static List<int> BuildHourlyTotals(List<AggregatedHourlyStatRow> hourlyRows, List<string> hourKeys)
        {
            return hourKeys
                .Select(hour => (hourlyRows ?? new List<AggregatedHourlyStatRow>())
                    .Where(row => string.Equals(row.RequestHour, hour, StringComparison.OrdinalIgnoreCase))
                    .Sum(row => row.TotalRequests))
                .ToList();
        }

        private static string NormalizeDashboardSelectedModule(string selectedModule, List<string> moduleOptions)
        {
            var normalizedModule = IsAllModules(selectedModule) ? "All Modules" : ToSidebarModuleLabel(selectedModule);
            return moduleOptions.Any(i => IsSameModule(i, normalizedModule)) ? normalizedModule : "All Modules";
        }

        private async Task<List<string>> GetCachedSidebarModuleOptionsAsync()
            => await GetOrCreateDashboardCacheAsync(
                "dashboard-sidebar-module-options",
                TimeSpan.FromHours(1),
                GetSidebarModuleOptionsAsync);

        private async Task<List<DashboardQuickLinkViewModel>> GetCachedDashboardManagementQuickLinksAsync()
            => await GetOrCreateDashboardCacheAsync(
                "dashboard-management-quick-links",
                TimeSpan.FromHours(1),
                GetDashboardManagementQuickLinksAsync);

        private async Task FillLegacyShellMetricsAsync(DashboardStatsViewModel model)
        {
            // Kept isolated for server-render fallback scenarios; Index now loads metrics asynchronously.
            // Permission groups (3rd card)
            var groups = (await _permissionGroupsClient.PermissionGroupsListAsync())?.Items;
            model.TotalPermissionGroups = groups?.Count ?? 0;

            // Aggregate module + endpoint counts for current permission group,
            // matching the "Api Method Access Grant Manager" group selector behavior.
            var currentPermissionGroupName =
                HttpContextAccessor.HttpContext?.User?.Claims?
                    .FirstOrDefault(c => c.Type == ClaimTypes.GroupSid)?.Value
                ?? groups?.FirstOrDefault()?.Name;

            if (!string.IsNullOrWhiteSpace(currentPermissionGroupName))
            {
                dynamic apiPermissions = await _apiMethodDefinitionsClient
                    .ApiMethodDefinitionsGetApiPermissionsAsync(currentPermissionGroupName);

                if (apiPermissions?.ApiModulePermissionList != null)
                {
                    model.TotalModules = (int)apiPermissions.ApiModulePermissionList.Count;

                    int endpoints = 0;
                    foreach (var moduleEntry in apiPermissions.ApiModulePermissionList)
                    {
                        foreach (var controllerEntry in moduleEntry.Value)
                        {
                            endpoints += (int)controllerEntry.Value.Count;
                        }
                    }

                    model.TotalEndpoints = endpoints;
                }
            }

            // Users count (4th card). If NSwag doesn't expose a list method,
            // this will gracefully fall back to 0.
            model.TotalUsers = await TryGetUsersCountAsync(_aspNetUsersClient);
            model.ModuleOptions = await GetSidebarModuleOptionsAsync();
            model.ManagementQuickLinks = await GetDashboardManagementQuickLinksAsync();
            if (!model.ModuleOptions.Any(i => IsSameModule(i, model.SelectedModule)))
                model.SelectedModule = "All Modules";
            await FillRequestMetricsAsync(model);
        }

        private async Task FillRequestMetricsAsync(DashboardStatsViewModel model)
        {
            var last7DayKeys = BuildLast7DayKeys();

            var hourlyTask = TryGetHourlyStatsByModuleFromQueryAsync(model.ModuleOptions, model.SelectedModule);
            var dailyTask = TryGetDailyStatsByModuleFromQueryAsync(model.ModuleOptions, model.SelectedModule);
            var totalsTask = TryGetModuleTotalsFromQueryAsync(model.ModuleOptions, model.SelectedModule);
            var statusTask = TryGetStatusCodeStatsByModuleFromQueryAsync(model.ModuleOptions, model.SelectedModule);
            var topTask = TryGetTopServicesByModuleFromQueryAsync(model.ModuleOptions, model.SelectedModule);
            var durationTask = TryGetDailyStatsFromQueryAsync(model.ModuleOptions, model.SelectedModule);
            await Task.WhenAll(hourlyTask, dailyTask, totalsTask, statusTask, topTask, durationTask).ConfigureAwait(false);

            var hourlyByModuleRows = await hourlyTask.ConfigureAwait(false);
            var dailyByModuleRows = await dailyTask.ConfigureAwait(false);
            var moduleTotalsRows = await totalsTask.ConfigureAwait(false);
            var statusByModuleRows = await statusTask.ConfigureAwait(false);
            var topServiceRows = await topTask.ConfigureAwait(false);
            var dailyDurationRows = await durationTask.ConfigureAwait(false);

            if (!IsAllModules(model.SelectedModule))
            {
                hourlyByModuleRows = hourlyByModuleRows
                    .Where(i => IsSameModule(i.Module, model.SelectedModule))
                    .ToList();
                dailyByModuleRows = dailyByModuleRows
                    .Where(i => IsSameModule(i.Module, model.SelectedModule))
                    .ToList();
                moduleTotalsRows = moduleTotalsRows
                    .Where(i => IsSameModule(i.Module, model.SelectedModule))
                    .ToList();
                statusByModuleRows = statusByModuleRows
                    .Where(i => IsSameModule(i.Module, model.SelectedModule))
                    .ToList();
                topServiceRows = topServiceRows
                    .Where(i => IsSameModule(i.Module, model.SelectedModule))
                    .ToList();
            }

            if (NeedsDailyFallback(dailyByModuleRows, last7DayKeys))
            {
                dailyByModuleRows = BuildDailyRowsFromModuleTotals(moduleTotalsRows, model.SelectedModule);
            }

            var last24HourKeys = BuildLast24HourKeys(hourlyByModuleRows);
            model.Last24HourKeys = last24HourKeys;
            model.Last24HourLabels = BuildHourLabels(last24HourKeys);

            model.ModuleHourlySeries = BuildModuleHourlySeries(
                hourlyByModuleRows,
                last24HourKeys,
                model.SelectedModule,
                model.ModuleOptions);

            model.ModuleDailySeries = BuildModuleDailySeries(
                dailyByModuleRows,
                last7DayKeys,
                model.SelectedModule,
                model.ModuleOptions);
            if (moduleTotalsRows.Count == 0)
            {
                moduleTotalsRows = dailyByModuleRows
                    .GroupBy(i => i.Module, StringComparer.OrdinalIgnoreCase)
                    .Select(g => new ModuleTotalRequestViewModel
                    {
                        Module = g.Key,
                        TotalRequests = g.Sum(x => x.TotalRequests)
                    })
                    .ToList();
            }
            model.ModuleTotalRequests = BuildModuleTotals(moduleTotalsRows, model.ModuleOptions, model.SelectedModule);
            model.StatusCodeStats = statusByModuleRows
                .GroupBy(i => i.StatusCode)
                .OrderBy(g => g.Key)
                .Select(g => new StatusCodeStatViewModel
                {
                    StatusCode = g.Key,
                    TotalRequests = g.Sum(x => x.TotalRequests)
                })
                .ToList();

            if (dailyDurationRows.Count > 0)
            {
                model.DailyRequestStats = EnsureLast7DaysStats(dailyDurationRows);
            }
            else
            {
                model.DailyRequestStats = EnsureLast7DaysStats(dailyByModuleRows
                    .GroupBy(i => i.RequestDay)
                    .OrderByDescending(g => g.Key)
                    .Select(g =>
                    {
                        var totalRequests = g.Sum(x => x.TotalRequests);
                        var weightedDuration = totalRequests > 0
                            ? g.Sum(x => x.AvgDurationMs * x.TotalRequests) / totalRequests
                            : 0;
                        var minDuration = g.Where(x => x.MinDurationMs > 0).Select(x => x.MinDurationMs).DefaultIfEmpty(0).Min();
                        return new DailyRequestStatViewModel
                        {
                            RequestDay = g.Key,
                            TotalRequests = totalRequests,
                            AvgDurationMs = weightedDuration,
                            MaxDurationMs = g.Select(x => x.MaxDurationMs).DefaultIfEmpty(0).Max(),
                            MinDurationMs = minDuration
                        };
                    })
                    .ToList());
            }

            model.ModuleTopServices = topServiceRows
                .GroupBy(i => i.Module, StringComparer.OrdinalIgnoreCase)
                .Select(g => g.OrderByDescending(x => x.TotalRequests).First())
                .OrderByDescending(i => i.TotalRequests)
                .ThenBy(i => i.Module)
                .Select(i => new ModuleTopServiceViewModel
                {
                    Module = i.Module,
                    Method = i.Method,
                    Path = i.Path,
                    TotalRequests = i.TotalRequests
                })
                .ToList();

            // Hard safety net: if daily stats are still empty/zero but module totals exist,
            // rebuild daily stats from totals so Operational Insights and charts are never fully zero.
            var dailyTotal = model.DailyRequestStats.Sum(x => x.TotalRequests);
            var moduleTotal = model.ModuleTotalRequests.Sum(x => x.TotalRequests);
            if (dailyTotal == 0 && moduleTotal > 0)
            {
                var todayKey = DateTime.UtcNow.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
                var fallbackAvg = dailyByModuleRows.Count > 0
                    ? dailyByModuleRows.Average(x => x.AvgDurationMs)
                    : 0;
                var fallbackMax = dailyByModuleRows.Count > 0
                    ? dailyByModuleRows.Max(x => x.MaxDurationMs)
                    : 0;
                var fallbackMin = dailyByModuleRows.Count > 0
                    ? dailyByModuleRows.Where(x => x.MinDurationMs > 0).Select(x => x.MinDurationMs).DefaultIfEmpty(0).Min()
                    : 0;

                model.DailyRequestStats = EnsureLast7DaysStats(new List<DailyRequestStatViewModel>
                {
                    new DailyRequestStatViewModel
                    {
                        RequestDay = todayKey,
                        TotalRequests = moduleTotal,
                        AvgDurationMs = fallbackAvg,
                        MaxDurationMs = fallbackMax,
                        MinDurationMs = fallbackMin
                    }
                });
            }
        }

        private async Task<List<AggregatedDailyStatRow>> TryGetDailyStatsByModuleFromQueryAsync(List<string> moduleOptions, string selectedModule)
        {
            var results = await TryInvokeAcrossAuditClientsWithSourceAsync(
                moduleOptions,
                selectedModule,
                "AuditLogsStatsDailyHttpRequestsByDayByModuleAsync");
            if (results.Count == 0)
                return new List<AggregatedDailyStatRow>();

            var rows = new List<AggregatedDailyStatRow>();
            foreach (var result in results)
            {
                var item = result.Row;
                var requestDay = GetStringProperty(item, "RequestDay");
                if (string.IsNullOrWhiteSpace(requestDay))
                    requestDay = GetStringProperty(item, "Timestamp");
                requestDay = NormalizeOrDefaultRequestDayKey(requestDay);

                rows.Add(new AggregatedDailyStatRow
                {
                    Module = GetDashboardModuleForAuditRow(result.Module, item),
                    RequestDay = requestDay,
                    TotalRequests = GetIntProperty(item, "TotalRequests"),
                    AvgDurationMs = GetDoubleProperty(item, "AvgDurationMs"),
                    MaxDurationMs = GetLongProperty(item, "MaxDurationMs"),
                    MinDurationMs = GetLongProperty(item, "MinDurationMs")
                });
            }

            return rows.Where(i => !string.IsNullOrWhiteSpace(i.Module)).ToList();
        }

        private async Task<List<AggregatedHourlyStatRow>> TryGetHourlyStatsByModuleFromQueryAsync(List<string> moduleOptions, string selectedModule)
        {
            var results = await TryInvokeAcrossAuditClientsWithSourceAsync(
                moduleOptions,
                selectedModule,
                "AuditLogsStatsHourlyHttpRequestsByModuleAsync");
            if (results.Count == 0)
                return new List<AggregatedHourlyStatRow>();

            var rows = new List<AggregatedHourlyStatRow>();
            foreach (var result in results)
            {
                var item = result.Row;
                var requestHour = GetRequestHourValue(item);

                rows.Add(new AggregatedHourlyStatRow
                {
                    Module = GetDashboardModuleForAuditRow(result.Module, item),
                    RequestHour = NormalizeRequestHourKey(requestHour),
                    TotalRequests = GetIntProperty(item, "TotalRequests")
                });
            }

            if (rows.Count > 0)
            {
                var sample = rows[0];
                DashboardDebug($"Hourly raw rows={rows.Count}, sample module={sample.Module}, hour={sample.RequestHour}, total={sample.TotalRequests}");
                var missingHourCount = rows.Count(i => string.IsNullOrWhiteSpace(i.RequestHour));
                if (missingHourCount > 0)
                    DashboardDebug($"Hourly rows missing request hour after mapping={missingHourCount}. Sample source properties=[{GetPropertyNamesForDebug(results[0].Row)}]");
            }
            else
            {
                DashboardDebug("Hourly query returned zero rows after mapping.");
            }

            return rows
                .Where(i => !string.IsNullOrWhiteSpace(i.Module))
                .Where(i => !string.IsNullOrWhiteSpace(i.RequestHour))
                .ToList();
        }

        private async Task<List<AggregatedStatusCodeRow>> TryGetStatusCodeStatsByModuleFromQueryAsync(List<string> moduleOptions, string selectedModule)
        {
            var results = await TryInvokeAcrossAuditClientsWithSourceAsync(
                moduleOptions,
                selectedModule,
                "AuditLogsStatsHttpStatusCodesByModuleAsync");
            if (results.Count == 0)
                return new List<AggregatedStatusCodeRow>();

            var rows = new List<AggregatedStatusCodeRow>();
            foreach (var result in results)
            {
                var item = result.Row;
                rows.Add(new AggregatedStatusCodeRow
                {
                    Module = GetDashboardModuleForAuditRow(result.Module, item),
                    StatusCode = GetIntProperty(item, "StatusCode"),
                    TotalRequests = GetIntProperty(item, "TotalRequests")
                });
            }
            return rows.Where(i => !string.IsNullOrWhiteSpace(i.Module)).ToList();
        }

        private async Task<List<AggregatedStatusCodeRow>> TryGetStatusCodeStatsLast24HoursByModuleFromQueryAsync(List<string> moduleOptions, string selectedModule)
        {
            var results = await TryInvokeAcrossAuditClientsWithSourceAsync(
                moduleOptions,
                selectedModule,
                "AuditLogsStatsHttpStatusCodesLast24HoursByModuleAsync");
            if (results.Count == 0)
                return new List<AggregatedStatusCodeRow>();

            var rows = new List<AggregatedStatusCodeRow>();
            foreach (var result in results)
            {
                var item = result.Row;
                rows.Add(new AggregatedStatusCodeRow
                {
                    Module = GetDashboardModuleForAuditRow(result.Module, item),
                    StatusCode = GetIntProperty(item, "StatusCode"),
                    TotalRequests = GetIntProperty(item, "TotalRequests")
                });
            }

            return rows.Where(i => !string.IsNullOrWhiteSpace(i.Module)).ToList();
        }

        private static List<StatusCodeStatViewModel> BuildStatusCodeStats(List<AggregatedStatusCodeRow> rows)
        {
            return rows
                .GroupBy(i => i.StatusCode)
                .OrderBy(g => g.Key)
                .Select(g => new StatusCodeStatViewModel
                {
                    StatusCode = g.Key,
                    TotalRequests = g.Sum(x => x.TotalRequests)
                })
                .ToList();
        }

        private async Task<List<DailyRequestStatViewModel>> TryGetDailyStatsFromQueryAsync(List<string> moduleOptions, string selectedModule)
        {
            var results = await TryInvokeAcrossAuditClientsAsync(
                moduleOptions,
                selectedModule,
                "AuditLogsStatsDailyHttpRequestsByDayAsync");
            var enumerable = ExtractEnumerable(results);
            if (enumerable == null)
            {
                DashboardDebug("Daily duration query returned null/empty enumerable.");
                return new List<DailyRequestStatViewModel>();
            }

            var rows = new List<DailyRequestStatViewModel>();
            foreach (var item in enumerable)
            {
                var requestDay = GetStringProperty(item, "RequestDay");
                if (string.IsNullOrWhiteSpace(requestDay))
                    requestDay = GetStringProperty(item, "Timestamp");
                requestDay = NormalizeOrDefaultRequestDayKey(requestDay);

                rows.Add(new DailyRequestStatViewModel
                {
                    RequestDay = requestDay,
                    TotalRequests = GetIntProperty(item, "TotalRequests"),
                    AvgDurationMs = GetDoubleProperty(item, "AvgDurationMs"),
                    MaxDurationMs = GetLongProperty(item, "MaxDurationMs"),
                    MinDurationMs = GetLongProperty(item, "MinDurationMs")
                });
            }

            if (rows.Count > 0)
            {
                var sample = rows[0];
                DashboardDebug(
                    $"Daily duration raw rows={rows.Count}, sample day={sample.RequestDay}, total={sample.TotalRequests}, avgMs={sample.AvgDurationMs}, maxMs={sample.MaxDurationMs}, minMs={sample.MinDurationMs}");
            }
            else
            {
                DashboardDebug("Daily duration query returned zero rows after mapping.");
            }

            var aggregated = new List<DailyRequestStatViewModel>();
            foreach (var g in rows.GroupBy(i => i.RequestDay, StringComparer.OrdinalIgnoreCase))
            {
                var total = g.Sum(x => x.TotalRequests);
                var weightedAvg = total > 0 ? g.Sum(x => x.AvgDurationMs * x.TotalRequests) / total : 0;
                var min = g.Where(x => x.MinDurationMs > 0).Select(x => x.MinDurationMs).DefaultIfEmpty(0).Min();
                aggregated.Add(new DailyRequestStatViewModel
                {
                    RequestDay = g.Key,
                    TotalRequests = total,
                    AvgDurationMs = weightedAvg,
                    MaxDurationMs = g.Select(x => x.MaxDurationMs).DefaultIfEmpty(0).Max(),
                    MinDurationMs = min
                });
            }

            return aggregated
                .OrderByDescending(i => i.RequestDay)
                .ToList();
        }

        private async Task<List<ModuleTotalRequestViewModel>> TryGetModuleTotalsFromQueryAsync(List<string> moduleOptions, string selectedModule)
        {
            var results = await TryInvokeAcrossAuditClientsWithSourceAsync(
                moduleOptions,
                selectedModule,
                "AuditLogsStatsTotalHttpRequestsByModuleAsync");
            if (results.Count == 0)
                return new List<ModuleTotalRequestViewModel>();

            var rows = new List<ModuleTotalRequestViewModel>();
            foreach (var result in results)
            {
                var item = result.Row;
                rows.Add(new ModuleTotalRequestViewModel
                {
                    Module = GetDashboardModuleForAuditRow(result.Module, item),
                    TotalRequests = GetIntProperty(item, "TotalRequests")
                });
            }

            return rows.Where(i => !string.IsNullOrWhiteSpace(i.Module)).ToList();
        }

        private async Task<List<AggregatedTopServiceRow>> TryGetTopServicesByModuleFromQueryAsync(List<string> moduleOptions, string selectedModule)
        {
            var results = await TryInvokeAcrossAuditClientsWithSourceAsync(
                moduleOptions,
                selectedModule,
                "AuditLogsStatsTopHttpServicesByModuleAsync");
            if (results.Count == 0)
                return new List<AggregatedTopServiceRow>();

            var rows = new List<AggregatedTopServiceRow>();
            foreach (var result in results)
            {
                var item = result.Row;
                rows.Add(new AggregatedTopServiceRow
                {
                    Module = GetDashboardModuleForAuditRow(result.Module, item),
                    Method = GetStringProperty(item, "Action"),
                    Path = GetStringProperty(item, "RequestPath"),
                    TotalRequests = GetIntProperty(item, "TotalRequests")
                });
            }
            return rows
                .Where(i => !string.IsNullOrWhiteSpace(i.Module))
                .Where(i => !string.IsNullOrWhiteSpace(i.Path))
                .Where(i => !IsDashboardExcludedServicePath(i.Path))
                .ToList();
        }

        private static bool IsDashboardExcludedServicePath(string? path)
        {
            if (string.IsNullOrWhiteSpace(path))
                return true;

            var value = path.Trim();
            if (value.Length == 0)
                return true;

            // Normalize "/hc/" -> "/hc"
            if (value.Length > 1 && value.EndsWith('/'))
                value = value.TrimEnd('/');

            return value.Equals("/hc", StringComparison.OrdinalIgnoreCase)
                   || value.StartsWith("/hc/", StringComparison.OrdinalIgnoreCase)
                   || value.StartsWith("/hc-", StringComparison.OrdinalIgnoreCase)
                   || value.Equals("/health", StringComparison.OrdinalIgnoreCase)
                   || value.StartsWith("/health/", StringComparison.OrdinalIgnoreCase)
                   || value.StartsWith("/healthz", StringComparison.OrdinalIgnoreCase)
                   || value.Equals("/ready", StringComparison.OrdinalIgnoreCase)
                   || value.Equals("/live", StringComparison.OrdinalIgnoreCase)
                   || value.Equals("/alive", StringComparison.OrdinalIgnoreCase);
        }

        private async Task<object> TryInvokeAcrossAuditClientsAsync(List<string> moduleOptions, string selectedModule, params string[] methodNames)
        {
            var rows = await TryInvokeAcrossAuditClientsWithSourceAsync(moduleOptions, selectedModule, methodNames);
            return rows.Select(i => i.Row).ToList();
        }

        private static readonly SemaphoreSlim AuditOutboundGate = new(8, 8);

        private async Task<List<AuditLogClientResultRow>> TryInvokeAcrossAuditClientsWithSourceAsync(List<string> moduleOptions, string selectedModule, params string[] methodNames)
        {
            var clients = GetAuditLogClientsForSelection(moduleOptions, selectedModule);
            DashboardDebug($"Invoking audit clients. Selected={selectedModule}, ClientCount={clients.Count}, Methods=[{string.Join(", ", methodNames)}]");

            var clientTasks = clients.Select(async client =>
            {
                var rows = new List<AuditLogClientResultRow>();
                await AuditOutboundGate.WaitAsync().ConfigureAwait(false);
                try
                {
                    DashboardDebug($"Calling client={client.Client.GetType().Name}, module={client.Module}");
                    var results = await TryInvokeFirstAvailableAsync(client.Client, new List<string> { client.Module }, methodNames)
                        .ConfigureAwait(false);
                    var enumerable = ExtractEnumerable(results);
                    if (enumerable == null)
                    {
                        DashboardDebug($"Client={client.Client.GetType().Name} returned null enumerable.");
                        return rows;
                    }

                    foreach (var item in enumerable.Cast<object>())
                    {
                        rows.Add(new AuditLogClientResultRow
                        {
                            Module = client.Module,
                            Row = item
                        });
                    }

                    DashboardDebug($"Client={client.Client.GetType().Name} mapped row count={rows.Count}");
                }
                catch (Exception ex)
                {
                    // Best-effort aggregation: one failing module must not break the whole dashboard.
                    DashboardDebug($"Client={client.Client.GetType().Name} failed: {ex.GetType().Name} - {ex.Message}");
                }
                finally
                {
                    AuditOutboundGate.Release();
                }

                return rows;
            });

            var batches = await Task.WhenAll(clientTasks).ConfigureAwait(false);
            var merged = batches.SelectMany(i => i).ToList();
            DashboardDebug($"Merged row count={merged.Count}");
            return merged;
        }

        private async Task<object> TryInvokeFirstAvailableAsync(object target, List<string> moduleOptions = null, params string[] methodNames)
        {
            var type = target.GetType();
            foreach (var methodName in methodNames)
            {
                var method = type.GetMethods()
                    .Where(m => string.Equals(m.Name, methodName, StringComparison.Ordinal))
                    .OrderBy(m => m.GetParameters().Length)
                    .FirstOrDefault();
                if (method == null)
                {
                    DashboardDebug($"Method not found. Client={type.Name}, Method={methodName}");
                    continue;
                }

                DashboardDebug($"Invoking method. Client={type.Name}, Method={method.Name}, Parameters=[{string.Join(", ", method.GetParameters().Select(p => $"{p.ParameterType.Name} {p.Name}"))}]");

                var requiredStringParams = method.GetParameters()
                    .Where(p => p.ParameterType == typeof(string) && !p.HasDefaultValue)
                    .ToList();

                if (requiredStringParams.Count > 0 && moduleOptions != null)
                {
                    var mergedResults = new List<object>();
                    var modules = moduleOptions
                        .Where(m => !IsAllModules(m))
                        .Distinct(StringComparer.OrdinalIgnoreCase)
                        .ToList();

                    foreach (var module in modules)
                    {
                        var candidates = BuildModuleFilterCandidates(module);
                        foreach (var candidate in candidates)
                        {
                            var args = BuildInvokeArgs(method, candidate);
                            if (method.Invoke(target, args) is not Task candidateTask)
                                continue;

                            await candidateTask.ConfigureAwait(false);
                            var candidateResult = candidateTask.GetType().GetProperty("Result")?.GetValue(candidateTask);
                            var candidateEnumerable = ExtractEnumerable(candidateResult);
                            if (candidateEnumerable != null)
                            {
                                var candidateList = candidateEnumerable.Cast<object>().ToList();
                                if (candidateList.Count == 0)
                                    continue;

                                mergedResults.AddRange(candidateList);
                                break;
                            }
                        }
                    }

                    return mergedResults;
                }

                var defaultArgs = BuildInvokeArgs(method, string.Empty);
                if (method.Invoke(target, defaultArgs) is not Task task)
                    continue;

                await task.ConfigureAwait(false);
                return task.GetType().GetProperty("Result")?.GetValue(task);
            }

            return null;
        }

        private static object[] BuildInvokeArgs(System.Reflection.MethodInfo method, string stringValue)
        {
            return method.GetParameters()
                .Select(p =>
                {
                    if (p.ParameterType == typeof(string))
                    {
                        if (p.HasDefaultValue) return p.DefaultValue;
                        return stringValue ?? string.Empty;
                    }

                    if (p.ParameterType == typeof(System.Threading.CancellationToken))
                        return System.Threading.CancellationToken.None;

                    return p.HasDefaultValue ? p.DefaultValue : null;
                })
                .ToArray();
        }

        private static List<string> BuildModuleFilterCandidates(string moduleLabel)
        {
            if (string.IsNullOrWhiteSpace(moduleLabel))
                return new List<string> { string.Empty };

            var trimmed = moduleLabel.Trim();
            var kebab = trimmed.ToLowerInvariant().Replace(" ", "-");
            var candidates = new List<string>
            {
                trimmed,
                trimmed.ToLowerInvariant(),
                kebab,
                kebab.EndsWith("-module", StringComparison.OrdinalIgnoreCase) ? kebab : $"{kebab}-module"
            };

            return candidates
                .Where(c => !string.IsNullOrWhiteSpace(c))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        private static readonly object AuditLogClientInterfaceTypesLock = new();
        private static List<Type> _auditLogClientInterfaceTypes;

        private static List<Type> GetAuditLogClientInterfaceTypes()
        {
            if (_auditLogClientInterfaceTypes != null)
                return _auditLogClientInterfaceTypes;

            lock (AuditLogClientInterfaceTypesLock)
            {
                if (_auditLogClientInterfaceTypes != null)
                    return _auditLogClientInterfaceTypes;

                _auditLogClientInterfaceTypes = AppDomain.CurrentDomain.GetAssemblies()
                    .SelectMany(a =>
                    {
                        try { return a.GetTypes(); }
                        catch (ReflectionTypeLoadException ex) { return ex.Types.Where(t => t != null)!; }
                    })
                    .Where(t => t != null && t.IsInterface && t.Name == "IAuditLogsClient")
                    .ToList();
            }

            return _auditLogClientInterfaceTypes;
        }

        private List<AuditLogClientEntry> GetAuditLogClientsForSelection(List<string> moduleOptions, string selectedModule)
        {
            var all = new List<AuditLogClientEntry>();
            foreach (var interfaceType in GetAuditLogClientInterfaceTypes())
            {
                // Best practice: resolve all registrations for a contract.
                // GetService returns only one instance and can silently hide others.
                var services = _serviceProvider.GetServices(interfaceType).Cast<object>().ToList();
                if (services.Count == 0)
                {
                    var fallback = _serviceProvider.GetService(interfaceType);
                    if (fallback != null)
                        services.Add(fallback);
                }

                foreach (var service in services)
                {
                    var module = ExtractModuleNameFromAuditClientType(service.GetType());
                    all.Add(new AuditLogClientEntry { Module = module, Client = service });
                }
            }

            if (all.Count == 0 && _auditLogsClient != null)
                all.Add(new AuditLogClientEntry { Module = "Identity", Client = _auditLogsClient });

            all = all
                .GroupBy(i => $"{i.Module}|{i.Client.GetType().FullName}", StringComparer.OrdinalIgnoreCase)
                .Select(g => g.First())
                .ToList();

            if (IsAllModules(selectedModule))
                return all;

            var selectedLabel = ToSidebarModuleLabel(selectedModule);
            return all
                .Where(i => IsSameModule(i.Module, selectedLabel))
                .ToList();
        }

        private static string ExtractModuleNameFromAuditClientType(Type type)
        {
            var ns = type.Namespace ?? string.Empty;
            var clientsIdx = ns.IndexOf(".Clients.", StringComparison.OrdinalIgnoreCase);
            var apiIdx = ns.IndexOf("Api.Contracts", StringComparison.OrdinalIgnoreCase);
            if (clientsIdx >= 0 && apiIdx > clientsIdx)
            {
                var raw = ns.Substring(clientsIdx + ".Clients.".Length, apiIdx - (clientsIdx + ".Clients.".Length));
                return ToSidebarModuleLabel(raw);
            }

            if (clientsIdx >= 0)
            {
                var raw = ns[(clientsIdx + ".Clients.".Length)..]
                    .Split('.', StringSplitOptions.RemoveEmptyEntries)
                    .FirstOrDefault() ?? string.Empty;
                if (raw.EndsWith("Api", StringComparison.OrdinalIgnoreCase))
                    raw = raw[..^3];
                return ToSidebarModuleLabel(raw);
            }

            return "Identity";
        }

        private static JsonDocument TryParseJson(string json)
        {
            if (string.IsNullOrWhiteSpace(json))
                return null;
            try
            {
                return JsonDocument.Parse(json);
            }
            catch
            {
                return null;
            }
        }

        private static string ReadJsonString(JsonDocument root, string propertyName)
        {
            if (root != null && root.RootElement.TryGetProperty(propertyName, out var property))
                return property.ToString();
            return string.Empty;
        }

        private static int ReadJsonInt(JsonDocument root, string propertyName)
        {
            if (root != null && root.RootElement.TryGetProperty(propertyName, out var property))
            {
                if (property.ValueKind == JsonValueKind.Number && property.TryGetInt32(out var intValue))
                    return intValue;
                if (int.TryParse(property.ToString(), out var parsed))
                    return parsed;
            }
            return 0;
        }

        private static string GetStringProperty(object source, string propertyName)
            => GetPropertyValue(source, propertyName)?.ToString() ?? string.Empty;

        private static string GetRequestHourValue(object source)
        {
            foreach (var propertyName in new[]
                     {
                         "RequestHour",
                         "REQUEST_HOUR",
                         "Request_Hour",
                         "AuditLogRequestHour",
                         "AuditLogRequest_Hour",
                         "Timestamp",
                         "TIMESTAMP"
                     })
            {
                var value = GetStringProperty(source, propertyName);
                if (!string.IsNullOrWhiteSpace(value))
                    return value;
            }

            foreach (var candidate in EnumerateScalarProperties(source))
            {
                var key = NormalizePropertyKey(candidate.Key);
                if (!key.Contains("hour") && !key.Contains("timestamp") && !key.Contains("time"))
                    continue;

                if (IsDateTimeLikeValue(candidate.Value))
                    return candidate.Value;
            }

            return string.Empty;
        }

        private static List<KeyValuePair<string, string>> EnumerateScalarProperties(object source)
        {
            var values = new List<KeyValuePair<string, string>>();
            if (source == null)
                return values;

            if (source is IDictionary dictionary)
            {
                foreach (DictionaryEntry entry in dictionary)
                {
                    if (entry.Value != null)
                        values.Add(new KeyValuePair<string, string>(entry.Key?.ToString() ?? string.Empty, entry.Value.ToString()));
                }
            }

            if (source is JsonElement jsonElement && jsonElement.ValueKind == JsonValueKind.Object)
            {
                foreach (var property in jsonElement.EnumerateObject())
                    values.Add(new KeyValuePair<string, string>(property.Name, property.Value.ToString()));
            }

            foreach (var property in source.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                if (property.GetIndexParameters().Length > 0)
                    continue;

                object value;
                try
                {
                    value = property.GetValue(source);
                }
                catch
                {
                    continue;
                }

                if (value != null)
                    values.Add(new KeyValuePair<string, string>(property.Name, value.ToString()));
            }

            try
            {
                using var json = JsonDocument.Parse(JsonSerializer.Serialize(source));
                if (json.RootElement.ValueKind == JsonValueKind.Object)
                {
                    foreach (var property in json.RootElement.EnumerateObject())
                        values.Add(new KeyValuePair<string, string>(property.Name, property.Value.ToString()));
                }
            }
            catch
            {
                // Best effort only; callers fall back to an empty value.
            }

            return values;
        }

        private static bool IsDateTimeLikeValue(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return false;

            return DateTime.TryParse(value, CultureInfo.InvariantCulture, DateTimeStyles.None, out _) ||
                   DateTime.TryParse(value, CultureInfo.CurrentCulture, DateTimeStyles.None, out _) ||
                   DateTimeOffset.TryParse(value, CultureInfo.InvariantCulture, DateTimeStyles.None, out _) ||
                   DateTimeOffset.TryParse(value, CultureInfo.CurrentCulture, DateTimeStyles.None, out _);
        }

        private static string GetPropertyNamesForDebug(object source)
        {
            return string.Join(", ", EnumerateScalarProperties(source)
                .Select(i => i.Key)
                .Where(i => !string.IsNullOrWhiteSpace(i))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .Take(20));
        }

        private static string GetDashboardModuleForAuditRow(string sourceModule, object row)
        {
            if (!string.IsNullOrWhiteSpace(sourceModule))
                return ToSidebarModuleLabel(sourceModule);

            return ToSidebarModuleLabel(GetStringProperty(row, "RequestModule"));
        }

        private static int GetIntProperty(object source, string propertyName)
        {
            var value = GetPropertyValue(source, propertyName);
            if (value == null) return 0;
            if (value is int i) return i;
            if (value is long l) return l > int.MaxValue ? int.MaxValue : (int)l;
            if (value is double d) return (int)Math.Round(d, MidpointRounding.AwayFromZero);
            if (value is decimal m) return (int)Math.Round(m, MidpointRounding.AwayFromZero);
            var text = value.ToString();
            if (int.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsedInvariant))
                return parsedInvariant;
            if (decimal.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsedDecimalInvariant))
                return (int)Math.Round(parsedDecimalInvariant, MidpointRounding.AwayFromZero);
            if (int.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out var parsedCurrent))
                return parsedCurrent;
            if (decimal.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out var parsedDecimalCurrent))
                return (int)Math.Round(parsedDecimalCurrent, MidpointRounding.AwayFromZero);
            return 0;
        }

        private static long GetLongProperty(object source, string propertyName)
        {
            var value = GetPropertyValue(source, propertyName);
            if (value == null) return 0;
            if (value is long l) return l;
            if (value is int i) return i;
            if (value is double d) return (long)Math.Round(d, MidpointRounding.AwayFromZero);
            if (value is decimal m) return (long)Math.Round(m, MidpointRounding.AwayFromZero);
            var text = value.ToString();
            if (long.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsedInvariant))
                return parsedInvariant;
            if (decimal.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsedDecimalInvariant))
                return (long)Math.Round(parsedDecimalInvariant, MidpointRounding.AwayFromZero);
            if (long.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out var parsedCurrent))
                return parsedCurrent;
            if (decimal.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out var parsedDecimalCurrent))
                return (long)Math.Round(parsedDecimalCurrent, MidpointRounding.AwayFromZero);
            return 0;
        }

        private static double GetDoubleProperty(object source, string propertyName)
        {
            var value = GetPropertyValue(source, propertyName);
            if (value == null) return 0;
            if (value is double d) return d;
            if (value is decimal m) return (double)m;
            if (value is int i) return i;
            if (value is long l) return l;
            var text = value.ToString();
            if (double.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsedInvariant))
                return parsedInvariant;
            if (double.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out var parsedCurrent))
                return parsedCurrent;
            return 0;
        }

        private static DateTime GetDateTimeProperty(object source, string propertyName)
        {
            var value = GetPropertyValue(source, propertyName);
            if (value is DateTime dt) return dt;
            return DateTime.TryParse(value?.ToString(), out var parsed) ? parsed : DateTime.MinValue;
        }

        private static bool GetBoolProperty(object source, string propertyName)
        {
            var value = GetPropertyValue(source, propertyName);
            if (value is bool b) return b;
            return bool.TryParse(value?.ToString(), out var parsed) && parsed;
        }

        private static int? GetNullableIntProperty(object source, string propertyName)
        {
            var value = GetPropertyValue(source, propertyName);
            if (value == null) return null;
            if (value is int i) return i;
            if (value is long l) return l > int.MaxValue ? int.MaxValue : (int)l;
            return int.TryParse(value.ToString(), out var parsed) ? parsed : null;
        }

        private static object GetPropertyValue(object source, string propertyName)
        {
            var type = source.GetType();
            var prop = type.GetProperty(propertyName)
                       ?? type.GetProperties().FirstOrDefault(p =>
                           string.Equals(p.Name, propertyName, StringComparison.OrdinalIgnoreCase))
                       ?? type.GetProperties().FirstOrDefault(p =>
                           NormalizePropertyKey(p.Name) == NormalizePropertyKey(propertyName));
            if (prop != null)
                return prop.GetValue(source);

            if (source is IDictionary dictionary)
            {
                foreach (DictionaryEntry entry in dictionary)
                {
                    if (NormalizePropertyKey(entry.Key?.ToString()) == NormalizePropertyKey(propertyName))
                        return entry.Value;
                }
            }

            // Last-resort fallback for anonymous/wrapped response shapes.
            // This keeps dashboard mapping resilient to naming/casing differences in generated DTOs.
            try
            {
                using var json = JsonDocument.Parse(JsonSerializer.Serialize(source));
                if (json.RootElement.ValueKind == JsonValueKind.Object)
                {
                    foreach (var item in json.RootElement.EnumerateObject())
                    {
                        if (NormalizePropertyKey(item.Name) != NormalizePropertyKey(propertyName))
                            continue;

                        return item.Value.ValueKind switch
                        {
                            JsonValueKind.Number when item.Value.TryGetInt64(out var l) => l,
                            JsonValueKind.Number when item.Value.TryGetDouble(out var d) => d,
                            JsonValueKind.String => item.Value.GetString(),
                            JsonValueKind.True => true,
                            JsonValueKind.False => false,
                            _ => item.Value.ToString()
                        };
                    }
                }
            }
            catch
            {
                // Intentionally swallow: getter should fail soft and return null.
            }

            return null;
        }

        private bool IsDashboardDebugEnabled()
        {
            var raw = Request?.Query["dashboardDebug"].ToString();
            return string.Equals(raw, "1", StringComparison.OrdinalIgnoreCase) ||
                   string.Equals(raw, "true", StringComparison.OrdinalIgnoreCase);
        }

        private void DashboardDebug(string message)
        {
            if (!IsDashboardDebugEnabled())
                return;

            Console.WriteLine($"[DashboardDebug] {DateTime.UtcNow:O} {message}");
        }

        private static string NormalizePropertyKey(string key)
            => new string((key ?? string.Empty).Where(char.IsLetterOrDigit).ToArray()).ToLowerInvariant();

        private static IEnumerable ExtractEnumerable(object result)
        {
            if (result == null) return null;
            if (result is string) return null;
            if (result is IEnumerable direct) return direct;

            var type = result.GetType();
            foreach (var candidate in new[] { "Items", "List", "Data", "Result" })
            {
                var prop = type.GetProperty(candidate);
                var value = prop?.GetValue(result);
                if (value is IEnumerable enumerable && value is not string)
                    return enumerable;
            }

            return null;
        }

        private static async Task<int> TryGetUsersCountAsync(IAspNetUsersClient client)
        {
            // Preferred: direct count-style methods.
            foreach (var methodName in new[] { "AspNetUsersCountAsync", "CountAsync" })
            {
                var result = await TryInvokeMethodAsync(client, methodName).ConfigureAwait(false);
                if (result is int i) return i;
                if (result is long l) return l > int.MaxValue ? int.MaxValue : (int)l;
            }

            // Fallback: list/get methods with optional args.
            foreach (var methodName in new[] { "AspNetUsersListAsync", "AspNetUsersGetAsync", "GetAllAsync" })
            {
                var result = await TryInvokeMethodAsync(client, methodName).ConfigureAwait(false);
                if (result is IEnumerable enumerable)
                {
                    var count = 0;
                    foreach (var _ in enumerable) count++;
                    if (count > 0) return count;
                }
            }

            return 0;
        }

        private static async Task<object> TryInvokeMethodAsync(object target, string methodName)
        {
            var method = target.GetType().GetMethods()
                .Where(m => string.Equals(m.Name, methodName, StringComparison.Ordinal))
                .OrderBy(m => m.GetParameters().Length)
                .FirstOrDefault();
            if (method == null) return null;

            var args = method.GetParameters()
                .Select(p => p.HasDefaultValue ? p.DefaultValue : null)
                .ToArray();

            if (method.Invoke(target, args) is not Task task)
                return null;

            await task.ConfigureAwait(false);
            return task.GetType().GetProperty("Result")?.GetValue(task);
        }

        private static List<DailyRequestStatViewModel> EnsureLast7DaysStats(List<DailyRequestStatViewModel> source)
        {
            var map = source
                .Where(x => !string.IsNullOrWhiteSpace(x.RequestDay))
                .GroupBy(x => x.RequestDay)
                .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

            var normalized = new List<DailyRequestStatViewModel>();
            for (var dayOffset = 6; dayOffset >= 0; dayOffset--)
            {
                var day = DateTime.UtcNow.Date.AddDays(-dayOffset);
                var key = day.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
                if (map.TryGetValue(key, out var item))
                {
                    normalized.Add(item);
                    continue;
                }

                normalized.Add(new DailyRequestStatViewModel
                {
                    RequestDay = key,
                    TotalRequests = 0,
                    AvgDurationMs = 0,
                    MaxDurationMs = 0,
                    MinDurationMs = 0
                });
            }

            return normalized;
        }

        private static List<DailyRequestStatViewModel> BuildDailyRequestStatsFromModuleRows(List<AggregatedDailyStatRow> dailyByModuleRows)
        {
            return EnsureLast7DaysStats((dailyByModuleRows ?? new List<AggregatedDailyStatRow>())
                .GroupBy(i => i.RequestDay)
                .OrderByDescending(g => g.Key)
                .Select(g =>
                {
                    var totalRequests = g.Sum(x => x.TotalRequests);
                    var weightedDuration = totalRequests > 0
                        ? g.Sum(x => x.AvgDurationMs * x.TotalRequests) / totalRequests
                        : 0;
                    var minDuration = g.Where(x => x.MinDurationMs > 0).Select(x => x.MinDurationMs).DefaultIfEmpty(0).Min();
                    return new DailyRequestStatViewModel
                    {
                        RequestDay = g.Key,
                        TotalRequests = totalRequests,
                        AvgDurationMs = weightedDuration,
                        MaxDurationMs = g.Select(x => x.MaxDurationMs).DefaultIfEmpty(0).Max(),
                        MinDurationMs = minDuration
                    };
                })
                .ToList());
        }

        private async Task<List<string>> GetSidebarModuleOptionsAsync()
        {
            try
            {
                var menuItems = await PortalMenuListLoader.LoadAllAsync(_portalMenusClient, HttpContext);
                var modules = menuItems
                    .Where(i =>
                        !string.IsNullOrWhiteSpace(i.ParentName) &&
                        i.ParentName.Trim().EndsWith("Module", StringComparison.OrdinalIgnoreCase) &&
                        !string.Equals(i.Name, "AuditLogs", StringComparison.OrdinalIgnoreCase))
                    .Select(i => ToSidebarModuleLabel(i.ParentName))
                    .Where(i => !string.IsNullOrWhiteSpace(i))
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .OrderBy(i => i)
                    .ToList();
                modules.Insert(0, "All Modules");
                return modules;
            }
            catch
            {
                return new List<string> { "All Modules" };
            }
        }

        private async Task<List<DashboardQuickLinkViewModel>> GetDashboardManagementQuickLinksAsync()
        {
            try
            {
                var menuItems = await PortalMenuListLoader.LoadAllAsync(_portalMenusClient, HttpContext);
                var parentKeys = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
                {
                    "AccessGrantManagers",
                    "WorkflowManagers"
                };

                var quickLinks = menuItems
                    .Where(i => !string.IsNullOrWhiteSpace(i.ActionName))
                    .Where(i => parentKeys.Contains(i.ParentName?.Trim() ?? string.Empty))
                    .OrderBy(i => i.ParentName)
                    .ThenBy(i => i.Text)
                    .Select(i => new DashboardQuickLinkViewModel
                    {
                        Group = string.Equals(i.ParentName, "WorkflowManagers", StringComparison.OrdinalIgnoreCase)
                            ? "Workflow Managers"
                            : "Access Grant Managers",
                        Title = ToDashboardQuickLinkTitle(i.Text ?? i.Name),
                        Description = ToDashboardQuickLinkDescription(i.Text ?? i.Name, i.ParentName),
                        Url = i.ActionName,
                        IconCss = string.Equals(i.ParentName, "WorkflowManagers", StringComparison.OrdinalIgnoreCase)
                            ? "fa-project-diagram"
                            : "fa-user-shield"
                    })
                    .ToList();

                var auditLogItem = menuItems
                    .Where(i => !string.IsNullOrWhiteSpace(i.ActionName))
                    .Where(i => string.Equals(i.Name, "AuditLogs", StringComparison.OrdinalIgnoreCase))
                    .OrderBy(i => i.ParentName)
                    .FirstOrDefault();
                if (auditLogItem != null && quickLinks.Count < 4)
                {
                    quickLinks.Add(new DashboardQuickLinkViewModel
                    {
                        Group = "Audit Logs",
                        Title = "Audit Logs",
                        Description = "Review request history",
                        Url = auditLogItem.ActionName,
                        IconCss = "fa-clipboard-list"
                    });
                }

                return quickLinks;
            }
            catch
            {
                return new List<DashboardQuickLinkViewModel>();
            }
        }

        private static string ToDashboardQuickLinkTitle(string text)
        {
            var normalized = ToDashboardLinkText(text);
            var key = NormalizePropertyKey(normalized);

            return key switch
            {
                "apimethodaccessgrantmanager" => "Api Method Grants",
                "portalpageaccessgrantmanager" => "Portal Page Grants",
                _ => normalized
                    .Replace(" Manager", string.Empty, StringComparison.OrdinalIgnoreCase)
                    .Replace(" Management", string.Empty, StringComparison.OrdinalIgnoreCase)
            };
        }

        private static string ToDashboardQuickLinkDescription(string text, string parentName)
        {
            var key = NormalizePropertyKey(text);
            if (key.Contains("apimethodaccessgrant"))
                return "Manage API permissions";
            if (key.Contains("portalpageaccessgrant"))
                return "Manage page permissions";
            if (string.Equals(parentName, "WorkflowManagers", StringComparison.OrdinalIgnoreCase))
                return "Manage workflow steps";

            return "Open manager page";
        }

        private static string ToDashboardLinkText(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
                return string.Empty;

            var normalized = text.Replace("_", " ").Replace("-", " ").Trim();
            var sb = new StringBuilder();
            for (var i = 0; i < normalized.Length; i++)
            {
                var c = normalized[i];
                if (i > 0 && char.IsUpper(c) && !char.IsWhiteSpace(normalized[i - 1]) && !char.IsUpper(normalized[i - 1]))
                    sb.Append(' ');
                sb.Append(c);
            }

            return CultureInfo.InvariantCulture.TextInfo.ToTitleCase(sb.ToString().ToLowerInvariant()).Trim();
        }

        private static bool IsAllModules(string moduleName)
            => string.IsNullOrWhiteSpace(moduleName) ||
               string.Equals(moduleName.Trim(), "All Modules", StringComparison.OrdinalIgnoreCase);

        private static bool IsSameModule(string left, string right)
        {
            if (IsAllModules(left) && IsAllModules(right))
                return true;

            return string.Equals(
                NormalizePropertyKey(ToSidebarModuleLabel(left)),
                NormalizePropertyKey(ToSidebarModuleLabel(right)),
                StringComparison.OrdinalIgnoreCase);
        }

        private static string ToSidebarModuleLabel(string moduleName)
        {
            if (string.IsNullOrWhiteSpace(moduleName))
                return string.Empty;

            var normalized = moduleName.Trim();
            normalized = normalized.Replace("_", " ").Replace("-", " ");
            normalized = string.Join(" ", normalized
                .Split(' ', StringSplitOptions.RemoveEmptyEntries));

            if (normalized.EndsWith(" Module", StringComparison.OrdinalIgnoreCase))
                normalized = normalized[..^7];
            else if (normalized.EndsWith("Module", StringComparison.OrdinalIgnoreCase))
                normalized = normalized[..^6];

            var sb = new StringBuilder();
            for (var i = 0; i < normalized.Length; i++)
            {
                var c = normalized[i];
                if (i > 0 && char.IsUpper(c) && !char.IsUpper(normalized[i - 1]))
                    sb.Append(' ');
                sb.Append(c);
            }

            var baseName = sb.ToString().Trim();
            if (string.IsNullOrWhiteSpace(baseName))
                return string.Empty;

            var key = baseName.Replace(" ", string.Empty).ToLowerInvariant();
            if (key is "auth" or "identity")
                baseName = "Identity";

            var textInfo = CultureInfo.InvariantCulture.TextInfo;
            var titleCaseName = textInfo.ToTitleCase(baseName.ToLowerInvariant()).Trim();
            return $"{titleCaseName} Module";
        }

        private static List<ModuleDailyRequestSeriesViewModel> BuildModuleDailySeries(
            List<AggregatedDailyStatRow> dailyByModuleRows,
            List<string> last7DayKeys,
            string selectedModule,
            List<string> moduleOptions)
        {
            var series = dailyByModuleRows
                .Where(i => !string.IsNullOrWhiteSpace(i.Module))
                .GroupBy(i => i.Module, StringComparer.OrdinalIgnoreCase)
                .Select(g => new ModuleDailyRequestSeriesViewModel
                {
                    Module = g.Key,
                    DailyTotals = last7DayKeys
                        .Select(day => g.Where(x => string.Equals(x.RequestDay, day, StringComparison.OrdinalIgnoreCase)).Sum(x => x.TotalRequests))
                        .ToList()
                })
                .OrderByDescending(i => i.DailyTotals.Sum())
                .ThenBy(i => i.Module)
                .ToList();

            var sidebarModules = (moduleOptions ?? new List<string>())
                .Where(i => !string.IsNullOrWhiteSpace(i) && !IsAllModules(i))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            foreach (var module in sidebarModules)
            {
                if (series.Any(i => IsSameModule(i.Module, module)))
                    continue;

                series.Add(new ModuleDailyRequestSeriesViewModel
                {
                    Module = module,
                    DailyTotals = last7DayKeys.Select(_ => 0).ToList()
                });
            }

            series = series
                .OrderByDescending(i => i.DailyTotals.Sum())
                .ThenBy(i => i.Module)
                .ToList();

            if (!IsAllModules(selectedModule))
            {
                return series
                    .Where(i => IsSameModule(i.Module, selectedModule))
                    .ToList();
            }

            return series;
        }

        private static List<ModuleHourlyRequestSeriesViewModel> BuildModuleHourlySeries(
            List<AggregatedHourlyStatRow> hourlyByModuleRows,
            List<string> last24HourKeys,
            string selectedModule,
            List<string> moduleOptions)
        {
            var sourceRows = hourlyByModuleRows ?? new List<AggregatedHourlyStatRow>();
            var series = sourceRows
                .Where(i => !string.IsNullOrWhiteSpace(i.Module))
                .GroupBy(i => NormalizePropertyKey(ToSidebarModuleLabel(i.Module)), StringComparer.OrdinalIgnoreCase)
                .Select(g => new ModuleHourlyRequestSeriesViewModel
                {
                    Module = ToSidebarModuleLabel(g.First().Module),
                    HourlyTotals = last24HourKeys
                        .Select(hour => g.Where(x => string.Equals(x.RequestHour, hour, StringComparison.OrdinalIgnoreCase)).Sum(x => x.TotalRequests))
                        .ToList()
                })
                .OrderByDescending(i => i.HourlyTotals.Sum())
                .ThenBy(i => i.Module)
                .ToList();

            var sidebarModules = (moduleOptions ?? new List<string>())
                .Where(i => !string.IsNullOrWhiteSpace(i) && !IsAllModules(i))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            foreach (var module in sidebarModules)
            {
                if (series.Any(i => IsSameModule(i.Module, module)))
                    continue;

                series.Add(new ModuleHourlyRequestSeriesViewModel
                {
                    Module = module,
                    HourlyTotals = last24HourKeys.Select(_ => 0).ToList()
                });
            }

            series = series
                .OrderByDescending(i => i.HourlyTotals.Sum())
                .ThenBy(i => i.Module)
                .ToList();

            if (!IsAllModules(selectedModule))
            {
                return series
                    .Where(i => IsSameModule(i.Module, selectedModule))
                    .ToList();
            }

            return series;
        }

        private static List<ModuleTotalRequestViewModel> BuildModuleTotals(
            List<ModuleTotalRequestViewModel> source,
            List<string> moduleOptions,
            string selectedModule)
        {
            var merged = source
                .GroupBy(i => i.Module, StringComparer.OrdinalIgnoreCase)
                .Select(g => new ModuleTotalRequestViewModel
                {
                    Module = g.Key,
                    TotalRequests = g.Sum(x => x.TotalRequests)
                })
                .ToList();

            foreach (var module in moduleOptions.Where(i => !IsAllModules(i)))
            {
                if (merged.Any(i => IsSameModule(i.Module, module)))
                    continue;
                merged.Add(new ModuleTotalRequestViewModel { Module = module, TotalRequests = 0 });
            }

            if (!IsAllModules(selectedModule))
            {
                merged = merged
                    .Where(i => IsSameModule(i.Module, selectedModule))
                    .ToList();
            }

            return merged
                .OrderByDescending(i => i.TotalRequests)
                .ThenBy(i => i.Module)
                .ToList();
        }

        private static bool NeedsDailyFallback(List<AggregatedDailyStatRow> dailyRows, List<string> last7DayKeys)
        {
            if (dailyRows == null || dailyRows.Count == 0)
                return true;

            var keySet = new HashSet<string>(last7DayKeys, StringComparer.OrdinalIgnoreCase);
            return !dailyRows.Any(r => keySet.Contains(r.RequestDay));
        }

        private static List<AggregatedDailyStatRow> BuildDailyRowsFromModuleTotals(
            List<ModuleTotalRequestViewModel> moduleTotalsRows,
            string selectedModule)
        {
            var dayKey = DateTime.UtcNow.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
            var source = moduleTotalsRows ?? new List<ModuleTotalRequestViewModel>();

            if (!IsAllModules(selectedModule))
            {
                source = source
                    .Where(i => IsSameModule(i.Module, selectedModule))
                    .ToList();
            }

            return source
                .Where(i => !string.IsNullOrWhiteSpace(i.Module))
                .Select(i => new AggregatedDailyStatRow
                {
                    Module = i.Module,
                    RequestDay = dayKey,
                    TotalRequests = i.TotalRequests,
                    AvgDurationMs = 0,
                    MaxDurationMs = 0,
                    MinDurationMs = 0
                })
                .ToList();
        }

        private static string NormalizeRequestDayKey(string rawValue)
        {
            if (string.IsNullOrWhiteSpace(rawValue))
                return string.Empty;

            if (DateTime.TryParse(rawValue, out var parsed))
                return parsed.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);

            return rawValue.Length >= 10 ? rawValue[..10] : rawValue;
        }

        private static string NormalizeRequestHourKey(string rawValue)
        {
            if (string.IsNullOrWhiteSpace(rawValue))
                return string.Empty;

            if (TryParseUtcHourKey(rawValue, out var parsed))
                return parsed.ToString("yyyy-MM-dd HH:00:00", CultureInfo.InvariantCulture);

            return rawValue.Length >= 13 ? $"{rawValue[..13]}:00:00" : rawValue;
        }

        private static bool TryParseUtcHourKey(string rawValue, out DateTime utcHour)
        {
            utcHour = DateTime.MinValue;
            if (string.IsNullOrWhiteSpace(rawValue))
                return false;

            if (DateTime.TryParse(
                    rawValue,
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                    out var parsed))
            {
                utcHour = new DateTime(parsed.Year, parsed.Month, parsed.Day, parsed.Hour, 0, 0, DateTimeKind.Utc);
                return true;
            }

            return false;
        }

        private static string NormalizeOrDefaultRequestDayKey(string rawValue)
        {
            var normalized = NormalizeRequestDayKey(rawValue);
            if (!string.IsNullOrWhiteSpace(normalized))
                return normalized;

            // Some generated stats DTOs omit request-day field even when durations are present.
            // Default to today so KPI/charts don't collapse to all-zero due to empty day keys.
            return DateTime.UtcNow.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        }

        private sealed class AggregatedDailyStatRow
        {
            public string Module { get; set; } = string.Empty;
            public string RequestDay { get; set; } = string.Empty;
            public int TotalRequests { get; set; }
            public double AvgDurationMs { get; set; }
            public long MaxDurationMs { get; set; }
            public long MinDurationMs { get; set; }
        }

        private sealed class AggregatedHourlyStatRow
        {
            public string Module { get; set; } = string.Empty;
            public string RequestHour { get; set; } = string.Empty;
            public int TotalRequests { get; set; }
        }

        private sealed class AggregatedStatusCodeRow
        {
            public string Module { get; set; } = string.Empty;
            public int StatusCode { get; set; }
            public int TotalRequests { get; set; }
        }

        private sealed class AggregatedTopServiceRow
        {
            public string Module { get; set; } = string.Empty;
            public string Method { get; set; } = string.Empty;
            public string Path { get; set; } = string.Empty;
            public int TotalRequests { get; set; }
        }

        private sealed class AuditLogClientEntry
        {
            public string Module { get; set; } = string.Empty;
            public object Client { get; set; }
        }

        private sealed class AuditLogClientResultRow
        {
            public string Module { get; set; } = string.Empty;
            public object Row { get; set; }
        }
        
        public IActionResult Privacy()
        {
            return View("Privacy");
        }
    }
}
