// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Quickcode.Portal.Models;
using QuickCode.Quickcode.Portal.Models.IdentityModule;
using QuickCode.Quickcode.Portal.Helpers;
using QuickCode.Quickcode.Infrastructure.Integration.Models;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.Quickcode.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Quickcode.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Quickcode.Portal.Controllers.IdentityModule
{
    [Permission("IdentityModuleAuditLogs")]
    [Area("IdentityModule")]
    [Route("IdentityModuleAuditLogs")]
    public partial class AuditLogsController : BaseController
    {
        private readonly IdentityModuleContracts.IAuditLogsClient pageClient;
        public AuditLogsController(IdentityModuleContracts.IAuditLogsClient pageClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(AuditLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("ListPartial")]
        [HttpPost]
        public async Task<IActionResult> ListPartial(AuditLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return PartialView("_ListTable", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(AuditLogData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.AuditLogsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(AuditLogData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.AuditLogsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(AuditLogData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.AuditLogsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(AuditLogData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(AuditLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(AuditLogData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(AuditLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<AuditLogData> PrepareModel()
        {
            var model = GetModel<AuditLogData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<AuditLogData> PrepareModel(AuditLogData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            var result = await pageClient.AuditLogsListAsync(model.CurrentPage, model.PageSize, includeCount: true);
            model.NumberOfRecord = result?.TotalCount ?? 0;
            model.TotalPage = model.PageSize <= 0 ? 0 : (model.NumberOfRecord + model.PageSize - 1) / model.PageSize;
            if (model.TotalPage > 0 && model.CurrentPage > model.TotalPage)
            {
                model.CurrentPage = model.TotalPage;
                result = await pageClient.AuditLogsListAsync(model.CurrentPage, model.PageSize, includeCount: false);
            }

            model.List = result?.Items?.ToList() ?? new();
            return model;
        }

        [Route("Queries/GetRecentHttpRequests")]
        public async Task<IActionResult> QueryGetRecentHttpRequests()
        {
            var model = GetModel<AuditLogGetRecentHttpRequestsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryGetRecentHttpRequestsModel(model);
            return View("GetRecentHttpRequests", model);
        }

        [Route("Queries/GetRecentHttpRequests")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentHttpRequests(AuditLogGetRecentHttpRequestsData model)
        {
            model = await PrepareQueryGetRecentHttpRequestsModel(model);
            return View("GetRecentHttpRequests", model);
        }

        [Route("Queries/GetRecentHttpRequestsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentHttpRequestsPartial(AuditLogGetRecentHttpRequestsData model)
        {
            model = await PrepareQueryGetRecentHttpRequestsModel(model);
            return PartialView("_GetRecentHttpRequestsTable", model);
        }

        private async Task<AuditLogGetRecentHttpRequestsData> PrepareQueryGetRecentHttpRequestsModel(AuditLogGetRecentHttpRequestsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsGetRecentHttpRequestsAsync(pageNumber: model.CurrentPage, pageSize: model.PageSize);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                var hasMore = model.List.Count >= model.PageSize;
                var seen = ((model.CurrentPage - 1) * model.PageSize) + model.List.Count;
                model.NumberOfRecord = seen;
                model.TotalPage = hasMore ? model.CurrentPage + 1 : model.CurrentPage;
                model.HasMoreRecords = hasMore;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetRecentHttpRequestsByModule")]
        public async Task<IActionResult> QueryGetRecentHttpRequestsByModule()
        {
            var model = GetModel<AuditLogGetRecentHttpRequestsByModuleData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            return View("GetRecentHttpRequestsByModule", model);
        }

        [Route("Queries/GetRecentHttpRequestsByModule")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentHttpRequestsByModule(AuditLogGetRecentHttpRequestsByModuleData model)
        {
            model = await PrepareQueryGetRecentHttpRequestsByModuleModel(model);
            return View("GetRecentHttpRequestsByModule", model);
        }

        [Route("Queries/GetRecentHttpRequestsByModulePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentHttpRequestsByModulePartial(AuditLogGetRecentHttpRequestsByModuleData model)
        {
            model = await PrepareQueryGetRecentHttpRequestsByModuleModel(model);
            return PartialView("_GetRecentHttpRequestsByModuleTable", model);
        }

        private async Task<AuditLogGetRecentHttpRequestsByModuleData> PrepareQueryGetRecentHttpRequestsByModuleModel(AuditLogGetRecentHttpRequestsByModuleData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsGetRecentHttpRequestsByModuleAsync(model.AuditLogRequestModule, pageNumber: model.CurrentPage, pageSize: model.PageSize);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                var hasMore = model.List.Count >= model.PageSize;
                var seen = ((model.CurrentPage - 1) * model.PageSize) + model.List.Count;
                model.NumberOfRecord = seen;
                model.TotalPage = hasMore ? model.CurrentPage + 1 : model.CurrentPage;
                model.HasMoreRecords = hasMore;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsDailyHttpRequestsByDay")]
        public async Task<IActionResult> QueryStatsDailyHttpRequestsByDay()
        {
            var model = GetModel<AuditLogStatsDailyHttpRequestsByDayData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsDailyHttpRequestsByDayModel(model);
            return View("StatsDailyHttpRequestsByDay", model);
        }

        [Route("Queries/StatsDailyHttpRequestsByDay")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsDailyHttpRequestsByDay(AuditLogStatsDailyHttpRequestsByDayData model)
        {
            model = await PrepareQueryStatsDailyHttpRequestsByDayModel(model);
            return View("StatsDailyHttpRequestsByDay", model);
        }

        [Route("Queries/StatsDailyHttpRequestsByDayPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsDailyHttpRequestsByDayPartial(AuditLogStatsDailyHttpRequestsByDayData model)
        {
            model = await PrepareQueryStatsDailyHttpRequestsByDayModel(model);
            return PartialView("_StatsDailyHttpRequestsByDayTable", model);
        }

        private async Task<AuditLogStatsDailyHttpRequestsByDayData> PrepareQueryStatsDailyHttpRequestsByDayModel(AuditLogStatsDailyHttpRequestsByDayData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsDailyHttpRequestsByDayAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsDailyHttpRequestsByDayByModule")]
        public async Task<IActionResult> QueryStatsDailyHttpRequestsByDayByModule()
        {
            var model = GetModel<AuditLogStatsDailyHttpRequestsByDayByModuleData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsDailyHttpRequestsByDayByModuleModel(model);
            return View("StatsDailyHttpRequestsByDayByModule", model);
        }

        [Route("Queries/StatsDailyHttpRequestsByDayByModule")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsDailyHttpRequestsByDayByModule(AuditLogStatsDailyHttpRequestsByDayByModuleData model)
        {
            model = await PrepareQueryStatsDailyHttpRequestsByDayByModuleModel(model);
            return View("StatsDailyHttpRequestsByDayByModule", model);
        }

        [Route("Queries/StatsDailyHttpRequestsByDayByModulePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsDailyHttpRequestsByDayByModulePartial(AuditLogStatsDailyHttpRequestsByDayByModuleData model)
        {
            model = await PrepareQueryStatsDailyHttpRequestsByDayByModuleModel(model);
            return PartialView("_StatsDailyHttpRequestsByDayByModuleTable", model);
        }

        private async Task<AuditLogStatsDailyHttpRequestsByDayByModuleData> PrepareQueryStatsDailyHttpRequestsByDayByModuleModel(AuditLogStatsDailyHttpRequestsByDayByModuleData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsDailyHttpRequestsByDayByModuleAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsHourlyHttpRequestsByModule")]
        public async Task<IActionResult> QueryStatsHourlyHttpRequestsByModule()
        {
            var model = GetModel<AuditLogStatsHourlyHttpRequestsByModuleData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsHourlyHttpRequestsByModuleModel(model);
            return View("StatsHourlyHttpRequestsByModule", model);
        }

        [Route("Queries/StatsHourlyHttpRequestsByModule")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHourlyHttpRequestsByModule(AuditLogStatsHourlyHttpRequestsByModuleData model)
        {
            model = await PrepareQueryStatsHourlyHttpRequestsByModuleModel(model);
            return View("StatsHourlyHttpRequestsByModule", model);
        }

        [Route("Queries/StatsHourlyHttpRequestsByModulePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHourlyHttpRequestsByModulePartial(AuditLogStatsHourlyHttpRequestsByModuleData model)
        {
            model = await PrepareQueryStatsHourlyHttpRequestsByModuleModel(model);
            return PartialView("_StatsHourlyHttpRequestsByModuleTable", model);
        }

        private async Task<AuditLogStatsHourlyHttpRequestsByModuleData> PrepareQueryStatsHourlyHttpRequestsByModuleModel(AuditLogStatsHourlyHttpRequestsByModuleData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsHourlyHttpRequestsByModuleAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsHttpStatusCodes")]
        public async Task<IActionResult> QueryStatsHttpStatusCodes()
        {
            var model = GetModel<AuditLogStatsHttpStatusCodesData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsHttpStatusCodesModel(model);
            return View("StatsHttpStatusCodes", model);
        }

        [Route("Queries/StatsHttpStatusCodes")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHttpStatusCodes(AuditLogStatsHttpStatusCodesData model)
        {
            model = await PrepareQueryStatsHttpStatusCodesModel(model);
            return View("StatsHttpStatusCodes", model);
        }

        [Route("Queries/StatsHttpStatusCodesPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHttpStatusCodesPartial(AuditLogStatsHttpStatusCodesData model)
        {
            model = await PrepareQueryStatsHttpStatusCodesModel(model);
            return PartialView("_StatsHttpStatusCodesTable", model);
        }

        private async Task<AuditLogStatsHttpStatusCodesData> PrepareQueryStatsHttpStatusCodesModel(AuditLogStatsHttpStatusCodesData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsHttpStatusCodesAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsHttpStatusCodesByModule")]
        public async Task<IActionResult> QueryStatsHttpStatusCodesByModule()
        {
            var model = GetModel<AuditLogStatsHttpStatusCodesByModuleData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsHttpStatusCodesByModuleModel(model);
            return View("StatsHttpStatusCodesByModule", model);
        }

        [Route("Queries/StatsHttpStatusCodesByModule")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHttpStatusCodesByModule(AuditLogStatsHttpStatusCodesByModuleData model)
        {
            model = await PrepareQueryStatsHttpStatusCodesByModuleModel(model);
            return View("StatsHttpStatusCodesByModule", model);
        }

        [Route("Queries/StatsHttpStatusCodesByModulePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHttpStatusCodesByModulePartial(AuditLogStatsHttpStatusCodesByModuleData model)
        {
            model = await PrepareQueryStatsHttpStatusCodesByModuleModel(model);
            return PartialView("_StatsHttpStatusCodesByModuleTable", model);
        }

        private async Task<AuditLogStatsHttpStatusCodesByModuleData> PrepareQueryStatsHttpStatusCodesByModuleModel(AuditLogStatsHttpStatusCodesByModuleData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsHttpStatusCodesByModuleAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsHttpStatusCodesLast24HoursByModule")]
        public async Task<IActionResult> QueryStatsHttpStatusCodesLast24HoursByModule()
        {
            var model = GetModel<AuditLogStatsHttpStatusCodesLast24HoursByModuleData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsHttpStatusCodesLast24HoursByModuleModel(model);
            return View("StatsHttpStatusCodesLast24HoursByModule", model);
        }

        [Route("Queries/StatsHttpStatusCodesLast24HoursByModule")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHttpStatusCodesLast24HoursByModule(AuditLogStatsHttpStatusCodesLast24HoursByModuleData model)
        {
            model = await PrepareQueryStatsHttpStatusCodesLast24HoursByModuleModel(model);
            return View("StatsHttpStatusCodesLast24HoursByModule", model);
        }

        [Route("Queries/StatsHttpStatusCodesLast24HoursByModulePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsHttpStatusCodesLast24HoursByModulePartial(AuditLogStatsHttpStatusCodesLast24HoursByModuleData model)
        {
            model = await PrepareQueryStatsHttpStatusCodesLast24HoursByModuleModel(model);
            return PartialView("_StatsHttpStatusCodesLast24HoursByModuleTable", model);
        }

        private async Task<AuditLogStatsHttpStatusCodesLast24HoursByModuleData> PrepareQueryStatsHttpStatusCodesLast24HoursByModuleModel(AuditLogStatsHttpStatusCodesLast24HoursByModuleData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsHttpStatusCodesLast24HoursByModuleAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsLastHourHttpRequests")]
        public async Task<IActionResult> QueryStatsLastHourHttpRequests()
        {
            var model = GetModel<AuditLogStatsLastHourHttpRequestsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsLastHourHttpRequestsModel(model);
            return View("StatsLastHourHttpRequests", model);
        }

        [Route("Queries/StatsLastHourHttpRequests")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsLastHourHttpRequests(AuditLogStatsLastHourHttpRequestsData model)
        {
            model = await PrepareQueryStatsLastHourHttpRequestsModel(model);
            return View("StatsLastHourHttpRequests", model);
        }

        [Route("Queries/StatsLastHourHttpRequestsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsLastHourHttpRequestsPartial(AuditLogStatsLastHourHttpRequestsData model)
        {
            model = await PrepareQueryStatsLastHourHttpRequestsModel(model);
            return PartialView("_StatsLastHourHttpRequestsTable", model);
        }

        private async Task<AuditLogStatsLastHourHttpRequestsData> PrepareQueryStatsLastHourHttpRequestsModel(AuditLogStatsLastHourHttpRequestsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsLastHourHttpRequestsAsync();
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsMonthlyHttpRequests")]
        public async Task<IActionResult> QueryStatsMonthlyHttpRequests()
        {
            var model = GetModel<AuditLogStatsMonthlyHttpRequestsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsMonthlyHttpRequestsModel(model);
            return View("StatsMonthlyHttpRequests", model);
        }

        [Route("Queries/StatsMonthlyHttpRequests")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsMonthlyHttpRequests(AuditLogStatsMonthlyHttpRequestsData model)
        {
            model = await PrepareQueryStatsMonthlyHttpRequestsModel(model);
            return View("StatsMonthlyHttpRequests", model);
        }

        [Route("Queries/StatsMonthlyHttpRequestsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsMonthlyHttpRequestsPartial(AuditLogStatsMonthlyHttpRequestsData model)
        {
            model = await PrepareQueryStatsMonthlyHttpRequestsModel(model);
            return PartialView("_StatsMonthlyHttpRequestsTable", model);
        }

        private async Task<AuditLogStatsMonthlyHttpRequestsData> PrepareQueryStatsMonthlyHttpRequestsModel(AuditLogStatsMonthlyHttpRequestsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsMonthlyHttpRequestsAsync();
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsTodayHttpRequests")]
        public async Task<IActionResult> QueryStatsTodayHttpRequests()
        {
            var model = GetModel<AuditLogStatsTodayHttpRequestsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsTodayHttpRequestsModel(model);
            return View("StatsTodayHttpRequests", model);
        }

        [Route("Queries/StatsTodayHttpRequests")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsTodayHttpRequests(AuditLogStatsTodayHttpRequestsData model)
        {
            model = await PrepareQueryStatsTodayHttpRequestsModel(model);
            return View("StatsTodayHttpRequests", model);
        }

        [Route("Queries/StatsTodayHttpRequestsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsTodayHttpRequestsPartial(AuditLogStatsTodayHttpRequestsData model)
        {
            model = await PrepareQueryStatsTodayHttpRequestsModel(model);
            return PartialView("_StatsTodayHttpRequestsTable", model);
        }

        private async Task<AuditLogStatsTodayHttpRequestsData> PrepareQueryStatsTodayHttpRequestsModel(AuditLogStatsTodayHttpRequestsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsTodayHttpRequestsAsync();
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsTopHttpServicesByModule")]
        public async Task<IActionResult> QueryStatsTopHttpServicesByModule()
        {
            var model = GetModel<AuditLogStatsTopHttpServicesByModuleData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsTopHttpServicesByModuleModel(model);
            return View("StatsTopHttpServicesByModule", model);
        }

        [Route("Queries/StatsTopHttpServicesByModule")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsTopHttpServicesByModule(AuditLogStatsTopHttpServicesByModuleData model)
        {
            model = await PrepareQueryStatsTopHttpServicesByModuleModel(model);
            return View("StatsTopHttpServicesByModule", model);
        }

        [Route("Queries/StatsTopHttpServicesByModulePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsTopHttpServicesByModulePartial(AuditLogStatsTopHttpServicesByModuleData model)
        {
            model = await PrepareQueryStatsTopHttpServicesByModuleModel(model);
            return PartialView("_StatsTopHttpServicesByModuleTable", model);
        }

        private async Task<AuditLogStatsTopHttpServicesByModuleData> PrepareQueryStatsTopHttpServicesByModuleModel(AuditLogStatsTopHttpServicesByModuleData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsTopHttpServicesByModuleAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsTotalHttpRequestsByModule")]
        public async Task<IActionResult> QueryStatsTotalHttpRequestsByModule()
        {
            var model = GetModel<AuditLogStatsTotalHttpRequestsByModuleData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsTotalHttpRequestsByModuleModel(model);
            return View("StatsTotalHttpRequestsByModule", model);
        }

        [Route("Queries/StatsTotalHttpRequestsByModule")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsTotalHttpRequestsByModule(AuditLogStatsTotalHttpRequestsByModuleData model)
        {
            model = await PrepareQueryStatsTotalHttpRequestsByModuleModel(model);
            return View("StatsTotalHttpRequestsByModule", model);
        }

        [Route("Queries/StatsTotalHttpRequestsByModulePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsTotalHttpRequestsByModulePartial(AuditLogStatsTotalHttpRequestsByModuleData model)
        {
            model = await PrepareQueryStatsTotalHttpRequestsByModuleModel(model);
            return PartialView("_StatsTotalHttpRequestsByModuleTable", model);
        }

        private async Task<AuditLogStatsTotalHttpRequestsByModuleData> PrepareQueryStatsTotalHttpRequestsByModuleModel(AuditLogStatsTotalHttpRequestsByModuleData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsTotalHttpRequestsByModuleAsync();
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsWeeklyHttpRequests")]
        public async Task<IActionResult> QueryStatsWeeklyHttpRequests()
        {
            var model = GetModel<AuditLogStatsWeeklyHttpRequestsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsWeeklyHttpRequestsModel(model);
            return View("StatsWeeklyHttpRequests", model);
        }

        [Route("Queries/StatsWeeklyHttpRequests")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsWeeklyHttpRequests(AuditLogStatsWeeklyHttpRequestsData model)
        {
            model = await PrepareQueryStatsWeeklyHttpRequestsModel(model);
            return View("StatsWeeklyHttpRequests", model);
        }

        [Route("Queries/StatsWeeklyHttpRequestsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsWeeklyHttpRequestsPartial(AuditLogStatsWeeklyHttpRequestsData model)
        {
            model = await PrepareQueryStatsWeeklyHttpRequestsModel(model);
            return PartialView("_StatsWeeklyHttpRequestsTable", model);
        }

        private async Task<AuditLogStatsWeeklyHttpRequestsData> PrepareQueryStatsWeeklyHttpRequestsModel(AuditLogStatsWeeklyHttpRequestsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsWeeklyHttpRequestsAsync();
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsYearlyHttpRequests")]
        public async Task<IActionResult> QueryStatsYearlyHttpRequests()
        {
            var model = GetModel<AuditLogStatsYearlyHttpRequestsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsYearlyHttpRequestsModel(model);
            return View("StatsYearlyHttpRequests", model);
        }

        [Route("Queries/StatsYearlyHttpRequests")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsYearlyHttpRequests(AuditLogStatsYearlyHttpRequestsData model)
        {
            model = await PrepareQueryStatsYearlyHttpRequestsModel(model);
            return View("StatsYearlyHttpRequests", model);
        }

        [Route("Queries/StatsYearlyHttpRequestsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsYearlyHttpRequestsPartial(AuditLogStatsYearlyHttpRequestsData model)
        {
            model = await PrepareQueryStatsYearlyHttpRequestsModel(model);
            return PartialView("_StatsYearlyHttpRequestsTable", model);
        }

        private async Task<AuditLogStatsYearlyHttpRequestsData> PrepareQueryStatsYearlyHttpRequestsModel(AuditLogStatsYearlyHttpRequestsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsYearlyHttpRequestsAsync();
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/StatsYesterdayHttpRequests")]
        public async Task<IActionResult> QueryStatsYesterdayHttpRequests()
        {
            var model = GetModel<AuditLogStatsYesterdayHttpRequestsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryStatsYesterdayHttpRequestsModel(model);
            return View("StatsYesterdayHttpRequests", model);
        }

        [Route("Queries/StatsYesterdayHttpRequests")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsYesterdayHttpRequests(AuditLogStatsYesterdayHttpRequestsData model)
        {
            model = await PrepareQueryStatsYesterdayHttpRequestsModel(model);
            return View("StatsYesterdayHttpRequests", model);
        }

        [Route("Queries/StatsYesterdayHttpRequestsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryStatsYesterdayHttpRequestsPartial(AuditLogStatsYesterdayHttpRequestsData model)
        {
            model = await PrepareQueryStatsYesterdayHttpRequestsModel(model);
            return PartialView("_StatsYesterdayHttpRequestsTable", model);
        }

        private async Task<AuditLogStatsYesterdayHttpRequestsData> PrepareQueryStatsYesterdayHttpRequestsModel(AuditLogStatsYesterdayHttpRequestsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.AuditLogsStatsYesterdayHttpRequestsAsync();
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }
    }
}