// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System.Net.Http.Json;
using QuickCode.QuickCode.Infrastructure.Integration.Models;
using QuickCode.QuickCode.Infrastructure.Integration.Security;

namespace QuickCode.QuickCode.EventListenerService.Security;

public sealed class GatewayServiceTokenHttpGenerator : IGatewayServiceTokenGenerator
{
    private readonly IConfiguration _configuration;
    private readonly IHttpClientFactory _httpClientFactory;

    public GatewayServiceTokenHttpGenerator(IConfiguration configuration, IHttpClientFactory httpClientFactory)
    {
        _configuration = configuration;
        _httpClientFactory = httpClientFactory;
    }

    public string Create(string targetModuleName, string? userId = null, string? permissionGroup = null, string? userEmail = null)
    {
        var gatewayBaseUrl = ResolveGatewayBaseUrl();
        var internalTokenKey = ResolveInternalTokenKey();
        var client = _httpClientFactory.CreateClient();
        var request = new HttpRequestMessage(HttpMethod.Post, $"{gatewayBaseUrl}api/gateway/service-token")
        {
            Content = JsonContent.Create(new GatewayServiceTokenIssueRequest
            {
                TargetModuleName = targetModuleName
            })
        };
        request.Headers.Add(GatewayServiceTokenSettings.InternalTokenHeaderName, internalTokenKey);

        var response = client.SendAsync(request).GetAwaiter().GetResult();
        response.EnsureSuccessStatusCode();
        var payload = response.Content.ReadFromJsonAsync<GatewayServiceTokenIssueResponse>().GetAwaiter().GetResult();

        if (string.IsNullOrWhiteSpace(payload?.Token))
        {
            throw new InvalidOperationException("Gateway service token response was empty.");
        }

        return payload.Token;
    }

    private string ResolveGatewayBaseUrl()
    {
        var gatewayUrl = _configuration["QuickcodeClients:GatewayApi"];
        if (string.IsNullOrWhiteSpace(gatewayUrl))
        {
            throw new InvalidOperationException("QuickcodeClients:GatewayApi is not configured for Event Listener Service.");
        }

        return gatewayUrl.EndsWith("/") ? gatewayUrl : $"{gatewayUrl}/";
    }

    private static string ResolveInternalTokenKey()
    {
        var key = Environment.GetEnvironmentVariable(GatewayServiceTokenSettings.InternalTokenKeyEnvVar)
            ?? Environment.GetEnvironmentVariable(GatewayServiceTokenSettings.QuickCodeInternalTokenKeyEnvVar);
        if (!string.IsNullOrWhiteSpace(key))
        {
            return key;
        }

        throw new InvalidOperationException(
            $"Gateway internal token key is missing. Set {GatewayServiceTokenSettings.InternalTokenKeyEnvVar} or {GatewayServiceTokenSettings.QuickCodeInternalTokenKeyEnvVar}.");
    }

    private sealed class GatewayServiceTokenIssueRequest
    {
        public string TargetModuleName { get; set; } = string.Empty;
    }

    private sealed class GatewayServiceTokenIssueResponse
    {
        public string Token { get; set; } = string.Empty;
    }
}
