// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Quickcode.QuickcodeModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class ProjectAnalyses
    {
        public static class Command
        {
            private const string _prefix = "QuickcodeModule.ProjectAnalyses.Command";
            private const string _sqlScriptStem = "ProjectAnalyses";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string SetStatus => ResourceKey($"{_sqlScriptStem}.SetStatus.g.sql");
            public static string SetCurrent => ResourceKey($"{_sqlScriptStem}.SetCurrent.g.sql");
            public static string MarkNotCurrent => ResourceKey($"{_sqlScriptStem}.MarkNotCurrent.g.sql");
        }
    }
}