// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.QuickCode.IdentityModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class ApiKey
    {
        public static class Query
        {
            private const string _prefix = "IdentityModule.ApiKey.Query";
            private const string _sqlScriptStem = "ApiKey";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetApiKeyByPrefix => ResourceKey($"{_sqlScriptStem}.GetApiKeyByPrefix.g.sql");
            public static string ApiKeyNameIsExists => ResourceKey($"{_sqlScriptStem}.ApiKeyNameIsExists.g.sql");
            public static string GetByPrefix => ResourceKey($"{_sqlScriptStem}.GetByPrefix.g.sql");
            public static string GetByName => ResourceKey($"{_sqlScriptStem}.GetByName.g.sql");
            public static string GetByStatus => ResourceKey($"{_sqlScriptStem}.GetByStatus.g.sql");
            public static string GetByPermissionGroup => ResourceKey($"{_sqlScriptStem}.GetByPermissionGroup.g.sql");
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
        }
    }
}