// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.Quickcode.QuickcodeModule.Application.Services.ProjectModulePrompt;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.ProjectModulePrompt;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.Infrastructure.Web.Helpers;
using QuickCode.Quickcode.Application.Contracts;

namespace QuickCode.Quickcode.QuickcodeModule.Application.Tests.Services.ProjectModulePrompt
{
    public class ProjectModulePromptTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IProjectModulePromptRepository> _repositoryMock;
        private readonly Mock<ILogger<ProjectModulePromptService>> _loggerMock;
        private readonly ProjectModulePromptService _service;
        public ProjectModulePromptTests()
        {
            _repositoryMock = new Mock<IProjectModulePromptRepository>();
            _loggerMock = new Mock<ILogger<ProjectModulePromptService>>();
            _service = new ProjectModulePromptService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task GetItemAsync_Should_Return_Success_When_Item_Exists()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ProjectModulePromptDto>("tr");
            var fakeResponse = new RepoResponse<ProjectModulePromptDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id, fakeDto.ModuleName, fakeDto.AiType)).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.GetItemAsync(fakeDto.Id, fakeDto.ModuleName, fakeDto.AiType);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id, fakeDto.ModuleName, fakeDto.AiType), Times.Once);
        }

        [Fact]
        public async Task GetItemAsync_Should_Return_NotFound_When_Item_Does_Not_Exist()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ProjectModulePromptDto>("tr");
            var fakeResponse = new RepoResponse<ProjectModulePromptDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id, fakeDto.ModuleName, fakeDto.AiType)).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.GetItemAsync(fakeDto.Id, fakeDto.ModuleName, fakeDto.AiType);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        [Fact]
        public async Task ListAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeList = TestDataGenerator.CreateFakes<ProjectModulePromptDto>("tr");
            var fakeResponse = new RepoResponse<List<ProjectModulePromptDto>>(fakeList, "Success");
            _repositoryMock.Setup(r => r.ListAsync(It.IsAny<int?>(), It.IsAny<int?>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.ListAsync(1, 10);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeList, result.Value.Items);
            Assert.Null(result.Value.TotalCount);
            _repositoryMock.Verify(r => r.ListAsync(It.IsAny<int?>(), It.IsAny<int?>()), Times.Once);
            _repositoryMock.Verify(r => r.CountAsync(), Times.Never);
        }

        [Fact]
        public async Task ListAsync_Should_Include_TotalCount_When_Requested()
        {
            // Arrange
            var fakeList = TestDataGenerator.CreateFakes<ProjectModulePromptDto>("tr");
            var fakeResponse = new RepoResponse<List<ProjectModulePromptDto>>(fakeList, "Success");
            var fakeCount = new RepoResponse<int>(5, "Success");
            _repositoryMock.Setup(r => r.ListAsync(It.IsAny<int?>(), It.IsAny<int?>())).ReturnsAsync(fakeResponse);
            _repositoryMock.Setup(r => r.CountAsync()).ReturnsAsync(fakeCount);
            // Act
            var result = await _service.ListAsync(1, 10, true);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeList, result.Value.Items);
            Assert.Equal(5, result.Value.TotalCount);
            _repositoryMock.Verify(r => r.ListAsync(It.IsAny<int?>(), It.IsAny<int?>()), Times.Once);
            _repositoryMock.Verify(r => r.CountAsync(), Times.Once);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}