// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Quickcode.Application.Contracts;
using QuickCode.Quickcode.QuickcodeModule.Domain.Entities;
using QuickCode.Quickcode.QuickcodeModule.Application.Interfaces.Repositories;
using QuickCode.Quickcode.QuickcodeModule.Application.Dtos.GenerationStep;
using QuickCode.Quickcode.QuickcodeModule.Domain.Enums;

namespace QuickCode.Quickcode.QuickcodeModule.Application.Services.GenerationStep
{
    public partial interface IGenerationStepService
    {
        Task<Response<GenerationStepDto>> InsertAsync(GenerationStepDto request);
        Task<Response<bool>> DeleteAsync(GenerationStepDto request);
        Task<Response<bool>> UpdateAsync(int id, GenerationStepDto request);
        Task<Response<ListResult<GenerationStepDto>>> ListAsync(int? pageNumber, int? pageSize, bool includeCount = false);
        Task<Response<GenerationStepDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<GetByNameResponseDto>> GetByNameAsync(string generationStepName);
        Task<Response<List<GetByNeedsResponseDto>>> GetByNeedsAsync(string? generationStepNeeds);
    }
}