<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>769e0bb0-20d8-4529-9df8-42738fe5cdda</UserSecretsId>
		<GenerateCode>True</GenerateCode>
		<SwaggerSource>Project</SwaggerSource>
		<NswagQuickCodeApiUrl>https://api.quickcode.net/swagger/v1/swagger.json</NswagQuickCodeApiUrl>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<NoWarn>CS8669;AD0001</NoWarn>
		
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="AWSSDK.S3" />
		<PackageReference Include="BSolutions.Bocons" />
		<PackageReference Include="NSwag.MSBuild">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="SkiaSharp" />
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="Microsoft.Web.LibraryManager.Build" />
		<PackageReference Include="NSwag.AspNetCore" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" />
		<RuntimeHostConfigurationOption Include="System.Drawing.EnableUnixSupport" Value="true" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\Shared\QuickCode.QuickCode.Infrastructure.Web\QuickCode.QuickCode.Infrastructure.Web.csproj">
	    <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
	  </ProjectReference>
	  <ProjectReference Include="..\..\Shared\QuickCode.QuickCode.Application.Contracts\QuickCode.QuickCode.Application.Contracts.csproj" />
	</ItemGroup>
</Project>